/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import Mathlib.Order.Antisymmetrization
import Mathlib.Order.UpperLower.Closure
import Mathlib.Order.UpperLower.CompleteLattice
import QLambda.QuantumInstrument
import QLambda.QuantumPower

/-!
# Fixed-register instrument powerdomain

This module separates three layers:

1. finite Kraus-presented computations;
2. their observational refinement preorder and antisymmetrization;
3. the plain lower-set completion and its functorial structure.

The register dimension `n` is fixed externally.  This carrier is a
complete continuous lattice, but it is deliberately not installed as an
`IsQuantumPowerModel`: principal lower sets are compact, so pushforward
fails local continuity at genuine outcome limits; moreover Scott-open
event tests are not a congruence for value-dependent quantum bind.  The
file therefore records a useful intermediate construction and the exact
boundary that a rounded-ideal/TT redesign must cross.
-/

open Matrix
open scoped MatrixOrder

namespace QLambda

open Scott1972.ContinuousLattice

universe u

namespace LowerSet

variable {α β γ : Type*} [Preorder α] [Preorder β] [Preorder γ]

/-- Principal lower set generated by one basis element. -/
def principal (a : α) : LowerSet α :=
  lowerClosure {a}

theorem mem_principal {a b : α} :
    b ∈ principal a ↔ b ≤ a := by
  simp [principal]

theorem principal_le_iff_mem {a : α} {A : LowerSet α} :
    principal a ≤ A ↔ a ∈ A := by
  constructor
  · intro h
    exact LowerSet.coe_subset_coe.mpr h (mem_principal.mpr le_rfl)
  · intro ha
    exact LowerSet.coe_subset_coe.mp fun b hb =>
      A.lower (mem_principal.mp hb) ha

/-- Finitely generated principal lower sets are compact in the
lower-set lattice. -/
theorem principal_wayBelow_self (a : α) :
    principal a ≪ principal a := by
  rw [wayBelow_self_iff_scottOpen_Ici]
  refine ⟨fun A B hAB hA => hA.trans hAB, ?_⟩
  intro S hS hSdir hsup
  have haSup : a ∈ sSup S :=
    principal_le_iff_mem.mp (Set.mem_Ici.mp hsup)
  obtain ⟨A, hAS, haA⟩ := LowerSet.mem_sSup_iff.mp haSup
  exact ⟨A, hAS, Set.mem_Ici.mpr (principal_le_iff_mem.mpr haA)⟩

/-- The lattice of lower sets of any preorder is algebraic, hence
continuous: every lower set is the supremum of its principal lower
subsets. -/
theorem isContinuousLattice : IsContinuousLattice (LowerSet α) := by
  intro A
  refine ⟨?_, ?_⟩
  · intro B hB
    exact hB.le
  · intro Z hZ
    apply LowerSet.coe_subset_coe.mp
    intro a ha
    have hpa : principal a ≪ A :=
      (principal_wayBelow_self a).trans_le (principal_le_iff_mem.mpr ha)
    have hpZ : principal a ≤ Z := hZ hpa
    exact LowerSet.coe_subset_coe.mpr hpZ (mem_principal.mpr le_rfl)

/-- Covariant lower-set extension of an order homomorphism. -/
def mapOrderHom (f : α →o β) (A : LowerSet α) : LowerSet β :=
  lowerClosure (f '' (A : Set α))

theorem mem_mapOrderHom {f : α →o β} {A : LowerSet α} {b : β} :
    b ∈ mapOrderHom f A ↔ ∃ a ∈ A, b ≤ f a := by
  simp [mapOrderHom, mem_lowerClosure]

theorem mapOrderHom_mono (f : α →o β) : Monotone (mapOrderHom f) := by
  intro A B hAB
  apply lowerClosure_mono
  exact Set.image_mono (LowerSet.coe_subset_coe.mpr hAB)

theorem mapOrderHom_le {f g : α →o β} (hfg : f ≤ g) :
    mapOrderHom f ≤ mapOrderHom g := by
  intro A
  rw [mapOrderHom]
  apply lowerClosure_le.mpr
  rintro b ⟨a, ha, rfl⟩
  exact mem_mapOrderHom.mpr ⟨a, ha, hfg a⟩

@[simp] theorem mapOrderHom_id (A : LowerSet α) :
    mapOrderHom OrderHom.id A = A := by
  ext a
  change a ∈ mapOrderHom OrderHom.id A ↔ a ∈ A
  constructor
  · rw [mem_mapOrderHom]
    rintro ⟨b, hb, hab⟩
    exact A.lower hab hb
  · intro ha
    exact mem_mapOrderHom.mpr ⟨a, ha, le_rfl⟩

theorem mapOrderHom_comp (g : β →o γ) (f : α →o β) (A : LowerSet α) :
    mapOrderHom (g.comp f) A = mapOrderHom g (mapOrderHom f A) := by
  ext c
  change c ∈ mapOrderHom (g.comp f) A ↔ c ∈ mapOrderHom g (mapOrderHom f A)
  constructor
  · rw [mem_mapOrderHom]
    rintro ⟨a, ha, hca⟩
    exact mem_mapOrderHom.mpr
      ⟨f a, mem_mapOrderHom.mpr ⟨a, ha, le_rfl⟩, hca⟩
  · rw [mem_mapOrderHom]
    rintro ⟨b, hb, hcb⟩
    rw [mem_mapOrderHom] at hb
    obtain ⟨a, ha, hbf⟩ := hb
    exact mem_mapOrderHom.mpr ⟨a, ha, hcb.trans (g.mono hbf)⟩

theorem mapOrderHom_sSup (f : α →o β) (S : Set (LowerSet α)) :
    mapOrderHom f (sSup S) = sSup (mapOrderHom f '' S) := by
  ext b
  change b ∈ mapOrderHom f (sSup S) ↔
    b ∈ sSup (mapOrderHom f '' S)
  constructor
  · rw [mem_mapOrderHom]
    rintro ⟨a, ha, hba⟩
    rw [LowerSet.mem_sSup_iff] at ha
    obtain ⟨A, hAS, haA⟩ := ha
    rw [LowerSet.mem_sSup_iff]
    exact ⟨mapOrderHom f A, ⟨A, hAS, rfl⟩,
      mem_mapOrderHom.mpr ⟨a, haA, hba⟩⟩
  · rw [LowerSet.mem_sSup_iff]
    rintro ⟨B, ⟨A, hAS, rfl⟩, hb⟩
    rw [mem_mapOrderHom] at hb ⊢
    obtain ⟨a, haA, hba⟩ := hb
    exact ⟨a, LowerSet.mem_sSup_iff.mpr ⟨A, hAS, haA⟩, hba⟩

end LowerSet

namespace FiniteInstrumentComp

variable {n : ℕ} {D E : Type u}

/-- Kraus branches whose returned values lie in `U`.  Their concatenation
denotes the sum of those CP branches and is independent of list order at
the Choi level. -/
noncomputable def selectedKraus (μ : FiniteInstrumentComp n D) (U : Set D) :
    KrausFamily n n := by
  classical
  exact ((Finset.univ.filter fun o : μ.Outcome => μ.value o ∈ U).toList).flatMap μ.branch

/-- Choi denotation of the branches selected by an outcome test. -/
noncomputable def testChoi (μ : FiniteInstrumentComp n D) (U : Set D) :
    Matrix (Fin n × Fin n) (Fin n × Fin n) ℂ := by
  classical
  exact ∑ o : μ.Outcome,
    if μ.value o ∈ U then KrausFamily.choi (μ.branch o) else 0

/-- Observational refinement of finite instruments.  Every Scott-open
outcome test must receive a smaller CP map in Choi/Loewner order. -/
def Refines [CompleteLattice D] (μ ν : FiniteInstrumentComp n D) : Prop :=
  ∀ U : Set D, ScottOpen U → μ.testChoi U ≤ ν.testChoi U

theorem refines_refl [CompleteLattice D] (μ : FiniteInstrumentComp n D) :
    Refines μ μ :=
  fun _ _ => le_rfl

theorem refines_trans [CompleteLattice D] {μ ν ξ : FiniteInstrumentComp n D}
    (hμν : Refines μ ν) (hνξ : Refines ν ξ) : Refines μ ξ :=
  fun U hU => (hμν U hU).trans (hνξ U hU)

noncomputable instance instPreorderFiniteInstrumentComp [CompleteLattice D] :
    Preorder (FiniteInstrumentComp n D) where
  le := Refines
  le_refl := refines_refl
  le_trans _ _ _ := refines_trans

theorem le_def [CompleteLattice D] {μ ν : FiniteInstrumentComp n D} :
    μ ≤ ν ↔ ∀ U : Set D, ScottOpen U → μ.testChoi U ≤ ν.testChoi U :=
  Iff.rfl

theorem selectedKraus_map [CompleteLattice D] [CompleteLattice E]
    (f : ScottMap D E) (μ : FiniteInstrumentComp n D) (U : Set E) :
    (μ.map f).selectedKraus U = μ.selectedKraus (f ⁻¹' U) := by
  classical
  rfl

theorem testChoi_map [CompleteLattice D] [CompleteLattice E]
    (f : ScottMap D E) (μ : FiniteInstrumentComp n D) (U : Set E) :
    (μ.map f).testChoi U = μ.testChoi (f ⁻¹' U) := by
  rfl

/-- Pushforward of finite instruments respects observational refinement. -/
theorem map_mono [CompleteLattice D] [CompleteLattice E] (f : ScottMap D E) :
    Monotone (FiniteInstrumentComp.map (n := n) (f : D → E)) := by
  intro μ ν hμν U hU
  rw [testChoi_map (n := n), testChoi_map (n := n)]
  exact hμν (f ⁻¹' U)
    (scottOpen_preimage ((proposition_2_5 (f : D → E)).mp f.continuous) hU)

/-- Pointwise larger result maps produce observationally larger
pushforwards. -/
theorem map_le_map [CompleteLattice D] [CompleteLattice E]
    {f g : ScottMap D E} (hfg : f ≤ g) (μ : FiniteInstrumentComp n D) :
    μ.map f ≤ μ.map g := by
  intro U hU
  classical
  unfold testChoi
  apply Finset.sum_le_sum
  intro o _
  change (if f (μ.value o) ∈ U then KrausFamily.choi (μ.branch o) else 0) ≤
    if g (μ.value o) ∈ U then KrausFamily.choi (μ.branch o) else 0
  by_cases hf : f (μ.value o) ∈ U
  · have hg : g (μ.value o) ∈ U := hU.1 (hfg (μ.value o)) hf
    simp [hf, hg]
  · simp only [hf, ↓reduceIte]
    by_cases hg : g (μ.value o) ∈ U
    · simp [hg, KrausFamily.choi_nonneg]
    · simp [hg]

/-- Pushforward as an order homomorphism on finite presentations. -/
noncomputable def mapHom [CompleteLattice D] [CompleteLattice E] (f : ScottMap D E) :
    FiniteInstrumentComp n D →o FiniteInstrumentComp n E :=
  ⟨FiniteInstrumentComp.map (n := n) (f : D → E), map_mono (n := n) f⟩

end FiniteInstrumentComp

/-- Finite instruments modulo mutual observational refinement. -/
abbrev SemanticInstrument (n : ℕ) (D : Type u) [CompleteLattice D] :=
  Antisymmetrization (FiniteInstrumentComp n D) (· ≤ ·)

/-- Complete lattice generated by finite semantic instruments under
downward closure.  Arbitrary joins add Hoare-style nondeterministic
closure; they are not quantum measurement outcomes. -/
abbrev InstrumentPower (n : ℕ) (D : Type u) [CompleteLattice D] :=
  LowerSet (SemanticInstrument n D)

namespace InstrumentPower

variable {n : ℕ} {D E : Type u} [CompleteLattice D] [CompleteLattice E]

/-- The lower-set completion is a continuous lattice independently of
the approximation properties of its outcome domain. -/
theorem isContinuousLattice :
    IsContinuousLattice (InstrumentPower n D) :=
  LowerSet.isContinuousLattice

/-- Pushforward on the antisymmetrized finite semantic basis. -/
noncomputable def basisMap (f : ScottMap D E) :
    SemanticInstrument n D →o SemanticInstrument n E :=
  (FiniteInstrumentComp.mapHom f).antisymmetrization

theorem basisMap_le {f g : ScottMap D E} (hfg : f ≤ g) :
    basisMap (n := n) f ≤ basisMap (n := n) g := by
  intro a
  refine Antisymmetrization.induction_on (· ≤ ·) a ?_
  intro μ
  rw [basisMap, basisMap,
    OrderHom.antisymmetrization_apply_mk,
    OrderHom.antisymmetrization_apply_mk,
    toAntisymmetrization_le_toAntisymmetrization_iff]
  exact FiniteInstrumentComp.map_le_map hfg μ

@[simp] theorem basisMap_id :
    basisMap (n := n) (ScottMap.idMap : ScottMap D D) = OrderHom.id := by
  apply OrderHom.ext
  funext a
  refine Antisymmetrization.induction_on (· ≤ ·) a ?_
  intro μ
  rw [basisMap, OrderHom.antisymmetrization_apply_mk]
  change toAntisymmetrization (· ≤ ·)
      (FiniteInstrumentComp.map (n := n)
        (ScottMap.idMap : D → D) μ) =
    toAntisymmetrization (· ≤ ·) μ
  have hid : (ScottMap.idMap : D → D) = id := by
    funext d
    rfl
  rw [hid, FiniteInstrumentComp.map_id]

theorem basisMap_comp {F : Type u} [CompleteLattice F]
    (g : ScottMap E F) (f : ScottMap D E) :
    basisMap (n := n) (g.comp f) =
      (basisMap (n := n) g).comp (basisMap (n := n) f) := by
  apply OrderHom.ext
  funext a
  refine Antisymmetrization.induction_on (· ≤ ·) a ?_
  intro μ
  rw [basisMap, OrderHom.antisymmetrization_apply_mk]
  change toAntisymmetrization (· ≤ ·)
      (FiniteInstrumentComp.map (n := n)
        ((g : E → F) ∘ (f : D → E)) μ) =
    basisMap (n := n) g
      (basisMap (n := n) f (toAntisymmetrization (· ≤ ·) μ))
  rw [basisMap, basisMap,
    OrderHom.antisymmetrization_apply_mk,
    OrderHom.antisymmetrization_apply_mk]
  apply congrArg (toAntisymmetrization (· ≤ ·))
  exact FiniteInstrumentComp.map_comp (g : E → F) (f : D → E) μ

/-- Embed a finite computation as its principal lower set. -/
noncomputable def ofFinite (μ : FiniteInstrumentComp n D) : InstrumentPower n D :=
  LowerSet.principal (toAntisymmetrization (· ≤ ·) μ)

theorem ofFinite_le_iff {μ : FiniteInstrumentComp n D}
    {A : InstrumentPower n D} :
    ofFinite μ ≤ A ↔ toAntisymmetrization (· ≤ ·) μ ∈ A :=
  LowerSet.principal_le_iff_mem

theorem ofFinite_mono :
    Monotone (ofFinite (n := n) (D := D)) := by
  intro μ ν hμν
  rw [ofFinite_le_iff]
  exact LowerSet.mem_principal.mpr (toAntisymmetrization_mono hμν)

/-- Lower-set extension of pushforward along a Scott map. -/
noncomputable def map (f : ScottMap D E) (A : InstrumentPower n D) :
    InstrumentPower n E :=
  LowerSet.mapOrderHom (basisMap f) A

theorem map_mono (f : ScottMap D E) : Monotone (map (n := n) f) := by
  exact LowerSet.mapOrderHom_mono (basisMap f)

/-- Pushforward preserves all suprema, hence in particular directed
suprema. -/
theorem map_sSup (f : ScottMap D E) (S : Set (InstrumentPower n D)) :
    map (n := n) f (sSup S) = sSup (map (n := n) f '' S) :=
  LowerSet.mapOrderHom_sSup (basisMap f) S

theorem map_preservesDirectedSup (f : ScottMap D E) :
    PreservesDirectedSup (map (n := n) f) :=
  fun S _ _ => map_sSup f S

/-- Scott-continuous pushforward on the completed powerdomain. -/
noncomputable def mapScott (f : ScottMap D E) :
    ScottMap (InstrumentPower n D) (InstrumentPower n E) :=
  ⟨map (n := n) f, continuous_of_preservesDirectedSup (map_preservesDirectedSup f)⟩

theorem mapScott_le {f g : ScottMap D E} (hfg : f ≤ g) :
    mapScott (n := n) f ≤ mapScott (n := n) g :=
  LowerSet.mapOrderHom_le (basisMap_le hfg)

@[simp] theorem map_id (A : InstrumentPower n D) :
    map (n := n) (ScottMap.idMap : ScottMap D D) A = A := by
  rw [map, basisMap_id]
  exact LowerSet.mapOrderHom_id A

theorem map_comp {F : Type u} [CompleteLattice F]
    (g : ScottMap E F) (f : ScottMap D E) (A : InstrumentPower n D) :
    map (n := n) (g.comp f) A = map (n := n) g (map (n := n) f A) := by
  rw [map, map, map, basisMap_comp]
  exact LowerSet.mapOrderHom_comp (basisMap g) (basisMap f) A

end InstrumentPower

end QLambda
