/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import QLambda.ObservationBasis

/-!
# Saturated rounded theories

This file constructs the continuous lattice of rounded theories of
strict rational Choi/output tokens.  The auxiliary basis relation first
allows semantic weakening and then requires a strict rational
strengthening.  Consequently its rounded lower sets are saturated under
the full semantic entailment preorder, not merely syntactic inclusion.
-/

open Set

namespace QLambda

open Scott1972.ContinuousLattice

universe u v w

/-- An abstract interpolative basis. -/
structure AbstractBasis (α : Type u) where
  below : α → α → Prop
  trans : ∀ {a b c}, below a b → below b c → below a c
  interpolate : ∀ {a c}, below a c → ∃ b, below a b ∧ below b c

namespace RoundedTheory

variable {α : Type u} (B : AbstractBasis α)

/-- One-step rounded lower closure. -/
def round (s : Set α) : Set α :=
  {a | ∃ b ∈ s, B.below a b}

theorem round_mono : Monotone (round B) := by
  intro s t hst a
  rintro ⟨b, hb, hab⟩
  exact ⟨b, hst hb, hab⟩

theorem round_idempotent (s : Set α) :
    round B (round B s) = round B s := by
  ext a
  constructor
  · rintro ⟨b, ⟨c, hc, hbc⟩, hab⟩
    exact ⟨c, hc, B.trans hab hbc⟩
  · rintro ⟨c, hc, hac⟩
    obtain ⟨b, hab, hbc⟩ := B.interpolate hac
    exact ⟨b, ⟨c, hc, hbc⟩, hab⟩

/-- A rounded theory is a fixed point of the basis rounding operator. -/
structure Carrier where
  carrier : Set α
  rounded : round B carrier = carrier

instance : SetLike (Carrier B) α where
  coe A := A.carrier
  coe_injective A C h := by
    cases A
    cases C
    simp only [Carrier.mk.injEq]
    exact h

@[ext]
theorem ext {A C : Carrier B} (h : (A : Set α) = C) : A = C :=
  SetLike.coe_injective h

instance : PartialOrder (Carrier B) :=
  PartialOrder.lift (fun A => (A : Set α)) SetLike.coe_injective

/-- The rounded principal generated by a basis element. -/
def principal (b : α) : Carrier B :=
  ⟨round B {b}, round_idempotent B {b}⟩

@[simp]
theorem mem_principal {a b : α} :
    a ∈ principal B b ↔ B.below a b := by
  change a ∈ round B {b} ↔ B.below a b
  simp [round]

theorem principal_le {b : α} {A : Carrier B} (hb : b ∈ A) :
    principal B b ≤ A := by
  intro a ha
  change a ∈ A.carrier
  change a ∈ round B {b} at ha
  have haround : a ∈ round B A.carrier := by
    exact ⟨b, hb, (by simpa [round] using ha)⟩
  rw [A.rounded] at haround
  exact haround

/-- Rounded theories are closed under arbitrary unions. -/
def union (S : Set (Carrier B)) : Carrier B where
  carrier := {a | ∃ A ∈ S, a ∈ A}
  rounded := by
    ext a
    constructor
    · rintro ⟨b, ⟨A, hAS, hbA⟩, hab⟩
      refine ⟨A, hAS, ?_⟩
      change a ∈ A.carrier
      have ha : a ∈ round B A.carrier := ⟨b, hbA, hab⟩
      rw [A.rounded] at ha
      exact ha
    · rintro ⟨A, hAS, haA⟩
      have ha : a ∈ round B A.carrier := by
        rw [A.rounded]
        exact haA
      obtain ⟨b, hbA, hab⟩ := ha
      exact ⟨b, ⟨A, hAS, hbA⟩, hab⟩

instance : SupSet (Carrier B) :=
  ⟨union B⟩

@[simp]
theorem mem_sSup {S : Set (Carrier B)} {a : α} :
    a ∈ sSup S ↔ ∃ A ∈ S, a ∈ A :=
  Iff.rfl

theorem isLUB_sSup (S : Set (Carrier B)) : IsLUB S (sSup S) := by
  constructor
  · intro A hAS a ha
    exact ⟨A, hAS, ha⟩
  · intro C hC a
    rintro ⟨A, hAS, ha⟩
    exact hC hAS ha

noncomputable instance : CompleteLattice (Carrier B) :=
  completeLatticeOfSup (Carrier B) (isLUB_sSup B)

/-- Membership of a basis element is Scott-open in the theory lattice. -/
theorem scottOpen_mem (b : α) :
    ScottOpen {A : Carrier B | b ∈ A} := by
  constructor
  · intro A C hAC hbA
    exact hAC hbA
  · intro S hS hdir hb
    change b ∈ (sSup S : Carrier B) at hb
    change ∃ A ∈ S, b ∈ A at hb
    obtain ⟨A, hAS, hbA⟩ := hb
    exact ⟨A, hAS, hbA⟩

/-- A rounded principal is way below every theory containing its
generator. -/
theorem principal_wayBelow {b : α} {A : Carrier B} (hb : b ∈ A) :
    principal B b ≪ A := by
  refine ⟨{C : Carrier B | b ∈ C}, scottOpen_mem B b, hb, ?_⟩
  intro C hbC
  exact principal_le B hbC

/-- Every rounded theory is the supremum of the rounded principals way
below it. -/
theorem isContinuousLattice : IsContinuousLattice (Carrier B) := by
  intro A
  constructor
  · intro C hC
    exact hC.le
  · intro C hC a ha
    have haround : a ∈ round B A.carrier := by
      rw [A.rounded]
      exact ha
    obtain ⟨b, hbA, hab⟩ := haround
    have hp : principal B b ≪ A := principal_wayBelow B hbA
    exact hC hp (show a ∈ principal B b by rwa [mem_principal])

end RoundedTheory

namespace CodedAtom

variable {n : ℕ} {ι : Type v}

/-- Strict strengthening of a coded atom: the output code and rational
vector are unchanged while the threshold strictly increases. -/
def StronglyBelow (a b : CodedAtom n ι) : Prop :=
  a.1.1 = b.1.1 ∧ a.2 = b.2 ∧ a.1.2.1 < b.1.2.1

theorem stronglyBelow_trans {a b c : CodedAtom n ι}
    (hab : StronglyBelow a b) (hbc : StronglyBelow b c) :
    StronglyBelow a c :=
  ⟨hab.1.trans hbc.1, hab.2.1.trans hbc.2.1,
    hab.2.2.trans hbc.2.2⟩

theorem stronglyBelow_interpolate {a c : CodedAtom n ι}
    (hac : StronglyBelow a c) :
    ∃ b, StronglyBelow a b ∧ StronglyBelow b c := by
  let q : ℚ := (a.1.2.1 + c.1.2.1) / 2
  have hq0 : 0 ≤ q := by
    have ha0 := a.1.2.2
    have hc0 := c.1.2.2
    dsimp [q]
    linarith
  let b : CodedAtom n ι := ((a.1.1, ⟨q, hq0⟩), a.2)
  refine ⟨b, ?_, ?_⟩
  · exact ⟨rfl, rfl, by dsimp [b, q]; linarith [hac.2.2]⟩
  · exact ⟨hac.1, hac.2.1, by dsimp [b, q]; linarith [hac.2.2]⟩

theorem stronglyBelow_holds {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) {a b : CodedAtom n ι}
    (hab : StronglyBelow a b) {μ : FiniteInstrumentComp n D}
    (hb : Holds C b μ) : Holds C a μ := by
  apply ObservationAtom.holds_of_threshold_lt
    (a := toObservation C a) (b := toObservation C b)
  · exact congrArg C.observe hab.2.1
  · exact hab.1
  · change (a.1.2.1 : ℝ) ≤ (b.1.2.1 : ℝ)
    exact_mod_cast hab.2.2.le
  · exact hb

end CodedAtom

namespace CodedToken

variable {n : ℕ} {ι : Type v}

/-- Pointwise strict strengthening of every conjunct. -/
def StronglyBelow (t s : CodedToken n ι) : Prop :=
  ∀ a ∈ t, ∃ b ∈ s, CodedAtom.StronglyBelow a b

theorem stronglyBelow_trans {t s r : CodedToken n ι}
    (hts : StronglyBelow t s) (hsr : StronglyBelow s r) :
    StronglyBelow t r := by
  intro a ha
  obtain ⟨b, hb, hab⟩ := hts a ha
  obtain ⟨c, hc, hbc⟩ := hsr b hb
  exact ⟨c, hc, CodedAtom.stronglyBelow_trans hab hbc⟩

theorem stronglyBelow_interpolate {t r : CodedToken n ι}
    (htr : StronglyBelow t r) :
    ∃ s, StronglyBelow t s ∧ StronglyBelow s r := by
  induction t with
  | nil =>
      exact ⟨[], by simp [StronglyBelow], by simp [StronglyBelow]⟩
  | cons a t ih =>
      obtain ⟨c, hc, hac⟩ := htr a (by simp)
      obtain ⟨b, hab, hbc⟩ := CodedAtom.stronglyBelow_interpolate hac
      have htr' : StronglyBelow t r := by
        intro x hx
        exact htr x (by simp [hx])
      obtain ⟨s, hts, hsr⟩ := ih htr'
      refine ⟨b :: s, ?_, ?_⟩
      · intro x hx
        rcases List.mem_cons.mp hx with rfl | hx
        · exact ⟨b, by simp, hab⟩
        · obtain ⟨y, hy, hxy⟩ := hts x hx
          exact ⟨y, by simp [hy], hxy⟩
      · intro x hx
        rcases List.mem_cons.mp hx with rfl | hx
        · exact ⟨c, hc, hbc⟩
        · exact hsr x hx

/-- Semantic entailment between coded tokens. -/
def Entails {D : Type u} [CompleteLattice D] (C : OutputCode ι D)
    (t s : CodedToken n ι) : Prop :=
  ObservationToken.Entails (toObservation C t) (toObservation C s)

theorem entails_refl {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) (t : CodedToken n ι) :
    Entails C t t :=
  fun _ h => h

theorem entails_trans {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) {t s r : CodedToken n ι}
    (hts : Entails C t s) (hsr : Entails C s r) :
    Entails C t r :=
  fun μ hr => hts μ (hsr μ hr)

theorem stronglyBelow_entails {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) {t s : CodedToken n ι}
    (hts : StronglyBelow t s) : Entails C t s := by
  intro μ hs a ha
  obtain ⟨x, hx, rfl⟩ := List.mem_map.mp ha
  obtain ⟨y, hy, hxy⟩ := hts x hx
  apply CodedAtom.stronglyBelow_holds C hxy
  exact hs _ (List.mem_map.mpr ⟨y, hy, rfl⟩)

/-- The saturated auxiliary relation: semantic weakening followed by a
strict rational strengthening. -/
def RoundedBelow {D : Type u} [CompleteLattice D] (C : OutputCode ι D)
    (t s : CodedToken n ι) : Prop :=
  ∃ u, Entails C t u ∧ StronglyBelow u s

theorem roundedBelow_entails {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) {t s : CodedToken n ι}
    (hts : RoundedBelow C t s) : Entails C t s := by
  obtain ⟨u, htu, hus⟩ := hts
  exact entails_trans C htu (stronglyBelow_entails C hus)

theorem roundedBelow_trans {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) {t s r : CodedToken n ι}
    (hts : RoundedBelow C t s) (hsr : RoundedBelow C s r) :
    RoundedBelow C t r := by
  obtain ⟨v, hsv, hvr⟩ := hsr
  exact ⟨v, entails_trans C (roundedBelow_entails C hts) hsv, hvr⟩

theorem roundedBelow_interpolate {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) {t r : CodedToken n ι}
    (htr : RoundedBelow C t r) :
    ∃ s, RoundedBelow C t s ∧ RoundedBelow C s r := by
  obtain ⟨u, htu, hur⟩ := htr
  obtain ⟨s, hus, hsr⟩ := stronglyBelow_interpolate hur
  refine ⟨s, ⟨u, htu, hus⟩, ?_⟩
  exact ⟨s, entails_refl C s, hsr⟩

/-- The interpolative basis of coded tokens for a chosen output code. -/
def roundedBasis {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) : AbstractBasis (CodedToken n ι) where
  below := RoundedBelow C
  trans := roundedBelow_trans C
  interpolate := roundedBelow_interpolate C

end CodedToken

/-- The saturated rounded-theory completion of strict rational
Choi/output tokens. -/
abbrev TokenTheory (n : ℕ) {ι : Type v} {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) :=
  RoundedTheory.Carrier (CodedToken.roundedBasis (n := n) C)

/-- The token-theory completion is a continuous lattice. -/
theorem tokenTheory_isContinuousLattice
    (n : ℕ) {ι : Type v} {D : Type u} [CompleteLattice D]
    (C : OutputCode ι D) :
    IsContinuousLattice (TokenTheory n C) :=
  RoundedTheory.isContinuousLattice (CodedToken.roundedBasis (n := n) C)

/-- Membership in a token theory is saturated under the full semantic
entailment preorder. -/
theorem TokenTheory.entailment_saturated
    {n : ℕ} {ι : Type v} {D : Type u} [CompleteLattice D]
    {C : OutputCode ι D} {A : TokenTheory n C}
    {t s : CodedToken n ι} (hts : CodedToken.Entails C t s)
    (hs : s ∈ A) : t ∈ A := by
  have hsround : s ∈
      RoundedTheory.round (CodedToken.roundedBasis (n := n) C) A.carrier := by
    rw [A.rounded]
    exact hs
  obtain ⟨r, hrA, hsr⟩ := hsround
  obtain ⟨u, hsu, hur⟩ := hsr
  have htr : CodedToken.RoundedBelow C t r :=
    ⟨u, CodedToken.entails_trans C hts hsu, hur⟩
  have ht : t ∈
      RoundedTheory.round (CodedToken.roundedBasis (n := n) C) A.carrier :=
    ⟨r, hrA, htr⟩
  change t ∈ A.carrier
  rw [← A.rounded]
  exact ht

/-- Every assertion in a token theory has a strictly rounded semantic
strengthening in the same theory. -/
theorem TokenTheory.exists_rounding
    {n : ℕ} {ι : Type v} {D : Type u} [CompleteLattice D]
    {C : OutputCode ι D} (A : TokenTheory n C)
    {t : CodedToken n ι} (ht : t ∈ A) :
    ∃ s ∈ A, CodedToken.RoundedBelow C t s := by
  have : t ∈ RoundedTheory.round (CodedToken.roundedBasis (n := n) C)
      A.carrier := by
    rw [A.rounded]
    exact ht
  exact this

/-- The canonical token completion obtained from the countable output
basis of an `ωQVA`. -/
noncomputable abbrev OmegaTokenTheory
    (n : ℕ) (D : Type u) [CompleteLattice D] [IsOmegaQVA D] :=
  TokenTheory n (CountableOutputBasis.ofOmegaQVAFiniteUnion (D := D)).code

theorem omegaTokenTheory_isContinuousLattice
    (n : ℕ) (D : Type u) [CompleteLattice D] [IsOmegaQVA D] :
    IsContinuousLattice (OmegaTokenTheory n D) :=
  tokenTheory_isContinuousLattice n
    (CountableOutputBasis.ofOmegaQVAFiniteUnion (D := D)).code

end QLambda
