/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import QLambda.Soundness
import QLambda.TTExternalChoice
import QLambda.TTPhysicalEmbedding

/-!
# Complete computation choice for tagged TT continuations

The weighted relation is the least relation generated by the two physical
probabilistic branches and closure under Kleisli sequencing on either side.
The right-closure constructor is essential: a raw CPS continuation need not
preserve a probabilistic operation in its continuation argument, so the
top-level syntactic relation from `TTProbChoice` cannot honestly prove
call-by-value application-right closure.
-/

namespace QLambda

open Scott1972.ContinuousLattice

universe u

namespace TTContinuation

variable {n : ℕ}
variable {D E : Type u} [CompleteLattice D] [CompleteLattice E]

/-- The three concrete choice operations.  Its internal-choice inequalities
are proved pointwise as part of the value, before it is registered. -/
@[instance_reducible] noncomputable def externalComputationChoice :
    HasComputationChoice (TTExternalContinuationPower n D) where
  prob p := liftTaggedBinary (probChoice (n := n) (D := D) p)
  intern := liftTaggedBinary (internalChoice (n := n) (D := D))
  extern := externalChoice
  left_le_intern := by
    intro q r i
    exact le_internalChoice_left (q i) (r i)
  right_le_intern := by
    intro q r i
    exact le_internalChoice_right (q i) (r i)

noncomputable instance instHasComputationChoiceTTExternal :
    HasComputationChoice (TTExternalContinuationPower n D) :=
  externalComputationChoice

theorem computation_prob_apply (p : Prob)
    (q r : TTExternalContinuationPower n D) (i : ℕ) :
    HasComputationChoice.prob p (q, r) i =
      probChoice p (q i, r i) := rfl

theorem computation_intern_apply
    (q r : TTExternalContinuationPower n D) (i : ℕ) :
    HasComputationChoice.intern (q, r) i =
      internalChoice (q i, r i) := rfl

/-- Kleisli extension of a tagged continuation preserves TT internal
choice exactly, because bind is evaluated coordinatewise. -/
theorem taggedBind_intern
    (h : ScottMap D (TTExternalContinuationPower n E))
    (q r : TTExternalContinuationPower n D) :
    taggedBindScott (n := n) h
        (HasComputationChoice.intern (q, r)) =
      HasComputationChoice.intern
        (taggedBindScott (n := n) h q,
          taggedBindScott (n := n) h r) := by
  funext i
  have hsrc :=
    taggedBind_atCoordinate (n := n) (E := E) h
      (HasComputationChoice.intern (q, r)) i
  have hleft := taggedBind_atCoordinate (n := n) (E := E) h q i
  have hright := taggedBind_atCoordinate (n := n) (E := E) h r i
  change TTContinuation.bind ((atCoordinate i).comp h)
      (HasComputationChoice.intern (q, r) i) =
    HasComputationChoice.intern
      (taggedBindScott (n := n) h q, taggedBindScott (n := n) h r) i
  rw [computation_intern_apply, bind_internalChoice,
    computation_intern_apply, hleft, hright]

theorem computation_extern_select_false
    (q r : TTExternalContinuationPower n D) :
    selectBranch false (HasComputationChoice.extern (q, r)) = q :=
  selectBranch_false_external q r

theorem computation_extern_select_true
    (q r : TTExternalContinuationPower n D) :
    selectBranch true (HasComputationChoice.extern (q, r)) = r :=
  selectBranch_true_external q r

noncomputable instance instHasExternalSelectionTTExternal :
    HasExternalSelection (TTExternalContinuationPower n D) where
  select := selectBranch
  select_false := computation_extern_select_false
  select_true := computation_extern_select_true

/-- Honest weighted branches generated by physical probabilistic choice and
the two Kleisli-context closure principles needed by call-by-value
application. -/
inductive TaggedWeightedBranch (n : ℕ) {D : Type u} [CompleteLattice D] :
    TTExternalContinuationPower n D → Prob →
      TTExternalContinuationPower n D → Prop
  | probLeft (p : Prob)
      (q r : TTExternalContinuationPower n D)
      (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1) :
      TaggedWeightedBranch n
        (liftTaggedBinary (probChoice (n := n) (D := D) p) (q, r)) p q
  | probRight (p : Prob)
      (q r : TTExternalContinuationPower n D)
      (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1) :
      TaggedWeightedBranch n
        (liftTaggedBinary (probChoice (n := n) (D := D) p) (q, r))
        (1 - p) r
  | bindLeft {source branch : TTExternalContinuationPower n D} {p : Prob}
      (hbranch : TaggedWeightedBranch n source p branch)
      (h : ScottMap D (TTExternalContinuationPower n D)) :
      TaggedWeightedBranch n
        (taggedBindScott h source) p (taggedBindScott h branch)
  | bindRight
      (source : TTExternalContinuationPower n D) (p : Prob)
      (h h' : ScottMap D (TTExternalContinuationPower n D))
      (hbranch : ∀ d, TaggedWeightedBranch n (h d) p (h' d)) :
      TaggedWeightedBranch n
        (taggedBindScott h source) p (taggedBindScott h' source)

noncomputable instance instHasWeightedBranchSemanticsTTExternal :
    HasWeightedBranchSemantics (TTExternalContinuationPower n D) where
  weightedBranch := TaggedWeightedBranch n
  prob_left := by
    intro p q r hp₀ hp₁
    exact TaggedWeightedBranch.probLeft p q r hp₀ hp₁
  prob_right := by
    intro p q r hp₀ hp₁
    exact TaggedWeightedBranch.probRight p q r hp₀ hp₁

/-- The generated relation is closed under application-left by `bindLeft`
and under application-right by first closing each unfolded function and then
using `bindRight`. -/
noncomputable instance instHasWeightedApplicationClosureTTExternal
    (D₀ : QDomain.{0})
    (j₀ : IsContinuousLatticeProjection D₀.carrier
      (QuantumFunctor
        (QModel (TTExternalContinuationPower n)) D₀.carrier)) :
    HasWeightedApplicationClosure (TTExternalContinuationPower n) D₀ j₀ where
  app_left := by
    intro mf mf' ma p ρ hbranch
    exact TaggedWeightedBranch.bindLeft hbranch
      (applyContinuation (Q := TTExternalContinuationPower n)
        (D₀ := D₀) (j₀ := j₀) ma ρ)
  app_right := by
    intro mf ma ma' p ρ hbranch
    apply TaggedWeightedBranch.bindRight (mf ρ) p
      (applyContinuation (Q := TTExternalContinuationPower n)
        (D₀ := D₀) (j₀ := j₀) ma ρ)
      (applyContinuation (Q := TTExternalContinuationPower n)
        (D₀ := D₀) (j₀ := j₀) ma' ρ)
    intro f
    exact TaggedWeightedBranch.bindLeft hbranch
      (semanticUnfold (Q := TTExternalContinuationPower n)
        (D₀ := D₀) (j₀ := j₀) f)

end TTContinuation

end QLambda
