/- 
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import QLambda.Effects
import QLambda.TTResultOperations

/-!
# Weighted aggregation of TT results

The construction in this file is generated by finite TT observations of a
genuine probabilistic coin instrument.  In particular, it is not defined as
lattice join.  Endpoints are routed explicitly; this both gives exact endpoint
laws on the completed carrier and avoids pretending that the token basis has
already been proved separating for zero-weight branches.
-/

open Matrix Set
open scoped BigOperators ComplexOrder MatrixOrder

namespace QLambda

open Scott1972.ContinuousLattice

namespace FiniteInstrumentComp

variable {n : ℕ}

/-- A two-outcome coin whose branches have CP weights `p` and `1-p`.
The bounds are data because outside `[0,1]` these branches need not form a
trace-nonincreasing instrument. -/
noncomputable def weightedCoin (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1) :
    FiniteInstrumentComp n Bool where
  Outcome := Bool
  branch := fun b =>
    if b then
      KrausFamily.scale (Real.sqrt (1 - p)) (KrausFamily.identity n)
    else
      KrausFamily.scale (Real.sqrt p) (KrausFamily.identity n)
  value := id
  trace_nonincreasing := by
    intro ρ hρ
    rw [Fintype.sum_bool]
    change
      (Matrix.trace (KrausFamily.applyMat
        (KrausFamily.scale (Real.sqrt (1 - p))
          (KrausFamily.identity n)) ρ)).re +
      (Matrix.trace (KrausFamily.applyMat
        (KrausFamily.scale (Real.sqrt p)
          (KrausFamily.identity n)) ρ)).re ≤
      (Matrix.trace ρ).re
    rw [KrausFamily.applyMat_scale, KrausFamily.applyMat_scale,
      KrausFamily.applyMat_identity]
    have hp' : 0 ≤ 1 - p := sub_nonneg.mpr hp₁
    have hsqrt_p : (Real.sqrt p : ℂ) * star (Real.sqrt p : ℂ) = p := by
      simp only [Complex.star_def, Complex.conj_ofReal, ← Complex.ofReal_mul]
      norm_cast
      simpa [pow_two] using Real.sq_sqrt hp₀
    have hsqrt_q :
        (Real.sqrt (1 - p) : ℂ) * star (Real.sqrt (1 - p) : ℂ) = 1 - p := by
      simp only [Complex.star_def, Complex.conj_ofReal, ← Complex.ofReal_mul]
      norm_cast
      simpa [pow_two] using Real.sq_sqrt hp'
    rw [hsqrt_p, hsqrt_q]
    rw [Matrix.trace_smul, Matrix.trace_smul]
    have hre (x : ℝ) :
        (((x : ℂ) • Matrix.trace ρ).re) = x * (Matrix.trace ρ).re := by
      rw [smul_eq_mul, Complex.mul_re]
      simp
    rw [← Complex.ofReal_one, ← Complex.ofReal_sub]
    rw [hre, hre]
    ring_nf
    exact le_rfl

/-- Physical weighted combination of two finite result instruments. -/
noncomputable def weightedResult
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1)
    (μ ν : FiniteInstrumentComp n PUnit.{1}) :
    FiniteInstrumentComp n PUnit.{1} :=
  (weightedCoin (n := n) p hp₀ hp₁).bind fun b => if b then ν else μ

end FiniteInstrumentComp

namespace TTWeightedAggregation

variable {n : ℕ}

private def resultCode : OutputCode ℕ PUnit.{1} :=
  TTContinuation.resultCode

/-- Two branch-local finite observations force a target observation when the
corresponding finite result instruments are physically weighted. -/
def WeightedDerives
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1)
    (left right target : TTObservationToken n) : Prop :=
  ∀ μ ν : FiniteInstrumentComp n PUnit.{1},
    TTObservationToken.Holds resultCode left μ →
    TTObservationToken.Holds resultCode right ν →
    TTObservationToken.Holds resultCode target
      (μ.weightedResult p hp₀ hp₁ ν)

private def resultBasis (n : ℕ) :=
  TTObservationToken.roundedBasis (n := n) resultCode

/-- Interior, token-generated weighted aggregation. -/
noncomputable def core
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1)
    (T U : TTContinuation.TTResult n) :
    TTContinuation.TTResult n :=
  sSup {V | ∃ left ∈ T, ∃ right ∈ U, ∃ target,
    WeightedDerives p hp₀ hp₁ left right target ∧
    V = RoundedTheory.principal (resultBasis n) target}

theorem mem_core
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1)
    (T U : TTContinuation.TTResult n) (t : TTObservationToken n) :
    t ∈ core p hp₀ hp₁ T U ↔
      ∃ left ∈ T, ∃ right ∈ U, ∃ target,
        WeightedDerives p hp₀ hp₁ left right target ∧
        TTObservationToken.RoundedBelow resultCode t target := by
  rw [core, RoundedTheory.mem_sSup]
  constructor
  · rintro ⟨V, ⟨left, hleft, right, hright, target, hderives, rfl⟩, ht⟩
    exact ⟨left, hleft, right, hright, target, hderives,
      (RoundedTheory.mem_principal (B := resultBasis n)).mp ht⟩
  · rintro ⟨left, hleft, right, hright, target, hderives, ht⟩
    exact ⟨RoundedTheory.principal (resultBasis n) target,
      ⟨left, hleft, right, hright, target, hderives, rfl⟩,
      (RoundedTheory.mem_principal (B := resultBasis n)).2 ht⟩

theorem core_sSup
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1)
    {S : Set (TTContinuation.TTResult n × TTContinuation.TTResult n)}
    (_hS : S.Nonempty) (hdir : DirectedOn (· ≤ ·) S) :
    core p hp₀ hp₁ (sSup S).1 (sSup S).2 =
      sSup ((fun q => core p hp₀ hp₁ q.1 q.2) '' S) := by
  classical
  apply RoundedTheory.ext
  ext t
  change t ∈ core p hp₀ hp₁ (sSup S).1 (sSup S).2 ↔
    t ∈ (sSup ((fun q => core p hp₀ hp₁ q.1 q.2) '' S) :
      TTContinuation.TTResult n)
  rw [RoundedTheory.mem_sSup]
  constructor
  · intro ht
    obtain ⟨left, hleft, right, hright, target, hderives, httarget⟩ :=
      (mem_core p hp₀ hp₁ (sSup S).1 (sSup S).2 t).mp ht
    rw [Prod.fst_sSup, RoundedTheory.mem_sSup] at hleft
    rw [Prod.snd_sSup, RoundedTheory.mem_sSup] at hright
    obtain ⟨TL, ⟨qL, hqLS, rfl⟩, hleft⟩ := hleft
    obtain ⟨UR, ⟨qR, hqRS, rfl⟩, hright⟩ := hright
    obtain ⟨q, hqS, hLq, hRq⟩ := hdir qL hqLS qR hqRS
    refine ⟨core p hp₀ hp₁ q.1 q.2, ⟨q, hqS, rfl⟩, ?_⟩
    exact (mem_core p hp₀ hp₁ q.1 q.2 t).2
      ⟨left, hLq.1 hleft, right, hRq.2 hright,
        target, hderives, httarget⟩
  · rintro ⟨V, ⟨q, hqS, rfl⟩, ht⟩
    obtain ⟨left, hleft, right, hright, target, hderives, httarget⟩ :=
      (mem_core p hp₀ hp₁ q.1 q.2 t).mp ht
    apply (mem_core p hp₀ hp₁ (sSup S).1 (sSup S).2 t).2
    refine ⟨left, ?_, right, ?_, target, hderives, httarget⟩
    · rw [Prod.fst_sSup, RoundedTheory.mem_sSup]
      exact ⟨q.1, ⟨q, hqS, rfl⟩, hleft⟩
    · rw [Prod.snd_sSup, RoundedTheory.mem_sSup]
      exact ⟨q.2, ⟨q, hqS, rfl⟩, hright⟩

/-- The interior construction is jointly Scott-continuous in both results. -/
noncomputable def coreScott
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1) :
    ScottMap
      (TTContinuation.TTResult n × TTContinuation.TTResult n)
      (TTContinuation.TTResult n) :=
  ⟨fun q => core p hp₀ hp₁ q.1 q.2,
    continuous_of_preservesDirectedSup fun _ hS hdir =>
      core_sSup p hp₀ hp₁ hS hdir⟩

private noncomputable def fstResult :
    ScottMap
      (TTContinuation.TTResult n × TTContinuation.TTResult n)
      (TTContinuation.TTResult n) :=
  ⟨Prod.fst, continuous_of_preservesDirectedSup fun S _ _ =>
    Prod.fst_sSup S⟩

private noncomputable def sndResult :
    ScottMap
      (TTContinuation.TTResult n × TTContinuation.TTResult n)
      (TTContinuation.TTResult n) :=
  ⟨Prod.snd, continuous_of_preservesDirectedSup fun S _ _ =>
    Prod.snd_sSup S⟩

/-- Scott-continuous weighted aggregation.  Exact endpoints are part of the
definition; strictly interior weights use the token-generated physical
construction. -/
noncomputable def weightedResultScott
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1) :
    ScottMap
      (TTContinuation.TTResult n × TTContinuation.TTResult n)
      (TTContinuation.TTResult n) :=
  if p = 0 then sndResult
  else if p = 1 then fstResult
  else coreScott p hp₀ hp₁

@[simp]
theorem weightedResultScott_zero
    (T U : TTContinuation.TTResult n) :
    weightedResultScott (n := n) 0 (le_refl 0) zero_le_one (T, U) = U := by
  simp [weightedResultScott, sndResult]

@[simp]
theorem weightedResultScott_one
    (T U : TTContinuation.TTResult n) :
    weightedResultScott (n := n) 1 zero_le_one (le_refl 1) (T, U) = T := by
  simp [weightedResultScott, fstResult]

/-- At weight zero, weighted aggregation cannot be lattice join whenever the
discarded left result contributes genuinely new information. -/
theorem weightedResultScott_zero_ne_sup
    {T U : TTContinuation.TTResult n} (hTU : ¬ T ≤ U) :
    weightedResultScott (n := n) 0 (le_refl 0) zero_le_one (T, U) ≠
      T ⊔ U := by
  intro h
  apply hTU
  have hleft : T ≤ T ⊔ U := le_sup_left
  rw [weightedResultScott_zero] at h
  exact hleft.trans (le_of_eq h.symm)

/-- Symmetrically, at weight one the discarded right result prevents
identification with join whenever it is not already below the left result. -/
theorem weightedResultScott_one_ne_sup
    {T U : TTContinuation.TTResult n} (hUT : ¬ U ≤ T) :
    weightedResultScott (n := n) 1 zero_le_one (le_refl 1) (T, U) ≠
      T ⊔ U := by
  intro h
  apply hUT
  have hright : U ≤ T ⊔ U := le_sup_right
  rw [weightedResultScott_one] at h
  exact hright.trans (le_of_eq h.symm)

theorem weightedResultScott_interior
    (p : Prob) (hp₀ : 0 < p) (hp₁ : p < 1)
    (T U : TTContinuation.TTResult n) :
    weightedResultScott p hp₀.le hp₁.le (T, U) =
      core p hp₀.le hp₁.le T U := by
  simp [weightedResultScott, hp₀.ne', hp₁.ne]
  rfl

/-- The token-generated core agrees exactly with physical weighting whenever
both inputs are represented by finite result instruments.  The reverse
inclusion is the substantive direction: finite support is extracted from the
existing bind-approximation theorem for the two-outcome coin. -/
theorem core_satisfiedTTTheory
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1)
    (μ ν : FiniteInstrumentComp n PUnit.{1}) :
    core p hp₀ hp₁
        (μ.satisfiedTTTheory resultCode)
        (ν.satisfiedTTTheory resultCode) =
      (μ.weightedResult p hp₀ hp₁ ν).satisfiedTTTheory resultCode := by
  apply RoundedTheory.ext
  ext t
  constructor
  · intro ht
    obtain ⟨left, hleft, right, hright, target, hderives, httarget⟩ :=
      (mem_core p hp₀ hp₁
        (μ.satisfiedTTTheory resultCode)
        (ν.satisfiedTTTheory resultCode) t).mp ht
    have htarget :
        TTObservationToken.Holds resultCode target
          (μ.weightedResult p hp₀ hp₁ ν) :=
      hderives μ ν
        ((FiniteInstrumentComp.mem_satisfiedTTTheory resultCode μ left).mp hleft)
        ((FiniteInstrumentComp.mem_satisfiedTTTheory resultCode ν right).mp hright)
    exact TTObservationToken.roundedBelow_entails resultCode httarget
      (μ.weightedResult p hp₀ hp₁ ν) htarget
  · intro ht
    obtain ⟨target, httarget, htarget⟩ :=
      TTObservationToken.exists_stronglyBelow_holds resultCode
        (μ.weightedResult p hp₀ hp₁ ν) ht
    obtain ⟨sources, hsources, hall⟩ :=
      TTResultApproximation.exists_bind_source_tokens
        (FiniteInstrumentComp.weightedCoin (n := n) p hp₀ hp₁)
        target (fun b => if b then ν else μ) htarget
    let left := sources false
    let right := sources true
    apply (mem_core p hp₀ hp₁
      (μ.satisfiedTTTheory resultCode)
      (ν.satisfiedTTTheory resultCode) t).2
    refine ⟨left, ?_, right, ?_, target, ?_, ?_⟩
    · apply (FiniteInstrumentComp.mem_satisfiedTTTheory resultCode μ left).2
      simpa [left, resultCode, FiniteInstrumentComp.weightedCoin] using
        hsources false
    · apply (FiniteInstrumentComp.mem_satisfiedTTTheory resultCode ν right).2
      simpa [right, resultCode, FiniteInstrumentComp.weightedCoin] using
        hsources true
    · intro μ' ν' hleft hright
      change TTObservationToken.Holds resultCode target
        ((FiniteInstrumentComp.weightedCoin (n := n) p hp₀ hp₁).bind
          (fun b => if b then ν' else μ'))
      apply hall (fun b => if b then ν' else μ')
      intro b
      cases b
      · exact hleft
      · exact hright
    · exact ⟨t, TTObservationToken.entails_refl resultCode t, httarget⟩

/-- Exact finite-instrument agreement for every strictly interior weight. -/
theorem weightedResultScott_satisfied_interior
    (p : Prob) (hp₀ : 0 < p) (hp₁ : p < 1)
    (μ ν : FiniteInstrumentComp n PUnit.{1}) :
    weightedResultScott p hp₀.le hp₁.le
        (μ.satisfiedTTTheory resultCode,
          ν.satisfiedTTTheory resultCode) =
      (μ.weightedResult p hp₀.le hp₁.le ν).satisfiedTTTheory resultCode := by
  exact Eq.trans
    (weightedResultScott_interior p hp₀ hp₁
      (μ.satisfiedTTTheory resultCode)
      (ν.satisfiedTTTheory resultCode))
    (core_satisfiedTTTheory p hp₀.le hp₁.le μ ν)

theorem weightedResultScott_bot_left
    (p : Prob) (hp₀ : 0 < p) (hp₁ : p < 1)
    (U : TTContinuation.TTResult n) :
    weightedResultScott p hp₀.le hp₁.le (⊥, U) = ⊥ := by
  rw [weightedResultScott_interior p hp₀ hp₁]
  apply RoundedTheory.ext
  ext t
  constructor
  · intro ht
    obtain ⟨left, hleft, _⟩ :=
      (mem_core p hp₀.le hp₁.le ⊥ U t).mp ht
    have : False := by
      rw [← sSup_empty, RoundedTheory.mem_sSup] at hleft
      simpa using hleft
    exact this.elim
  · intro ht
    have : False := by
      rw [← sSup_empty] at ht
      have ht' := (RoundedTheory.mem_sSup (S := (∅ : Set
        (TTContinuation.TTResult n)))).mp ht
      simpa using ht'
    exact this.elim

theorem weightedResultScott_bot_right
    (p : Prob) (hp₀ : 0 < p) (hp₁ : p < 1)
    (T : TTContinuation.TTResult n) :
    weightedResultScott p hp₀.le hp₁.le (T, ⊥) = ⊥ := by
  rw [weightedResultScott_interior p hp₀ hp₁]
  apply RoundedTheory.ext
  ext t
  constructor
  · intro ht
    obtain ⟨_, _, right, hright, _⟩ :=
      (mem_core p hp₀.le hp₁.le T ⊥ t).mp ht
    have : False := by
      rw [← sSup_empty, RoundedTheory.mem_sSup] at hright
      simpa using hright
    exact this.elim
  · intro ht
    have : False := by
      rw [← sSup_empty] at ht
      have ht' := (RoundedTheory.mem_sSup (S := (∅ : Set
        (TTContinuation.TTResult n)))).mp ht
      simpa using ht'
    exact this.elim

/-- The token-generated interior operation preserves arbitrary (not merely
directed) suprema in the two arguments jointly. -/
theorem core_sSup_product
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1)
    (S U : Set (TTContinuation.TTResult n)) :
    core p hp₀ hp₁ (sSup S) (sSup U) =
      sSup ((fun q => core p hp₀ hp₁ q.1 q.2) '' (S ×ˢ U)) := by
  apply RoundedTheory.ext
  ext t
  change t ∈ core p hp₀ hp₁ (sSup S) (sSup U) ↔
    t ∈ (sSup ((fun q => core p hp₀ hp₁ q.1 q.2) '' (S ×ˢ U)) :
      TTContinuation.TTResult n)
  rw [RoundedTheory.mem_sSup]
  constructor
  · intro ht
    obtain ⟨left, hleft, right, hright, target, hderives, httarget⟩ :=
      (mem_core p hp₀ hp₁ (sSup S) (sSup U) t).mp ht
    rw [RoundedTheory.mem_sSup] at hleft hright
    obtain ⟨T, hTS, hleft⟩ := hleft
    obtain ⟨V, hVU, hright⟩ := hright
    refine ⟨core p hp₀ hp₁ T V, ?_, ?_⟩
    · exact ⟨(T, V), ⟨hTS, hVU⟩, rfl⟩
    · exact (mem_core p hp₀ hp₁ T V t).2
        ⟨left, hleft, right, hright, target, hderives, httarget⟩
  · rintro ⟨W, ⟨⟨T, V⟩, ⟨hTS, hVU⟩, rfl⟩, ht⟩
    obtain ⟨left, hleft, right, hright, target, hderives, httarget⟩ :=
      (mem_core p hp₀ hp₁ T V t).mp ht
    apply (mem_core p hp₀ hp₁ (sSup S) (sSup U) t).2
    refine ⟨left, ?_, right, ?_, target, hderives, httarget⟩
    · rw [RoundedTheory.mem_sSup]
      exact ⟨T, hTS, hleft⟩
    · rw [RoundedTheory.mem_sSup]
      exact ⟨V, hVU, hright⟩

/-- Physical weighted aggregation preserves arbitrary product suprema.  The
nonemptiness assumptions are necessary at the endpoints, where one projection
is discarded but the Cartesian product would otherwise be empty. -/
theorem weightedResultScott_sSup_product
    (p : Prob) (hp₀ : 0 ≤ p) (hp₁ : p ≤ 1)
    (S U : Set (TTContinuation.TTResult n))
    (hS : S.Nonempty) (hU : U.Nonempty) :
    weightedResultScott p hp₀ hp₁ (sSup S, sSup U) =
      sSup ((fun q => weightedResultScott p hp₀ hp₁ q) '' (S ×ˢ U)) := by
  by_cases hpzero : p = 0
  · subst p
    simp only [weightedResultScott_zero]
    apply le_antisymm
    · apply sSup_le
      intro V hVU
      obtain ⟨T, hTS⟩ := hS
      apply le_sSup
      refine ⟨(T, V), ⟨hTS, hVU⟩, ?_⟩
      simp
    · apply sSup_le
      rintro _ ⟨⟨T, V⟩, ⟨hTS, hVU⟩, rfl⟩
      simpa using le_sSup hVU
  · by_cases hpone : p = 1
    · subst p
      simp only [weightedResultScott_one]
      apply le_antisymm
      · apply sSup_le
        intro T hTS
        obtain ⟨V, hVU⟩ := hU
        apply le_sSup
        refine ⟨(T, V), ⟨hTS, hVU⟩, ?_⟩
        simp
      · apply sSup_le
        rintro _ ⟨⟨T, V⟩, ⟨hTS, hVU⟩, rfl⟩
        simpa using le_sSup hTS
    · rw [weightedResultScott, if_neg hpzero, if_neg hpone]
      change core p hp₀ hp₁ (sSup S) (sSup U) =
        sSup ((fun q => core p hp₀ hp₁ q.1 q.2) '' (S ×ˢ U))
      exact core_sSup_product p hp₀ hp₁ S U

end TTWeightedAggregation

end QLambda
