/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import Mathlib.LinearAlgebra.Matrix.Kronecker
import QLambda.Domain.QuantumCategory

/-!
# Symmetric monoidal closure of quantum relations

The tensor of quantum relations is generated pointwise by Kronecker
products of operators.  Matrix indices are transported from products of
finite types to the canonical `Fin (m * n)` presentation used by
`QuantumSet.tensor`.
-/

open Matrix
open scoped Kronecker

namespace QLambda.Domain

set_option allowUnsafeReducibility true in
attribute [local reducible] QuantumSet.tensor QuantumSet.dual

namespace QuantumRel

variable {X Y Z W A B C D : QuantumSet}

/-- Kronecker product, reindexed to the operator convention of tensor atoms. -/
noncomputable def opTensor
    {x : X.Atom} {y : Y.Atom} {a : A.Atom} {b : B.Atom}
    (r : QuantumSet.Op X Y x y) (s : QuantumSet.Op A B a b) :
    QuantumSet.Op (X.tensor A) (Y.tensor B) (x, a) (y, b) :=
  Matrix.reindex finProdFinEquiv finProdFinEquiv (r ⊗ₖ s)

@[simp] theorem opTensor_apply
    {x : X.Atom} {y : Y.Atom} {a : A.Atom} {b : B.Atom}
    (r : QuantumSet.Op X Y x y) (s : QuantumSet.Op A B a b)
    (i : Fin (Y.dim y * B.dim b)) (j : Fin (X.dim x * A.dim a)) :
    opTensor r s i j =
      r (finProdFinEquiv.symm i).1 (finProdFinEquiv.symm j).1 *
      s (finProdFinEquiv.symm i).2 (finProdFinEquiv.symm j).2 :=
  rfl

/-- Tensor of relations, generated by elementary Kronecker products. -/
noncomputable def tensor (R : QuantumRel X Y) (S : QuantumRel A B) :
    QuantumRel (X.tensor A) (Y.tensor B) where
  component xa yb :=
    Submodule.span ℂ
      { opTensor r s |
        (r : QuantumSet.Op X Y xa.1 yb.1)
        (s : QuantumSet.Op A B xa.2 yb.2)
        (_ : r ∈ R.component xa.1 yb.1)
        (_ : s ∈ S.component xa.2 yb.2) }

theorem tensor_mono_left (S : QuantumRel A B) :
    Monotone (fun R : QuantumRel X Y => tensor R S) := by
  intro R₁ R₂ h xa yb
  apply Submodule.span_mono
  rintro _ ⟨r, s, hr, hs, rfl⟩
  exact ⟨r, s, h _ _ hr, hs, rfl⟩

theorem tensor_mono_right (R : QuantumRel X Y) :
    Monotone (fun S : QuantumRel A B => tensor R S) := by
  intro S₁ S₂ h xa yb
  apply Submodule.span_mono
  rintro _ ⟨r, s, hr, hs, rfl⟩
  exact ⟨r, s, hr, h _ _ hs, rfl⟩

@[simp] theorem opTensor_zero_left
    {x : X.Atom} {y : Y.Atom} {a : A.Atom} {b : B.Atom}
    (s : QuantumSet.Op A B a b) :
    opTensor (0 : QuantumSet.Op X Y x y) s = 0 := by
  ext i j
  change Fin (Y.dim y * B.dim b) at i
  change Fin (X.dim x * A.dim a) at j
  change (0 : ℂ) * s (finProdFinEquiv.symm i).2
      (finProdFinEquiv.symm j).2 = 0
  simp

@[simp] theorem opTensor_zero_right
    {x : X.Atom} {y : Y.Atom} {a : A.Atom} {b : B.Atom}
    (r : QuantumSet.Op X Y x y) :
    opTensor r (0 : QuantumSet.Op A B a b) = 0 := by
  ext i j
  change Fin (Y.dim y * B.dim b) at i
  change Fin (X.dim x * A.dim a) at j
  change r (finProdFinEquiv.symm i).1
      (finProdFinEquiv.symm j).1 * (0 : ℂ) = 0
  simp

@[simp] theorem opTensor_add_left
    {x : X.Atom} {y : Y.Atom} {a : A.Atom} {b : B.Atom}
    (r₁ r₂ : QuantumSet.Op X Y x y) (s : QuantumSet.Op A B a b) :
    opTensor (r₁ + r₂) s = opTensor r₁ s + opTensor r₂ s := by
  ext i j
  change Fin (Y.dim y * B.dim b) at i
  change Fin (X.dim x * A.dim a) at j
  change (r₁ _ _ + r₂ _ _) * s _ _ =
    r₁ _ _ * s _ _ + r₂ _ _ * s _ _
  simp [add_mul]

@[simp] theorem opTensor_add_right
    {x : X.Atom} {y : Y.Atom} {a : A.Atom} {b : B.Atom}
    (r : QuantumSet.Op X Y x y) (s₁ s₂ : QuantumSet.Op A B a b) :
    opTensor r (s₁ + s₂) = opTensor r s₁ + opTensor r s₂ := by
  ext i j
  change Fin (Y.dim y * B.dim b) at i
  change Fin (X.dim x * A.dim a) at j
  change r _ _ * (s₁ _ _ + s₂ _ _) =
    r _ _ * s₁ _ _ + r _ _ * s₂ _ _
  simp [mul_add]

@[simp] theorem opTensor_smul_left
    {x : X.Atom} {y : Y.Atom} {a : A.Atom} {b : B.Atom}
    (c : ℂ) (r : QuantumSet.Op X Y x y) (s : QuantumSet.Op A B a b) :
    opTensor (c • r) s = c • opTensor r s := by
  ext i j
  change Fin (Y.dim y * B.dim b) at i
  change Fin (X.dim x * A.dim a) at j
  change (c * r _ _) * s _ _ = c * (r _ _ * s _ _)
  simp [mul_assoc]

@[simp] theorem opTensor_smul_right
    {x : X.Atom} {y : Y.Atom} {a : A.Atom} {b : B.Atom}
    (c : ℂ) (r : QuantumSet.Op X Y x y) (s : QuantumSet.Op A B a b) :
    opTensor r (c • s) = c • opTensor r s := by
  ext i j
  change Fin (Y.dim y * B.dim b) at i
  change Fin (X.dim x * A.dim a) at j
  change r _ _ * (c * s _ _) = c * (r _ _ * s _ _)
  simp [mul_left_comm]

@[simp] theorem opTensor_one
    {x : X.Atom} {a : A.Atom} :
    opTensor (X := X) (Y := X) (A := A) (B := A)
      (1 : QuantumSet.Op X X x x)
      (1 : QuantumSet.Op A A a a) =
      (1 : QuantumSet.Op (X.tensor A) (X.tensor A) (x, a) (x, a)) := by
  unfold opTensor
  rw [Matrix.one_kronecker_one]
  exact Matrix.reindexLinearEquiv_one ℂ ℂ finProdFinEquiv

@[simp] theorem opTensor_mul
    {x : X.Atom} {y : Y.Atom} {z : Z.Atom}
    {a : A.Atom} {b : B.Atom} {c : C.Atom}
    (r₂ : QuantumSet.Op Y Z y z) (r₁ : QuantumSet.Op X Y x y)
    (s₂ : QuantumSet.Op B C b c) (s₁ : QuantumSet.Op A B a b) :
    opTensor (r₂ * r₁) (s₂ * s₁) =
      opTensor r₂ s₂ * opTensor r₁ s₁ := by
  unfold opTensor
  change
    Matrix.reindexLinearEquiv ℂ ℂ finProdFinEquiv finProdFinEquiv
        ((r₂ * r₁) ⊗ₖ (s₂ * s₁)) =
      Matrix.reindexLinearEquiv ℂ ℂ finProdFinEquiv finProdFinEquiv
          (r₂ ⊗ₖ s₂) *
        Matrix.reindexLinearEquiv ℂ ℂ finProdFinEquiv finProdFinEquiv
          (r₁ ⊗ₖ s₁)
  rw [Matrix.reindexLinearEquiv_mul, Matrix.mul_kronecker_mul]

/-- Tensor sends identity relations to the identity relation. -/
theorem tensor_id [DecidableEq X.Atom] [DecidableEq A.Atom] :
    tensor (id X) (id A) = id (X.tensor A) := by
  apply ext
  rintro ⟨x, a⟩ ⟨y, b⟩
  by_cases hxy : x = y
  · subst y
    by_cases hab : a = b
    · subst b
      rw [id_component_eq]
      apply le_antisymm
      · apply Submodule.span_le.mpr
        rintro _ ⟨r, s, hr, hs, rfl⟩
        have hr' : r ∈ Submodule.span ℂ
            {(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ)} := by
          simpa [id] using hr
        have hs' : s ∈ Submodule.span ℂ
            {(1 : Matrix (Fin (A.dim a)) (Fin (A.dim a)) ℂ)} := by
          simpa [id] using hs
        obtain ⟨cr, rfl⟩ := Submodule.mem_span_singleton.mp hr'
        obtain ⟨cs, rfl⟩ := Submodule.mem_span_singleton.mp hs'
        rw [opTensor_smul_left, opTensor_smul_right, opTensor_one]
        rw [smul_smul]
        apply Submodule.smul_mem
        exact Submodule.subset_span (Set.mem_singleton _)
      · apply Submodule.span_le.mpr
        rintro _ rfl
        refine Submodule.subset_span
          ⟨(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ),
            (1 : Matrix (Fin (A.dim a)) (Fin (A.dim a)) ℂ), ?_, ?_, opTensor_one⟩
        · simp [id]
        · simp [id]
    · have hp : (x, a) ≠ (x, b) := fun h => hab (Prod.mk.inj h).2
      rw [show (id (X.tensor A)).component (x, a) (x, b) = ⊥ from
        id_component_ne hp]
      apply le_bot_iff.mp
      apply Submodule.span_le.mpr
      rintro _ ⟨r, s, hr, hs, rfl⟩
      have hs0 : s = 0 := by
        have : s ∈ (⊥ : OpSpace A A a b) := by
          simpa [id, hab] using hs
        simpa [Submodule.mem_bot] using this
      subst s
      simp
  · have hp : (x, a) ≠ (y, b) := fun h => hxy (Prod.mk.inj h).1
    rw [show (id (X.tensor A)).component (x, a) (y, b) = ⊥ from
      id_component_ne hp]
    apply le_bot_iff.mp
    apply Submodule.span_le.mpr
    rintro _ ⟨r, s, hr, hs, rfl⟩
    have hr0 : r = 0 := by
      have : r ∈ (⊥ : OpSpace X X x y) := by
        simpa [id, hxy] using hr
      simpa [Submodule.mem_bot] using this
    subst r
    simp

/-- Tensor is compatible with relational composition. -/
theorem tensor_comp
    (R₂ : QuantumRel Y Z) (R₁ : QuantumRel X Y)
    (S₂ : QuantumRel B C) (S₁ : QuantumRel A B) :
    tensor (R₂.comp R₁) (S₂.comp S₁) =
      (tensor R₂ S₂).comp (tensor R₁ S₁) := by
  apply ext
  rintro ⟨x, a⟩ ⟨z, c⟩
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨u, v, hu, hv, rfl⟩
    have hu' :
        u ∈ Submodule.span ℂ
          (⋃ y, (R₂.compThrough R₁ x y z : Set _)) := by
      simpa [comp, Submodule.iSup_eq_span] using hu
    have hv' :
        v ∈ Submodule.span ℂ
          (⋃ b, (S₂.compThrough S₁ a b c : Set _)) := by
      simpa [comp, Submodule.iSup_eq_span] using hv
    refine Submodule.span_induction₂
      (p := fun u v _ _ =>
        opTensor u v ∈
          ((tensor R₂ S₂).comp (tensor R₁ S₁)).component (x, a) (z, c))
      ?_
      (fun v _ => by rw [opTensor_zero_left]; exact zero_mem _)
      (fun u _ => by rw [opTensor_zero_right]; exact zero_mem _)
      (fun u₁ u₂ v _ _ _ h₁ h₂ => by
        rw [opTensor_add_left]
        exact add_mem h₁ h₂)
      (fun u v₁ v₂ _ _ _ h₁ h₂ => by
        rw [opTensor_add_right]
        exact add_mem h₁ h₂)
      (fun d u v _ _ h => by
        rw [opTensor_smul_left]
        exact Submodule.smul_mem _ d h)
      (fun d u v _ _ h => by
        rw [opTensor_smul_right]
        exact Submodule.smul_mem _ d h)
      hu' hv'
    intro u v hu0 hv0
    obtain ⟨y, huy⟩ := Set.mem_iUnion.mp hu0
    obtain ⟨b, hvb⟩ := Set.mem_iUnion.mp hv0
    refine Submodule.span_induction₂
      (p := fun u v _ _ =>
        opTensor u v ∈
          ((tensor R₂ S₂).comp (tensor R₁ S₁)).component (x, a) (z, c))
      ?_
      (fun v _ => by rw [opTensor_zero_left]; exact zero_mem _)
      (fun u _ => by rw [opTensor_zero_right]; exact zero_mem _)
      (fun u₁ u₂ v _ _ _ h₁ h₂ => by
        rw [opTensor_add_left]
        exact add_mem h₁ h₂)
      (fun u v₁ v₂ _ _ _ h₁ h₂ => by
        rw [opTensor_add_right]
        exact add_mem h₁ h₂)
      (fun d u v _ _ h => by
        rw [opTensor_smul_left]
        exact Submodule.smul_mem _ d h)
      (fun d u v _ _ h => by
        rw [opTensor_smul_right]
        exact Submodule.smul_mem _ d h)
      huy hvb
    rintro _ _ ⟨r₁, r₂, hr₁, hr₂, rfl⟩
      ⟨s₁, s₂, hs₁, hs₂, rfl⟩
    rw [opTensor_mul]
    apply (le_iSup
      (fun yb => (tensor R₂ S₂).compThrough (tensor R₁ S₁)
        (x, a) yb (z, c)) (y, b))
    refine Submodule.subset_span ⟨opTensor r₁ s₁, opTensor r₂ s₂, ?_, ?_, rfl⟩
    · exact Submodule.subset_span ⟨r₁, s₁, hr₁, hs₁, rfl⟩
    · exact Submodule.subset_span ⟨r₂, s₂, hr₂, hs₂, rfl⟩
  · apply iSup_le
    rintro ⟨y, b⟩
    apply Submodule.span_le.mpr
    rintro _ ⟨r, s, hr, hs, rfl⟩
    refine Submodule.span_induction₂
      (p := fun s r _ _ =>
        s * r ∈
          (tensor (R₂.comp R₁) (S₂.comp S₁)).component (x, a) (z, c))
      ?_
      (fun r _ => by rw [Matrix.zero_mul]; exact zero_mem _)
      (fun s _ => by rw [Matrix.mul_zero]; exact zero_mem _)
      (fun s₁ s₂ r _ _ _ h₁ h₂ => by
        rw [Matrix.add_mul]
        exact add_mem h₁ h₂)
      (fun s r₁ r₂ _ _ _ h₁ h₂ => by
        rw [Matrix.mul_add]
        exact add_mem h₁ h₂)
      (fun d s r _ _ h => by
        rw [Matrix.smul_mul]
        exact Submodule.smul_mem _ d h)
      (fun d s r _ _ h => by
        rw [Matrix.mul_smul]
        exact Submodule.smul_mem _ d h)
      hs hr
    rintro _ _ ⟨r₂, s₂, hr₂, hs₂, rfl⟩
      ⟨r₁, s₁, hr₁, hs₁, rfl⟩
    rw [← opTensor_mul]
    refine Submodule.subset_span ⟨r₂ * r₁, s₂ * s₁, ?_, ?_, rfl⟩
    · apply (le_iSup (fun y => R₂.compThrough R₁ x y z) y)
      exact Submodule.subset_span ⟨r₁, r₂, hr₁, hr₂, rfl⟩
    · apply (le_iSup (fun b => S₂.compThrough S₁ a b c) b)
      exact Submodule.subset_span ⟨s₁, s₂, hs₁, hs₂, rfl⟩

/-- Identity matrix transported across an equality of dimensions. -/
def transportMatrix {m n : ℕ} (h : m = n) :
    Matrix (Fin n) (Fin m) ℂ := by
  subst n
  exact 1

@[simp] theorem transportMatrix_rfl (n : ℕ) :
    transportMatrix (rfl : n = n) = (1 : Matrix (Fin n) (Fin n) ℂ) :=
  rfl

theorem transportMatrix_symm_mul {m n : ℕ} (h : m = n) :
    transportMatrix h.symm * transportMatrix h =
      (1 : Matrix (Fin m) (Fin m) ℂ) := by
  subst n
  simp

theorem transportMatrix_mul_symm {m n : ℕ} (h : m = n) :
    transportMatrix h * transportMatrix h.symm =
      (1 : Matrix (Fin n) (Fin n) ℂ) := by
  subst n
  simp

/-- Relation implementing an atom equivalence whose dimensions agree. -/
noncomputable def reindexRel (e : X.Atom ≃ Y.Atom)
    [DecidableEq Y.Atom]
    (hdim : ∀ x, X.dim x = Y.dim (e x)) : QuantumRel X Y where
  component x y :=
    if h : y = e x then
      h ▸ Submodule.span ℂ {transportMatrix (hdim x)}
    else
      ⊥

@[simp] theorem reindexRel_component_eq
    (e : X.Atom ≃ Y.Atom) [DecidableEq Y.Atom]
    (hdim : ∀ x, X.dim x = Y.dim (e x))
    (x : X.Atom) :
    (reindexRel e hdim).component x (e x) =
      Submodule.span ℂ {transportMatrix (hdim x)} := by
  simp [reindexRel]

@[simp] theorem reindexRel_component_ne
    (e : X.Atom ≃ Y.Atom) [DecidableEq Y.Atom]
    (hdim : ∀ x, X.dim x = Y.dim (e x))
    {x : X.Atom} {y : Y.Atom} (h : y ≠ e x) :
    (reindexRel e hdim).component x y = ⊥ := by
  simp [reindexRel, h]

/-- Inverse relation, using the same forward atom equation as `reindexRel`. -/
noncomputable def reindexRelInv (e : X.Atom ≃ Y.Atom)
    [DecidableEq Y.Atom]
    (hdim : ∀ x, X.dim x = Y.dim (e x)) : QuantumRel Y X where
  component y x :=
    if h : y = e x then
      h ▸ Submodule.span ℂ {transportMatrix (hdim x).symm}
    else
      ⊥

@[simp] theorem reindexRelInv_component_eq
    (e : X.Atom ≃ Y.Atom) [DecidableEq Y.Atom]
    (hdim : ∀ x, X.dim x = Y.dim (e x)) (x : X.Atom) :
    (reindexRelInv e hdim).component (e x) x =
      Submodule.span ℂ {transportMatrix (hdim x).symm} := by
  simp [reindexRelInv]

/-- The inverse reindexing relation composes to the identity. -/
theorem reindexRel_inverse_comp [DecidableEq X.Atom] [DecidableEq Y.Atom]
    (e : X.Atom ≃ Y.Atom) (hdim : ∀ x, X.dim x = Y.dim (e x)) :
    (reindexRelInv e hdim).comp (reindexRel e hdim) = id X := by
  apply ext
  intro x z
  by_cases hxz : x = z
  · subst z
    rw [id_component_eq]
    apply le_antisymm
    · apply iSup_le
      intro y
      by_cases hy : y = e x
      · subst y
        apply Submodule.span_le.mpr
        rintro _ ⟨r, s, hr, hs, rfl⟩
        have hr' : r ∈ Submodule.span ℂ {transportMatrix (hdim x)} := by
          simpa using hr
        have hs' : s ∈ Submodule.span ℂ
            {transportMatrix (hdim x).symm} := by
          simpa using hs
        obtain ⟨cr, rfl⟩ := Submodule.mem_span_singleton.mp hr'
        obtain ⟨cs, rfl⟩ := Submodule.mem_span_singleton.mp hs'
        rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul]
        have hInv :
            transportMatrix (hdim x).symm *
                transportMatrix (hdim x) =
              (1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ) := by
          exact transportMatrix_symm_mul (hdim x)
        rw [hInv]
        exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))
      · apply Submodule.span_le.mpr
        rintro _ ⟨r, s, hr, hs, rfl⟩
        have hr0 : r = 0 := by
          have : r ∈ (⊥ : OpSpace X Y x y) := by
            simpa [reindexRel, hy] using hr
          simpa [Submodule.mem_bot] using this
        subst r
        simp
    · refine le_trans ?_
        (le_iSup (fun y =>
          (reindexRelInv e hdim).compThrough
            (reindexRel e hdim) x y x) (e x))
      apply Submodule.span_le.mpr
      rintro _ rfl
      refine Submodule.subset_span
        ⟨transportMatrix (hdim x),
          transportMatrix (hdim x).symm, ?_, ?_, ?_⟩
      · simp
      · simp
      · exact transportMatrix_symm_mul (hdim x)
  · rw [id_component_ne hxz]
    apply le_bot_iff.mp
    apply iSup_le
    intro y
    apply Submodule.span_le.mpr
    rintro _ ⟨r, s, hr, hs, rfl⟩
    by_cases hy : y = e x
    · subst y
      have hs0 : s = 0 := by
        have : s ∈ (⊥ : OpSpace Y X (e x) z) := by
          simpa [reindexRelInv, hxz, e.injective.eq_iff] using hs
        simpa [Submodule.mem_bot] using this
      subst s
      simp
    · have hr0 : r = 0 := by
        have : r ∈ (⊥ : OpSpace X Y x y) := by
          simpa [reindexRel, hy] using hr
        simpa [Submodule.mem_bot] using this
      subst r
      simp

/-- The forward reindexing relation also composes with its inverse to identity. -/
theorem reindexRel_comp_inverse [DecidableEq X.Atom] [DecidableEq Y.Atom]
    (e : X.Atom ≃ Y.Atom) (hdim : ∀ x, X.dim x = Y.dim (e x)) :
    (reindexRel e hdim).comp
        (reindexRelInv e hdim) = id Y := by
  apply ext
  intro y w
  by_cases hyw : y = w
  · subst w
    obtain ⟨x₀, rfl⟩ := e.surjective y
    rw [id_component_eq]
    apply le_antisymm
    · apply iSup_le
      intro x
      by_cases hy : x₀ = x
      · subst x
        apply Submodule.span_le.mpr
        rintro _ ⟨r, s, hr, hs, rfl⟩
        have hr' : r ∈ Submodule.span ℂ {transportMatrix (hdim x₀).symm} := by
          simpa using hr
        have hs' : s ∈ Submodule.span ℂ {transportMatrix (hdim x₀)} := by
          simpa using hs
        obtain ⟨cr, rfl⟩ := Submodule.mem_span_singleton.mp hr'
        obtain ⟨cs, rfl⟩ := Submodule.mem_span_singleton.mp hs'
        rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul,
          transportMatrix_mul_symm]
        exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))
      · apply Submodule.span_le.mpr
        rintro _ ⟨r, s, hr, hs, rfl⟩
        have hr0 : r = 0 := by
          have : r ∈ (⊥ : OpSpace Y X (e x₀) x) := by
            simpa [reindexRelInv, hy, e.injective.eq_iff] using hr
          simpa [Submodule.mem_bot] using this
        subst r
        simp
    ·
      refine le_trans ?_
        (le_iSup (fun x =>
          (reindexRel e hdim).compThrough
            (reindexRelInv e hdim) (e x₀) x (e x₀)) x₀)
      apply Submodule.span_le.mpr
      rintro _ rfl
      refine Submodule.subset_span
        ⟨transportMatrix (hdim x₀).symm, transportMatrix (hdim x₀), ?_, ?_, ?_⟩
      · simp
      · simp
      · exact transportMatrix_mul_symm (hdim x₀)
  · rw [id_component_ne hyw]
    apply le_bot_iff.mp
    apply iSup_le
    intro x
    apply Submodule.span_le.mpr
    rintro _ ⟨r, s, hr, hs, rfl⟩
    by_cases hy : y = e x
    · subst y
      have hs0 : s = 0 := by
        have : s ∈ (⊥ : OpSpace X Y x w) := by
          simpa [reindexRel, Ne.symm hyw] using hs
        simpa [Submodule.mem_bot] using this
      subst s
      simp
    · have hr0 : r = 0 := by
        have : r ∈ (⊥ : OpSpace Y X y x) := by
          simpa [reindexRelInv, hy] using hr
        simpa [Submodule.mem_bot] using this
      subst r
      simp

/-- Reshape an operator `X ⊗ A → B` as an operator `X → A* ⊗ B`. -/
noncomputable def curryOpEquiv (nx na nb : ℕ) :
    Matrix (Fin nb) (Fin (nx * na)) ℂ ≃ₗ[ℂ]
      Matrix (Fin (na * nb)) (Fin nx) ℂ where
  toFun f i x :=
    f (finProdFinEquiv.symm i).2
      (finProdFinEquiv (x, (finProdFinEquiv.symm i).1))
  invFun g b xa :=
    g (finProdFinEquiv ((finProdFinEquiv.symm xa).2, b))
      (finProdFinEquiv.symm xa).1
  left_inv f := by
    ext b xa
    generalize hx : finProdFinEquiv.symm xa = p
    rcases p with ⟨x, a⟩
    have hxa : xa = finProdFinEquiv (x, a) := by
      rw [← hx]
      exact (Equiv.apply_symm_apply finProdFinEquiv xa).symm
    subst xa
    simp
  right_inv g := by
    ext i x
    generalize hi : finProdFinEquiv.symm i = p
    rcases p with ⟨a, b⟩
    have hi' : i = finProdFinEquiv (a, b) := by
      rw [← hi]
      exact (Equiv.apply_symm_apply finProdFinEquiv i).symm
    subst i
    simp
  map_add' f g := by
    ext i x
    rfl
  map_smul' c f := by
    ext i x
    rfl

/-- Compact-closed internal hom `A* ⊗ B`. -/
abbrev internalHom (A B : QuantumSet) : QuantumSet :=
  A.dual.tensor B

/-- Relational currying, implemented by the canonical matrix reshaping. -/
noncomputable def curry (R : QuantumRel (X.tensor A) B) :
    QuantumRel X (internalHom A B) where
  component x ab :=
    Submodule.map
      (curryOpEquiv (X.dim x) (A.dim ab.1) (B.dim ab.2)).toLinearMap
      (R.component (x, ab.1) ab.2)

/-- Inverse matrix reshaping for relational uncurrying. -/
noncomputable def uncurry (R : QuantumRel X (internalHom A B)) :
    QuantumRel (X.tensor A) B where
  component xa b :=
    Submodule.map
      (curryOpEquiv (X.dim xa.1) (A.dim xa.2) (B.dim b)).symm.toLinearMap
      (R.component xa.1 (xa.2, b))

theorem curry_mono : Monotone
    (curry : QuantumRel (X.tensor A) B → QuantumRel X (internalHom A B)) := by
  intro R S h x ab
  exact Submodule.map_mono (h (x, ab.1) ab.2)

theorem uncurry_mono : Monotone
    (uncurry : QuantumRel X (internalHom A B) → QuantumRel (X.tensor A) B) := by
  intro R S h xa b
  exact Submodule.map_mono (h xa.1 (xa.2, b))

theorem curry_uncurry (R : QuantumRel X (internalHom A B)) :
    curry (uncurry R) = R := by
  apply ext
  rintro x ⟨a, b⟩
  simp only [curry, uncurry]
  exact (Submodule.map_symm_eq_iff
    (curryOpEquiv (X.dim x) (A.dim a) (B.dim b))).mp rfl

theorem uncurry_curry (R : QuantumRel (X.tensor A) B) :
    uncurry (curry R) = R := by
  apply ext
  rintro ⟨x, a⟩ b
  simp only [uncurry, curry]
  exact (Submodule.map_symm_eq_iff
    (curryOpEquiv (X.dim x) (A.dim a) (B.dim b))).mpr rfl

theorem curry_iSup (R : ℕ → QuantumRel (X.tensor A) B) :
    curry (⨆ n, R n) = ⨆ n, curry (R n) := by
  apply ext
  rintro x ⟨a, b⟩
  change
    Submodule.map
        (curryOpEquiv (X.dim x) (A.dim a) (B.dim b)).toLinearMap
        ((⨆ n, R n).component (x, a) b) =
      (⨆ n, curry (R n)).component x (a, b)
  rw [show ((⨆ n, R n).component (x, a) b) =
      ⨆ n, (R n).component (x, a) b from
    iSup_component R (x, a) b]
  rw [show ((⨆ n, curry (R n)).component x (a, b)) =
      ⨆ n, (curry (R n)).component x (a, b) from
    iSup_component (fun n => curry (R n)) x (a, b)]
  change
    Submodule.map
        (curryOpEquiv (X.dim x) (A.dim a) (B.dim b)).toLinearMap
        (⨆ n, (R n).component (x, a) b) =
      ⨆ n, Submodule.map
        (curryOpEquiv (X.dim x) (A.dim a) (B.dim b)).toLinearMap
        ((R n).component (x, a) b)
  exact Submodule.map_iSup
    (curryOpEquiv (X.dim x) (A.dim a) (B.dim b)).toLinearMap
    (fun n => (R n).component (x, a) b)

theorem uncurry_iSup (R : ℕ → QuantumRel X (internalHom A B)) :
    uncurry (⨆ n, R n) = ⨆ n, uncurry (R n) := by
  apply ext
  rintro ⟨x, a⟩ b
  change
    Submodule.map
        (curryOpEquiv (X.dim x) (A.dim a) (B.dim b)).symm.toLinearMap
        ((⨆ n, R n).component x (a, b)) =
      (⨆ n, uncurry (R n)).component (x, a) b
  rw [show ((⨆ n, R n).component x (a, b)) =
      ⨆ n, (R n).component x (a, b) from
    iSup_component R x (a, b)]
  rw [show ((⨆ n, uncurry (R n)).component (x, a) b) =
      ⨆ n, (uncurry (R n)).component (x, a) b from
    iSup_component (fun n => uncurry (R n)) (x, a) b]
  change
    Submodule.map
        (curryOpEquiv (X.dim x) (A.dim a) (B.dim b)).symm.toLinearMap
        (⨆ n, (R n).component x (a, b)) =
      ⨆ n, Submodule.map
        (curryOpEquiv (X.dim x) (A.dim a) (B.dim b)).symm.toLinearMap
        ((R n).component x (a, b))
  exact Submodule.map_iSup
    (curryOpEquiv (X.dim x) (A.dim a) (B.dim b)).symm.toLinearMap
    (fun n => (R n).component x (a, b))

/-- Evaluation induced by compact-closed uncurrying. -/
noncomputable def eval (A B : QuantumSet)
    [DecidableEq (internalHom A B).Atom] :
    QuantumRel ((internalHom A B).tensor A) B :=
  uncurry (id (internalHom A B))

end QuantumRel

namespace QObj

/-- Compact-closed internal hom on packaged quantum sets. -/
def internalHom (A B : QObj) : QObj where
  set := QuantumRel.internalHom A.set B.set
  decidable :=
    inferInstanceAs (DecidableEq (A.set.Atom × B.set.Atom))

end QObj

/-- Turn a dimension-preserving atom equivalence into an isomorphism in `qRel`. -/
noncomputable def qRelIsoOfEquiv (X Y : QObj)
    (e : X.set.Atom ≃ Y.set.Atom)
    (hdim : ∀ x, X.set.dim x = Y.set.dim (e x)) :
    qRelCategory.Iso X Y where
  hom := QuantumRel.reindexRel e hdim
  inv := QuantumRel.reindexRelInv e hdim
  hom_inv := QuantumRel.reindexRel_comp_inverse e hdim
  inv_hom := QuantumRel.reindexRel_inverse_comp e hdim

/-- Left unitor relation `I ⊗ X ≅ X`. -/
noncomputable def qRelLeftUnitor (X : QObj) :
    qRelCategory.Iso (QObj.tensor QObj.unit X) X :=
  qRelIsoOfEquiv _ _
    (Equiv.punitProd X.set.Atom)
    (fun p => by
      rcases p with ⟨u, x⟩
      cases u
      exact Nat.one_mul (X.set.dim x))

/-- Right unitor relation `X ⊗ I ≅ X`. -/
noncomputable def qRelRightUnitor (X : QObj) :
    qRelCategory.Iso (QObj.tensor X QObj.unit) X :=
  qRelIsoOfEquiv _ _
    (Equiv.prodPUnit X.set.Atom)
    (fun p => by
      rcases p with ⟨x, u⟩
      cases u
      exact Nat.mul_one (X.set.dim x))

/-- Associator relation `(X ⊗ Y) ⊗ Z ≅ X ⊗ (Y ⊗ Z)`. -/
noncomputable def qRelAssociator (X Y Z : QObj) :
    qRelCategory.Iso
      (QObj.tensor (QObj.tensor X Y) Z)
      (QObj.tensor X (QObj.tensor Y Z)) :=
  qRelIsoOfEquiv _ _
    (Equiv.prodAssoc X.set.Atom Y.set.Atom Z.set.Atom)
    (fun p => by
      rcases p with ⟨⟨x, y⟩, z⟩
      exact Nat.mul_assoc (X.set.dim x) (Y.set.dim y) (Z.set.dim z))

/-- Braiding relation `X ⊗ Y ≅ Y ⊗ X`. -/
noncomputable def qRelBraiding (X Y : QObj) :
    qRelCategory.Iso (QObj.tensor X Y) (QObj.tensor Y X) :=
  qRelIsoOfEquiv _ _
    (Equiv.prodComm X.set.Atom Y.set.Atom)
    (fun p => by
      rcases p with ⟨x, y⟩
      exact Nat.mul_comm (X.set.dim x) (Y.set.dim y))

/-- The symmetric monoidal closed structure on quantum relations. -/
noncomputable def qRelSymmetricMonoidalClosed :
    SymmetricMonoidalClosed qRelCategory where
  unit := QObj.unit
  tensor := QObj.tensor
  internalHom := QObj.internalHom
  tensorMap := QuantumRel.tensor
  tensorMap_mono_left := by
    intro A B C D g
    exact QuantumRel.tensor_mono_left g
  tensorMap_mono_right := by
    intro A B C D f
    exact QuantumRel.tensor_mono_right f
  tensorMap_id := by
    intro A B
    let _ := A.decidable
    let _ := B.decidable
    exact QuantumRel.tensor_id
  tensorMap_comp := by
    intro A B C D E F f₂ f₁ g₂ g₁
    exact QuantumRel.tensor_comp f₂ f₁ g₂ g₁
  leftUnitor := qRelLeftUnitor
  rightUnitor := qRelRightUnitor
  associator := qRelAssociator
  braiding := qRelBraiding
  eval := fun {A B} => by
    letI := A.decidable
    letI := B.decidable
    letI : DecidableEq (QuantumRel.internalHom A.set B.set).Atom :=
      inferInstanceAs (DecidableEq (A.set.Atom × B.set.Atom))
    exact QuantumRel.eval _ _
  curry := QuantumRel.curry
  uncurry := QuantumRel.uncurry
  curry_uncurry := QuantumRel.curry_uncurry
  uncurry_curry := QuantumRel.uncurry_curry
  curry_mono := by
    intro X A B
    exact QuantumRel.curry_mono
  curry_ωSup := by
    intro X A B c hc
    change QuantumRel.curry (⨆ n, c n) =
      ⨆ n, QuantumRel.curry (c n)
    exact QuantumRel.curry_iSup c

end QLambda.Domain
