/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.Order.CompleteLattice.Basic
import QLambda.Domain.QuantumSet

/-!
# Quantum relations

A quantum binary relation from `X` to `Y` is a matrix of operator
subspaces `R(x,y) ⊆ L(X_x, Y_y)`, after Weaver and Kornell.  Composition
is the subspace generated by operator products, summed over intermediate
atoms.  The identity has `ℂ · 1` on the diagonal and zero off it.

See arXiv:2109.02196, §2, and Weaver, *Quantum relations*.
-/

open Matrix

namespace QLambda.Domain

/-- Operator space from atom `x` of `X` to atom `y` of `Y`. -/
abbrev OpSpace (X Y : QuantumSet) (x : X.Atom) (y : Y.Atom) : Type :=
  Submodule ℂ (QuantumSet.Op X Y x y)

/-- A quantum binary relation: one operator subspace per pair of atoms. -/
structure QuantumRel (X Y : QuantumSet) where
  component : ∀ (x : X.Atom) (y : Y.Atom), OpSpace X Y x y

namespace QuantumRel

variable {X Y Z W : QuantumSet}

/-- Pointwise inclusion of quantum relations. -/
instance : LE (QuantumRel X Y) where
  le R S := ∀ x y, R.component x y ≤ S.component x y

instance : PartialOrder (QuantumRel X Y) where
  le_refl _ _ _ := le_rfl
  le_trans _ _ _ hRS hST x y := (hRS x y).trans (hST x y)
  le_antisymm R S hRS hSR := by
    cases R
    cases S
    congr 1
    funext x y
    exact le_antisymm (hRS x y) (hSR x y)

/-- The zero relation. -/
def bot : QuantumRel X Y where
  component := fun _ _ => ⊥

/-- The top relation: every operator is allowed. -/
def top : QuantumRel X Y where
  component := fun _ _ => ⊤

instance : Bot (QuantumRel X Y) := ⟨bot⟩
instance : Top (QuantumRel X Y) := ⟨top⟩

instance : InfSet (QuantumRel X Y) where
  sInf s := ⟨fun x y => ⨅ R : s, R.1.component x y⟩

instance : SupSet (QuantumRel X Y) where
  sSup s := ⟨fun x y => ⨆ R : s, R.1.component x y⟩

instance : SemilatticeInf (QuantumRel X Y) where
  inf R S := ⟨fun x y => R.component x y ⊓ S.component x y⟩
  inf_le_left := fun _ _ _ _ => inf_le_left
  inf_le_right := fun _ _ _ _ => inf_le_right
  le_inf := fun _ _ _ hR hS x y => le_inf (hR x y) (hS x y)

instance : SemilatticeSup (QuantumRel X Y) where
  sup R S := ⟨fun x y => R.component x y ⊔ S.component x y⟩
  le_sup_left := fun _ _ _ _ => le_sup_left
  le_sup_right := fun _ _ _ _ => le_sup_right
  sup_le := fun _ _ _ hR hS x y => sup_le (hR x y) (hS x y)

instance : Lattice (QuantumRel X Y) where

instance : BoundedOrder (QuantumRel X Y) where
  le_top := fun _ _ _ => le_top
  bot_le := fun _ _ _ => bot_le

theorem isLUB_sSup (s : Set (QuantumRel X Y)) :
    IsLUB s (sSup s) := by
  constructor
  · intro R hR x y
    exact le_iSup_of_le ⟨R, hR⟩ le_rfl
  · intro R hR x y
    apply iSup_le
    intro S
    exact (hR S.property) x y

theorem isGLB_sInf (s : Set (QuantumRel X Y)) :
    IsGLB s (sInf s) := by
  constructor
  · intro R hR x y
    exact iInf_le_of_le ⟨R, hR⟩ le_rfl
  · intro R hR x y
    apply le_iInf
    intro S
    exact (hR S.property) x y

noncomputable instance : CompleteLattice (QuantumRel X Y) where
  isLUB_sSup := isLUB_sSup
  isGLB_sInf := isGLB_sInf

/-- Identity relation: scalar multiples of `1` on matching atoms. -/
def id (X : QuantumSet) [DecidableEq X.Atom] : QuantumRel X X where
  component x y :=
    if h : x = y then
      h ▸ Submodule.span ℂ
        {(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ)}
    else
      ⊥

/-- Finite products of operators through one intermediate atom. -/
def compThrough (S : QuantumRel Y Z) (R : QuantumRel X Y)
    (x : X.Atom) (y : Y.Atom) (z : Z.Atom) : OpSpace X Z x z :=
  Submodule.span ℂ
    { (s * r : QuantumSet.Op X Z x z) |
      (r : QuantumSet.Op X Y x y)
      (s : QuantumSet.Op Y Z y z)
      (_ : r ∈ R.component x y)
      (_ : s ∈ S.component y z) }

/-- Relational composition as the join of all intermediate atoms. -/
def comp (S : QuantumRel Y Z) (R : QuantumRel X Y) : QuantumRel X Z where
  component x z := ⨆ y, S.compThrough R x y z

/-- The dagger / converse relation. -/
def dagger (R : QuantumRel X Y) : QuantumRel Y X where
  component y x :=
    Submodule.span ℂ
      { (rᴴ : QuantumSet.Op Y X y x) |
        (r : QuantumSet.Op X Y x y) (_ : r ∈ R.component x y) }

/-- A function is a relation satisfying the ordinary graph equations
`F ∘ F† ≤ I` and `F† ∘ F ≥ I`. -/
def IsFunction [DecidableEq X.Atom] [DecidableEq Y.Atom]
    (F : QuantumRel X Y) : Prop :=
  (F.comp F.dagger) ≤ id Y ∧ id X ≤ (F.dagger.comp F)

theorem ext {R S : QuantumRel X Y}
    (h : ∀ x y, R.component x y = S.component x y) : R = S := by
  cases R
  cases S
  congr 1
  funext x y
  exact h x y

theorem le_def {R S : QuantumRel X Y} :
    R ≤ S ↔ ∀ x y, R.component x y ≤ S.component x y :=
  Iff.rfl

@[simp] theorem id_component_eq [DecidableEq X.Atom] (x : X.Atom) :
    (id X).component x x =
      Submodule.span ℂ
        {(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ)} := by
  simp [id]

@[simp] theorem id_component_ne [DecidableEq X.Atom] {x y : X.Atom}
    (hxy : x ≠ y) :
    (id X).component x y = ⊥ := by
  simp [id, hxy]

theorem comp_mono_left {S₁ S₂ : QuantumRel Y Z} (R : QuantumRel X Y)
    (h : S₁ ≤ S₂) :
    S₁.comp R ≤ S₂.comp R := by
  intro x z
  refine iSup_mono ?_
  intro y
  apply Submodule.span_mono
  rintro _ ⟨r, s, hr, hs, rfl⟩
  exact ⟨r, s, hr, h y z hs, rfl⟩

theorem comp_mono_right {S : QuantumRel Y Z} {R₁ R₂ : QuantumRel X Y}
    (h : R₁ ≤ R₂) :
    S.comp R₁ ≤ S.comp R₂ := by
  intro x z
  refine iSup_mono ?_
  intro y
  apply Submodule.span_mono
  rintro _ ⟨r, s, hr, hs, rfl⟩
  exact ⟨r, s, h x y hr, hs, rfl⟩

theorem comp_mono {S₁ S₂ : QuantumRel Y Z} {R₁ R₂ : QuantumRel X Y}
    (hS : S₁ ≤ S₂) (hR : R₁ ≤ R₂) :
    S₁.comp R₁ ≤ S₂.comp R₂ :=
  (comp_mono_left R₁ hS).trans (comp_mono_right hR)

theorem dagger_mono {R S : QuantumRel X Y} (h : R ≤ S) :
    R.dagger ≤ S.dagger := by
  intro y x
  apply Submodule.span_mono
  rintro _ ⟨r, hr, rfl⟩
  exact ⟨r, h x y hr, rfl⟩

theorem mem_dagger {R : QuantumRel X Y} {x : X.Atom} {y : Y.Atom}
    {r : QuantumSet.Op X Y x y} (hr : r ∈ R.component x y) :
    rᴴ ∈ R.dagger.component y x :=
  Submodule.subset_span ⟨r, hr, rfl⟩

@[simp] theorem dagger_dagger (R : QuantumRel X Y) :
    R.dagger.dagger = R := by
  apply ext
  intro x y
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨s, hs, rfl⟩
    change sᴴ ∈ R.component x y
    refine Submodule.span_induction
      (p := fun t _ => tᴴ ∈ R.component x y)
      (fun _ ht => by
        obtain ⟨r, hr, rfl⟩ := ht
        simpa using hr)
      (by simp)
      (fun a b _ _ ha hb => by
        rw [Matrix.conjTranspose_add]
        exact add_mem ha hb)
      (fun c a _ ha => by
        rw [Matrix.conjTranspose_smul]
        exact Submodule.smul_mem _ (star c) ha)
      hs
  · intro r hr
    simpa using (mem_dagger (mem_dagger hr))

theorem adjoint_mem_span {n m : ℕ}
    {s : Set (Matrix (Fin m) (Fin n) ℂ)}
    {a : Matrix (Fin m) (Fin n) ℂ}
    (ha : a ∈ Submodule.span ℂ s) :
    aᴴ ∈ Submodule.span ℂ { bᴴ | b ∈ s } := by
  refine Submodule.span_induction
    (p := fun x _ => xᴴ ∈ Submodule.span ℂ { bᴴ | b ∈ s })
    (fun b hb => Submodule.subset_span ⟨b, hb, rfl⟩)
    (by simp [conjTranspose_zero])
    (fun x y _ _ hx hy => by
      rw [conjTranspose_add]
      exact add_mem hx hy)
    (fun c x _ hx => by
      rw [Matrix.conjTranspose_smul]
      exact Submodule.smul_mem _ (star c) hx)
    ha

theorem dagger_compThrough (S : QuantumRel Y Z) (R : QuantumRel X Y)
    (x : X.Atom) (y : Y.Atom) (z : Z.Atom) :
    Submodule.span ℂ { vᴴ | v ∈ S.compThrough R x y z } ≤
      R.dagger.compThrough S.dagger z y x := by
  apply Submodule.span_le.mpr
  rintro _ ⟨v, hv, rfl⟩
  have hvadj := adjoint_mem_span (s :=
      { (s * r : QuantumSet.Op X Z x z) |
        (r : QuantumSet.Op X Y x y)
        (s : QuantumSet.Op Y Z y z)
        (_ : r ∈ R.component x y)
        (_ : s ∈ S.component y z) }) hv
  refine (Submodule.span_le.mpr ?_) hvadj
  rintro _ ⟨w, hw, rfl⟩
  obtain ⟨r, s, hr, hs, rfl⟩ := hw
  refine Submodule.subset_span ⟨sᴴ, rᴴ, mem_dagger hs, mem_dagger hr, ?_⟩
  exact (Matrix.conjTranspose_mul s r).symm

theorem dagger_comp (S : QuantumRel Y Z) (R : QuantumRel X Y) :
    (S.comp R).dagger = R.dagger.comp S.dagger := by
  apply ext
  intro z x
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨u, hu, rfl⟩
    have hu' :
        u ∈ Submodule.span ℂ
          (⋃ y, (S.compThrough R x y z : Set _)) := by
      simpa [comp, Submodule.iSup_eq_span] using hu
    have hspan := adjoint_mem_span hu'
    refine (Submodule.span_le.mpr ?_) hspan
    rintro _ ⟨v, hv, rfl⟩
    obtain ⟨y, hv'⟩ := Set.mem_iUnion.mp hv
    apply (le_iSup (fun y => R.dagger.compThrough S.dagger z y x) y)
    exact dagger_compThrough S R x y z (Submodule.subset_span ⟨v, hv', rfl⟩)
  · apply iSup_le
    intro y
    apply Submodule.span_le.mpr
    rintro _ ⟨rFromS, sFromR, hrFromS, hsFromR, rfl⟩
    have hs' :
        sFromR ∈ Submodule.span ℂ
          { rᴴ | r ∈ R.component x y } := by
      simpa [dagger] using hsFromR
    have hr' :
        rFromS ∈ Submodule.span ℂ
          { sᴴ | s ∈ S.component y z } := by
      simpa [dagger] using hrFromS
    refine Submodule.span_induction₂
      (p := fun sa ra _ _ => sa * ra ∈ (S.comp R).dagger.component z x)
      (fun rT sT hrT hsT => by
        obtain ⟨r, hr, rfl⟩ := hrT
        obtain ⟨s, hs, rfl⟩ := hsT
        rw [← Matrix.conjTranspose_mul]
        exact mem_dagger
          (le_iSup (fun y => S.compThrough R x y z) y
            (Submodule.subset_span ⟨r, s, hr, hs, rfl⟩)))
      (fun sa _ => by
        rw [Matrix.zero_mul]
        exact zero_mem _)
      (fun ra _ => by
        rw [Matrix.mul_zero]
        exact zero_mem _)
      (fun a b c _ _ _ ha hb => by
        rw [Matrix.add_mul]
        exact add_mem ha hb)
      (fun a b c _ _ _ ha hb => by
        rw [Matrix.mul_add]
        exact add_mem ha hb)
      (fun c ra sa _ _ h => by
        rw [Matrix.smul_mul c ra sa]
        exact Submodule.smul_mem _ c h)
      (fun c ra sa _ _ h => by
        rw [Matrix.mul_smul ra c sa]
        exact Submodule.smul_mem _ c h)
      hs' hr'

private def mulRightLM {n m p : ℕ} (u : Matrix (Fin m) (Fin n) ℂ) :
    Matrix (Fin p) (Fin m) ℂ →ₗ[ℂ] Matrix (Fin p) (Fin n) ℂ where
  toFun t := t * u
  map_add' := fun _ _ => Matrix.add_mul _ _ _
  map_smul' := fun c t => Matrix.smul_mul c t u

private def mulLeftLM {n m p : ℕ} (t : Matrix (Fin p) (Fin m) ℂ) :
    Matrix (Fin m) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin p) (Fin n) ℂ where
  toFun u := t * u
  map_add' := fun _ _ => Matrix.mul_add _ _ _
  map_smul' := fun c u => Matrix.mul_smul t c u

theorem id_comp [DecidableEq Y.Atom] (R : QuantumRel X Y) :
    (id Y).comp R = R := by
  apply ext
  intro x z
  apply le_antisymm
  · apply iSup_le
    intro y
    apply Submodule.span_le.mpr
    rintro m ⟨r, s, hr, hs, rfl⟩
    by_cases hyz : y = z
    · subst z
      have hs' :
          s ∈ Submodule.span ℂ
            {(1 : Matrix (Fin (Y.dim y)) (Fin (Y.dim y)) ℂ)} := by
        simpa [id] using hs
      obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hs'
      have : s * r = c • r := by
        rw [← hc, Matrix.smul_mul, Matrix.one_mul]
      rw [this]
      exact Submodule.smul_mem _ c hr
    · have : s ∈ (⊥ : OpSpace Y Y y z) := by
        simpa [id, hyz] using hs
      have hs0 : s = 0 := by
        simpa [Submodule.mem_bot] using this
      rw [hs0, Matrix.zero_mul]
      exact zero_mem _
  · refine le_trans ?_ (le_iSup (fun y => (id Y).compThrough R x y z) z)
    intro m hm
    refine Submodule.subset_span
      ⟨m, (1 : Matrix (Fin (Y.dim z)) (Fin (Y.dim z)) ℂ), hm, ?_,
        Matrix.one_mul m⟩
    simpa [id] using Submodule.subset_span
      (Set.mem_singleton (1 : Matrix (Fin (Y.dim z)) (Fin (Y.dim z)) ℂ))

theorem comp_id [DecidableEq X.Atom] (R : QuantumRel X Y) :
    R.comp (id X) = R := by
  apply ext
  intro x z
  apply le_antisymm
  · apply iSup_le
    intro y
    apply Submodule.span_le.mpr
    rintro m ⟨r, s, hr, hs, rfl⟩
    by_cases hxy : x = y
    · subst y
      have hr' :
          r ∈ Submodule.span ℂ
            {(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ)} := by
        simpa [id] using hr
      obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hr'
      have : s * r = c • s := by
        rw [← hc, Matrix.mul_smul, Matrix.mul_one]
      rw [this]
      exact Submodule.smul_mem _ c hs
    · have : r ∈ (⊥ : OpSpace X X x y) := by
        simpa [id, hxy] using hr
      have hr0 : r = 0 := by
        simpa [Submodule.mem_bot] using this
      rw [hr0, Matrix.mul_zero]
      exact zero_mem _
  · refine le_trans ?_ (le_iSup (fun y => R.compThrough (id X) x y z) x)
    intro m hm
    refine Submodule.subset_span
      ⟨(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ), m, ?_, hm,
        Matrix.mul_one m⟩
    simpa [id] using Submodule.subset_span
      (Set.mem_singleton (1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ))

theorem assoc (T : QuantumRel Z W) (S : QuantumRel Y Z) (R : QuantumRel X Y) :
    (T.comp S).comp R = T.comp (S.comp R) := by
  apply ext
  intro x w
  apply le_antisymm
  · apply iSup_le
    intro y
    apply Submodule.span_le.mpr
    rintro m ⟨r, t, hr, ht, rfl⟩
    have : t * r ∈
        Submodule.map (mulRightLM (p := W.dim w) r)
          ((T.comp S).component y w) :=
      Submodule.mem_map.mpr ⟨t, ht, rfl⟩
    rw [show (T.comp S).component y w = ⨆ z, T.compThrough S y z w from rfl,
      Submodule.map_iSup] at this
    refine (iSup_le (fun z => ?_) : _ ≤ (T.comp (S.comp R)).component x w) this
    dsimp only [compThrough]
    rw [Submodule.map_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨s, t', hs, ht', rfl⟩, rfl⟩
    change (t' * s) * r ∈ (T.comp (S.comp R)).component x w
    rw [Matrix.mul_assoc]
    apply (le_iSup (fun z => T.compThrough (S.comp R) x z w) z)
    refine Submodule.subset_span ⟨s * r, t', ?_, ht', rfl⟩
    apply (le_iSup (fun y => S.compThrough R x y z) y)
    exact Submodule.subset_span ⟨r, s, hr, hs, rfl⟩
  · apply iSup_le
    intro z
    apply Submodule.span_le.mpr
    rintro m ⟨u, t, hu, ht, rfl⟩
    have : t * u ∈
        Submodule.map (mulLeftLM (n := X.dim x) t)
          ((S.comp R).component x z) :=
      Submodule.mem_map.mpr ⟨u, hu, rfl⟩
    rw [show (S.comp R).component x z = ⨆ y, S.compThrough R x y z from rfl,
      Submodule.map_iSup] at this
    refine (iSup_le (fun y => ?_) : _ ≤ ((T.comp S).comp R).component x w) this
    dsimp only [compThrough]
    rw [Submodule.map_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨r, s, hr, hs, rfl⟩, rfl⟩
    change t * (s * r) ∈ ((T.comp S).comp R).component x w
    rw [← Matrix.mul_assoc]
    apply (le_iSup (fun y => (T.comp S).compThrough R x y w) y)
    refine Submodule.subset_span ⟨r, t * s, hr, ?_, rfl⟩
    apply (le_iSup (fun z => T.compThrough S y z w) z)
    exact Submodule.subset_span ⟨s, t, hs, ht, rfl⟩

theorem id_dagger [DecidableEq X.Atom] : (id X).dagger = id X := by
  apply ext
  intro y x
  by_cases hxy : x = y
  · subst y
    apply le_antisymm
    · apply Submodule.span_le.mpr
      rintro _ ⟨r, hr, rfl⟩
      have hr' :
          r ∈ Submodule.span ℂ
            {(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ)} := by
        simpa [id] using hr
      obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hr'
      have : rᴴ = star c • (1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ) := by
        rw [← hc, Matrix.conjTranspose_smul, conjTranspose_one]
      rw [this]
      simp [id]
      exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))
    · intro m hm
      have hm' :
          m ∈ Submodule.span ℂ
            {(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ)} := by
        simpa [id] using hm
      obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hm'
      refine Submodule.subset_span ⟨star c • (1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ), ?_, ?_⟩
      · simp [id]
        exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))
      · rw [Matrix.conjTranspose_smul, conjTranspose_one, star_star, hc]
  · have hne : y ≠ x := Ne.symm hxy
    simp [id, dagger, hxy, hne]

theorem function_eq_of_le [DecidableEq X.Atom] [DecidableEq Y.Atom]
    {F G : QuantumRel X Y} (hF : F.IsFunction) (hG : G.IsFunction)
    (hFG : F ≤ G) : F = G := by
  apply le_antisymm hFG
  have h1 : G = G.comp (id X) := (comp_id G).symm
  have h2 : G.comp (id X) ≤ G.comp (F.dagger.comp F) :=
    comp_mono_right hF.2
  have h3 : G.comp (F.dagger.comp F) = (G.comp F.dagger).comp F :=
    (assoc G F.dagger F).symm
  have h4 : G.comp F.dagger ≤ G.comp G.dagger :=
    comp_mono_right (dagger_mono hFG)
  have h5 : (G.comp F.dagger).comp F ≤ (id Y).comp F :=
    comp_mono_left F (h4.trans hG.1)
  have h6 : (id Y).comp F = F := id_comp F
  exact h1.trans_le (h2.trans (h3.le.trans (h5.trans h6.le)))

theorem IsFunction.comp [DecidableEq X.Atom] [DecidableEq Y.Atom]
    [DecidableEq Z.Atom] {S : QuantumRel Y Z} {R : QuantumRel X Y}
    (hS : S.IsFunction) (hR : R.IsFunction) :
    (S.comp R).IsFunction := by
  constructor
  · calc
      (S.comp R).comp (S.comp R).dagger
          = (S.comp R).comp (R.dagger.comp S.dagger) := by
            rw [dagger_comp]
      _ = S.comp ((R.comp R.dagger).comp S.dagger) := by
            rw [← assoc (S.comp R) R.dagger S.dagger,
              assoc S R R.dagger,
              assoc S (R.comp R.dagger) S.dagger]
      _ ≤ S.comp ((id Y).comp S.dagger) :=
            comp_mono_right (comp_mono_left S.dagger hR.1)
      _ = S.comp S.dagger := by
            rw [id_comp]
      _ ≤ id Z := hS.1
  · have hRle : R ≤ S.dagger.comp (S.comp R) := by
      calc
        R = (id Y).comp R := (id_comp R).symm
        _ ≤ (S.dagger.comp S).comp R :=
          comp_mono_left R hS.2
        _ = S.dagger.comp (S.comp R) := assoc _ _ _
    calc
      id X ≤ R.dagger.comp R := hR.2
      _ ≤ R.dagger.comp (S.dagger.comp (S.comp R)) :=
          comp_mono_right hRle
      _ = (R.dagger.comp S.dagger).comp (S.comp R) :=
          (assoc _ _ _).symm
      _ = (S.comp R).dagger.comp (S.comp R) := by
          rw [← dagger_comp]

/-- Right composition by a quantum function preserves countable meets.
This is the relational algebra lemma used in the qCPO limit proofs. -/
theorem iInf_comp_of_function [DecidableEq X.Atom] [DecidableEq Y.Atom]
    (S : ℕ → QuantumRel Y Z) (F : QuantumRel X Y) (hF : F.IsFunction) :
    (⨅ n, S n).comp F = ⨅ n, (S n).comp F := by
  apply le_antisymm
  · apply le_iInf
    intro n
    exact comp_mono_left F (iInf_le S n)
  · let T : QuantumRel X Z := ⨅ n, (S n).comp F
    have hTF : T.comp F.dagger ≤ ⨅ n, S n := by
      apply le_iInf
      intro n
      calc
        T.comp F.dagger ≤ ((S n).comp F).comp F.dagger :=
          comp_mono_left F.dagger (iInf_le (fun n => (S n).comp F) n)
        _ = (S n).comp (F.comp F.dagger) := assoc _ _ _
        _ ≤ (S n).comp (id Y) := comp_mono_right hF.1
        _ = S n := comp_id _
    change T ≤ (⨅ n, S n).comp F
    calc
      T = T.comp (id X) := (comp_id T).symm
      _ ≤ T.comp (F.dagger.comp F) := comp_mono_right hF.2
      _ = (T.comp F.dagger).comp F := (assoc _ _ _).symm
      _ ≤ (⨅ n, S n).comp F := comp_mono_left F hTF

/-- Restrict the domain of a relation to one atomic summand. -/
def restrictAtom (R : QuantumRel X Y) (x : X.Atom) :
    QuantumRel (.atomic (X.dim x)) Y where
  component := fun _ y => R.component x y

/-- Reassemble a relation from its restrictions to all domain atoms. -/
def assembleAtoms
    (K : ∀ x : X.Atom, QuantumRel (.atomic (X.dim x)) Y) :
    QuantumRel X Y where
  component := fun x y => (K x).component PUnit.unit y

@[simp] theorem restrictAtom_assembleAtoms
    (K : ∀ x : X.Atom, QuantumRel (.atomic (X.dim x)) Y)
    (x : X.Atom) :
    restrictAtom (assembleAtoms K) x = K x := by
  apply ext
  intro u y
  cases u
  rfl

@[simp] theorem assembleAtoms_restrictAtom (R : QuantumRel X Y) :
    assembleAtoms (fun x => restrictAtom R x) = R := by
  apply ext
  intro x y
  rfl

theorem restrictAtom_mono {R S : QuantumRel X Y} (h : R ≤ S)
    (x : X.Atom) :
    restrictAtom R x ≤ restrictAtom S x := by
  intro u y
  exact h x y

@[simp] theorem restrictAtom_comp (S : QuantumRel Y Z)
    (R : QuantumRel X Y) (x : X.Atom) :
    restrictAtom (S.comp R) x = S.comp (restrictAtom R x) := by
  apply ext
  intro u z
  cases u
  rfl

theorem restrictAtom_comp_dagger_le (R : QuantumRel X Y) (x : X.Atom) :
    (restrictAtom R x).comp (restrictAtom R x).dagger ≤
      R.comp R.dagger := by
  intro y z
  calc
    ((restrictAtom R x).comp
        (restrictAtom R x).dagger).component y z =
        (restrictAtom R x).compThrough
          (restrictAtom R x).dagger y
            (default : (QuantumSet.atomic (X.dim x)).Atom) z :=
      by
        change (⨆ u : (QuantumSet.atomic (X.dim x)).Atom,
          (restrictAtom R x).compThrough
            (restrictAtom R x).dagger y u z) =
          (restrictAtom R x).compThrough
            (restrictAtom R x).dagger y default z
        exact iSup_unique
          (f := fun u : (QuantumSet.atomic (X.dim x)).Atom =>
            (restrictAtom R x).compThrough
              (restrictAtom R x).dagger y u z)
    _ = R.compThrough R.dagger y x z := by rfl
    _ ≤ (R.comp R.dagger).component y z :=
      le_iSup (fun x' => R.compThrough R.dagger y x' z) x

theorem restrictAtom_dagger_comp_self_component (R : QuantumRel X Y)
    (x : X.Atom) (u v : (QuantumSet.atomic (X.dim x)).Atom) :
    ((restrictAtom R x).dagger.comp (restrictAtom R x)).component u v =
      (R.dagger.comp R).component x x := by
  cases u
  cases v
  rfl

theorem restrictAtom_isFunction [DecidableEq X.Atom] [DecidableEq Y.Atom]
    {R : QuantumRel X Y} (hR : R.IsFunction) (x : X.Atom) :
    (restrictAtom R x).IsFunction := by
  constructor
  · exact (restrictAtom_comp_dagger_le R x).trans hR.1
  · intro u v
    have hu : u = default := Subsingleton.elim _ _
    have hv : v = default := Subsingleton.elim _ _
    subst u
    subst v
    rw [id_component_eq]
    rw [restrictAtom_dagger_comp_self_component]
    change
      Submodule.span ℂ
          {(1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ)} ≤
        (R.dagger.comp R).component x x
    simpa only [id_component_eq] using hR.2 x x

theorem assembleAtoms_isFunction [DecidableEq X.Atom] [DecidableEq Y.Atom]
    (K : ∀ x : X.Atom, QuantumRel (.atomic (X.dim x)) Y)
    (hK : ∀ x, (K x).IsFunction) :
    (assembleAtoms K).IsFunction := by
  constructor
  · intro y z
    apply iSup_le
    intro x
    have hx := (hK x).1 y z
    change (K x).compThrough (K x).dagger y
        (default : (QuantumSet.atomic (X.dim x)).Atom) z ≤
      (id Y).component y z
    exact (le_iSup
      (fun u => (K x).compThrough (K x).dagger y u z)
      (default : (QuantumSet.atomic (X.dim x)).Atom)).trans hx
  · intro x x'
    by_cases hxx : x = x'
    · subst x'
      rw [id_component_eq]
      apply Submodule.span_le.mpr
      rintro _ rfl
      have hone :
          (1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ) ∈
            (id (QuantumSet.atomic (X.dim x))).component
              default default := by
        rw [id_component_eq]
        exact Submodule.subset_span
          (Set.mem_singleton
            (1 : Matrix (Fin (X.dim x)) (Fin (X.dim x)) ℂ))
      exact (hK x).2 default default hone
    · rw [id_component_ne hxx]
      exact bot_le

theorem iInf_component (S : ℕ → QuantumRel X Y) (x : X.Atom) (y : Y.Atom) :
    (⨅ n, S n).component x y = ⨅ n, (S n).component x y := by
  apply le_antisymm
  · apply le_iInf
    intro n
    exact iInf_le_of_le ⟨S n, ⟨n, rfl⟩⟩ le_rfl
  · apply le_iInf
    intro R
    obtain ⟨n, hn⟩ := R.property
    rw [← hn]
    exact iInf_le (fun n => (S n).component x y) n

@[simp] theorem restrictAtom_iInf (S : ℕ → QuantumRel X Y) (x : X.Atom) :
    restrictAtom (⨅ n, S n) x = ⨅ n, restrictAtom (S n) x := by
  apply ext
  intro u y
  rw [iInf_component]
  exact iInf_component S x y

theorem iSup_component (S : ℕ → QuantumRel X Y) (x : X.Atom) (y : Y.Atom) :
    (⨆ n, S n).component x y = ⨆ n, (S n).component x y := by
  apply le_antisymm
  · apply iSup_le
    intro ⟨R, hR⟩
    obtain ⟨n, hn⟩ := hR
    subst R
    exact le_iSup (fun n => (S n).component x y) n
  · apply iSup_le
    intro n
    exact le_iSup_of_le ⟨S n, ⟨n, rfl⟩⟩ le_rfl

theorem comp_iSup_left (S : ℕ → QuantumRel Y Z) (R : QuantumRel X Y) :
    (⨆ n, S n).comp R = ⨆ n, (S n).comp R := by
  apply le_antisymm
  · intro x z
    apply iSup_le
    intro y
    apply Submodule.span_le.mpr
    rintro m ⟨r, s, hr, hs, rfl⟩
    have : s * r ∈
        Submodule.map (mulRightLM (p := Z.dim z) r)
          ((⨆ n, S n).component y z) :=
      Submodule.mem_map.mpr ⟨s, hs, rfl⟩
    rw [iSup_component S y z, Submodule.map_iSup] at this
    refine (iSup_le (fun n => ?_) :
      _ ≤ (⨆ n, (S n).comp R).component x z) this
    intro t ht
    obtain ⟨s', hs', rfl⟩ := Submodule.mem_map.mp ht
    apply (le_iSup (fun n => (S n).comp R) n)
    apply (le_iSup (fun y => (S n).compThrough R x y z) y)
    exact Submodule.subset_span ⟨r, s', hr, hs', rfl⟩
  · apply iSup_le
    intro n
    exact comp_mono_left R (le_iSup S n)

theorem comp_iSup_right (S : QuantumRel Y Z) (R : ℕ → QuantumRel X Y) :
    S.comp (⨆ n, R n) = ⨆ n, S.comp (R n) := by
  apply le_antisymm
  · intro x z
    apply iSup_le
    intro y
    apply Submodule.span_le.mpr
    rintro m ⟨r, s, hr, hs, rfl⟩
    have : s * r ∈
        Submodule.map (mulLeftLM (n := X.dim x) s)
          ((⨆ n, R n).component x y) :=
      Submodule.mem_map.mpr ⟨r, hr, rfl⟩
    rw [iSup_component R x y, Submodule.map_iSup] at this
    refine (iSup_le (fun n => ?_) :
      _ ≤ (⨆ n, S.comp (R n)).component x z) this
    intro t ht
    obtain ⟨r', hr', rfl⟩ := Submodule.mem_map.mp ht
    apply (le_iSup (fun n => S.comp (R n)) n)
    apply (le_iSup (fun y => S.compThrough (R n) x y z) y)
    exact Submodule.subset_span ⟨r', s, hr', hs, rfl⟩
  · apply iSup_le
    intro n
    exact comp_mono_right (le_iSup R n)

/-- Conjugation by a unitary on an atomic quantum set. -/
def ofUnitary {n : ℕ}
    (U : Matrix (Fin n) (Fin n) ℂ) : QuantumRel (.atomic n) (.atomic n) where
  component _ _ := Submodule.span ℂ {U}

theorem ofUnitary_dagger {n : ℕ} (U : Matrix (Fin n) (Fin n) ℂ) :
    (ofUnitary U).dagger = ofUnitary Uᴴ := by
  apply ext
  intro x y
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨r, hr, rfl⟩
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hr
    have : rᴴ = star c • Uᴴ := by
      rw [← hc]
      exact Matrix.conjTranspose_smul (R := ℂ) (M := U) c
    rw [this]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))
  · apply Submodule.span_le.mpr
    rintro m rfl
    refine Submodule.subset_span ⟨U, Submodule.subset_span (Set.mem_singleton _), rfl⟩

theorem ofUnitary_comp {n : ℕ}
    (S R : Matrix (Fin n) (Fin n) ℂ) :
    (ofUnitary S).comp (ofUnitary R) = ofUnitary (S * R) := by
  apply ext
  intro x z
  simp only [comp]
  trans (ofUnitary S).compThrough (ofUnitary R) x
      (default : (QuantumSet.atomic n).Atom) z
  · exact iSup_unique
      (f := fun y : (QuantumSet.atomic n).Atom =>
        (ofUnitary S).compThrough (ofUnitary R) x y z)
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨r, s, hr, hs, rfl⟩
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hr
    obtain ⟨d, hd⟩ := Submodule.mem_span_singleton.mp hs
    have : s * r = (d * c) • (S * R) := by
      rw [← hc, ← hd]
      calc
        (d • S) * (c • R)
          = d • (S * (c • R)) := Matrix.smul_mul d S (c • R)
        _ = d • (c • (S * R)) := by rw [Matrix.mul_smul]
        _ = (d * c) • (S * R) := smul_smul d c (S * R)
    rw [this]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))
  · apply Submodule.span_le.mpr
    rintro m rfl
    refine Submodule.subset_span ⟨R, S,
      Submodule.subset_span (Set.mem_singleton _),
      Submodule.subset_span (Set.mem_singleton _), rfl⟩

theorem ofUnitary_one {n : ℕ} :
    ofUnitary (1 : Matrix (Fin n) (Fin n) ℂ) = id (.atomic n) := by
  apply ext
  intro x y
  have hx : x = default := Subsingleton.elim _ _
  have hy : y = default := Subsingleton.elim _ _
  subst hx
  subst hy
  simp only [ofUnitary]
  exact (id_component_eq (default : (QuantumSet.atomic n).Atom)).symm

theorem ofUnitary_isFunction {n : ℕ}
    (U : Matrix (Fin n) (Fin n) ℂ)
    (hL : Uᴴ * U = 1) (hR : U * Uᴴ = 1) :
    (ofUnitary U).IsFunction := by
  constructor
  · rw [ofUnitary_dagger, ofUnitary_comp, hR, ofUnitary_one]
  · rw [ofUnitary_dagger, ofUnitary_comp, hL, ofUnitary_one]

/-- Computational-basis bras used to present measurement as a function. -/
def bra0 : KrausOperator 2 1 :=
  !![(1 : ℂ), 0]

def bra1 : KrausOperator 2 1 :=
  !![(0 : ℂ), 1]

/-- Computational-basis measurement of one qubit. -/
def qubitMeasure : QuantumRel .qubit .bit where
  component _
    | false => Submodule.span ℂ {bra0}
    | true => Submodule.span ℂ {bra1}

/-- A projection-valued measurement from an atomic system onto a
classical finite set.  The component at outcome `b` is the operators
that factor through the corresponding projector. -/
def ofPVM {n : ℕ} {α : Type} [Fintype α]
    (π : α → Matrix (Fin n) (Fin n) ℂ) :
    QuantumRel (.atomic n) (.liftSet α) where
  component _ b :=
    Submodule.span ℂ
      { (v : KrausOperator n 1) | v * (1 - π b) = 0 }

/-- The zero-state allocation channel `1 → qubit`. -/
def new0 : QuantumRel .unit .qubit where
  component _ _ :=
    Submodule.span ℂ {!![(1 : ℂ); 0]}

end QuantumRel

end QLambda.Domain
