/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/

module

public import QLambda.Composer.OpenQASM

@[expose] public section

/-!
# Parser for the rendered OpenQASM interchange fragment

This is deliberately a parser for the deterministic text emitted by
`Program.renderOpenQASM`, not a general OpenQASM parser.  Its exact grammar is:

* the four fixed header lines emitted by the renderer;
* `x`, `h`, `t`, `ry`, `cx`, measurement, reset, Boolean store, barrier,
  delay, `break`, and `continue`;
* brace-delimited `if`/`else`, Boolean `switch` cases, counted `for`, boxes,
  and the renderer's nested-`if` finite unrolling of bounded `while`;
* Boolean expressions generated by `CExpr.toOpenQASM`.

Whitespace, register names, declaration order, punctuation, and line layout
are exact.  A final render check rejects non-canonical spellings.

Two renderer erasures necessarily have canonical parses: a zero-count `for`
is parsed as `.forLoop 0 []`, and a zero-fuel `while` marker cannot recover a
guard or body and is accepted only as the terminator inside a positive-fuel
rendering.  Consequently `Program.ParserCanonical` below is the exact AST
boundary for two-sided round trips.
-/

namespace QLambda.Composer

def ofChars : List Char → String
  | [] => ""
  | c :: cs => String.singleton c ++ ofChars cs

def startsWithStr (pre s : String) : Bool :=
  pre.toList.isPrefixOf s.toList

def dropStr (n : Nat) (s : String) : String :=
  ofChars (s.toList.drop n)

def dropEndStr (n : Nat) (s : String) : String :=
  let xs := s.toList
  ofChars (xs.take (xs.length - n))

def endsWithStr (post s : String) : Bool :=
  let xs := s.toList
  let ps := post.toList
  xs.drop (xs.length - ps.length) == ps

def trimLeft : List Char → List Char
  | [] => []
  | ' ' :: cs => trimLeft cs
  | '\t' :: cs => trimLeft cs
  | '\n' :: cs => trimLeft cs
  | '\r' :: cs => trimLeft cs
  | cs => cs

def trimStr (s : String) : String :=
  ofChars (trimLeft (trimLeft s.toList.reverse).reverse)

def digit? (c : Char) : Option Nat :=
  if c = '0' then some 0 else if c = '1' then some 1 else if c = '2' then some 2
  else if c = '3' then some 3 else if c = '4' then some 4 else if c = '5' then some 5
  else if c = '6' then some 6 else if c = '7' then some 7 else if c = '8' then some 8
  else if c = '9' then some 9 else none

def parseNatChars (acc : Nat) : List Char → Option Nat
  | [] => some acc
  | c :: cs =>
    match digit? c with
    | some d => parseNatChars (acc * 10 + d) cs
    | none => none

def parseNatStr (s : String) : Option Nat :=
  match s.toList with
  | [] => none
  | cs => parseNatChars 0 cs

/-- Split on one character. Structural on the character list, so the kernel reduces it. -/
def splitChar (sep : Char) : String → List Char → List String
  | acc, [] => [acc]
  | acc, c :: cs =>
    if c = sep then
      acc :: splitChar sep "" cs
    else
      splitChar sep (acc ++ String.singleton c) cs

/-- Split on a two-character separator. Every recursive call is on the tail. -/
def splitTwo (a b : Char) : Bool → String → List Char → List String
  | _, acc, [] => [acc]
  | false, acc, c :: cs =>
    if c = a then
      splitTwo a b true acc cs
    else
      splitTwo a b false (acc ++ String.singleton c) cs
  | true, acc, c :: cs =>
    if c = b then
      acc :: splitTwo a b false "" cs
    else if c = a then
      splitTwo a b true (acc ++ String.singleton a) cs
    else
      splitTwo a b false (acc ++ String.singleton a ++ String.singleton c) cs

/-- Split on a three-character separator. Every recursive call is on the tail. -/
def splitThree (a b c : Char) : Nat → String → List Char → List String
  | _, acc, [] => [acc]
  | 0, acc, x :: xs =>
    if x = a then
      splitThree a b c 1 acc xs
    else
      splitThree a b c 0 (acc ++ String.singleton x) xs
  | 1, acc, x :: xs =>
    if x = b then
      splitThree a b c 2 acc xs
    else if x = a then
      splitThree a b c 1 (acc ++ String.singleton a) xs
    else
      splitThree a b c 0 (acc ++ String.singleton a ++ String.singleton x) xs
  | _, acc, x :: xs =>
    if x = c then
      acc :: splitThree a b c 0 "" xs
    else if x = a then
      splitThree a b c 1 (acc ++ String.singleton a ++ String.singleton b) xs
    else
      splitThree a b c 0
        (acc ++ String.singleton a ++ String.singleton b ++ String.singleton x) xs

def parseFin (bound : ℕ) (pre : String) (s : String) :
    Option (Fin bound) := do
  if !(startsWithStr (pre ++ "[") s) || !(endsWithStr "]" s) then
    none
  else
    let digits := dropEndStr 1 (dropStr (pre.length + 1) s)
    let n ← parseNatStr digits
    if h : n < bound then some ⟨n, h⟩ else none

def parseQRef (q : ℕ) : String → Option (Fin q) :=
  parseFin q "q"

def parseCRef (c : ℕ) : String → Option (Fin c) :=
  parseFin c "c"

def parseRat (s : String) : Option ℚ :=
  match splitChar '/' "" s.toList with
  | [n] => Rat.ofInt <$> n.toInt?
  | [n, d] => do
      let numerator ← n.toInt?
      let denominator ← d.toNat?
      if h : denominator = 0 then none
      else some (Rat.normalize numerator denominator h)
  | _ => none

def parseAngle (s : String) : Option AngleExpr :=
  if startsWithStr "2*acos(sqrt(" s && endsWithStr "))" s then do
    let body := dropEndStr 2 (dropStr 12 s)
    let p ← parseRat body
    if h0 : 0 ≤ p then
      if h1 : p ≤ 1 then some (.coin ⟨p, h0, h1⟩) else none
    else none
  else
    .rational <$> parseRat s

def withoutSemi (s : String) : Option String :=
  if endsWithStr ";" s then some (dropEndStr 1 s) else none

def stripAffixes (pre post s : String) : Option String :=
  if startsWithStr pre s && endsWithStr post s then
    some (dropEndStr post.length (dropStr pre.length s))
  else
    none

def dropChars (pre xs : List Char) : Option (List Char) :=
  if pre.isPrefixOf xs then some (xs.drop pre.length) else none

def takeUntil (stop : Char) : List Char → List Char
  | [] => []
  | c :: cs => if c = stop then [] else c :: takeUntil stop cs

def parseCChars (c : ℕ) :
    Nat → List Char → Option (CExpr c × List Char)
  | 0, _ => none
  | fuel + 1, xs =>
      if let some rest := dropChars "true".toList xs then
        some (.lit true, rest)
      else if let some rest := dropChars "false".toList xs then
        some (.lit false, rest)
      else if let some rest := dropChars "c[".toList xs then
        let digits := takeUntil ']' rest
        match rest.drop digits.length with
        | ']' :: tail => do
            let i ← parseCRef c ("c[" ++ ofChars digits ++ "]")
            pure (.bit i, tail)
        | _ => none
      else if let some rest := dropChars "!(".toList xs then do
        let (e, tail) ← parseCChars c fuel rest
        let tail ← dropChars [')'] tail
        pure (.not e, tail)
      else if let some rest := dropChars ['('] xs then do
        let (lhs, tail) ← parseCChars c fuel rest
        let (op, tail) ←
          if let some r := dropChars " && ".toList tail then
            some (0, r)
          else if let some r := dropChars " || ".toList tail then
            some (1, r)
          else if let some r := dropChars " != ".toList tail then
            some (2, r)
          else none
        let (rhs, tail) ← parseCChars c fuel tail
        let tail ← dropChars [')'] tail
        let e := match op with
          | 0 => .and lhs rhs
          | 1 => .or lhs rhs
          | _ => .xor lhs rhs
        pure (e, tail)
      else none

/-- Parse exactly the fully parenthesized Boolean expression language emitted
by `CExpr.toOpenQASM`. -/
def parseCExpr (c : ℕ) (s : String) : Option (CExpr c) := do
  let (e, rest) ← parseCChars c (s.length + 1) s.toList
  if rest = [] then some e else none

def parseRefs (q : ℕ) (s : String) : Option (List (Fin q)) :=
  if s = "" then some []
  else (splitTwo ',' ' ' false "" s.toList).mapM (parseQRef q)

/-- Parse one non-structured instruction in the interchange fragment. -/
def parseSimpleInstr (q c : ℕ) (line : String) : Option (Instr q c) := do
  let s ← withoutSemi (trimStr line)
  match splitChar ' ' "" s.toList with
  | ["x", w] => return .gate (.x (← parseQRef q w))
  | ["h", w] => return .gate (.h (← parseQRef q w))
  | ["t", w] => return .gate (.t (← parseQRef q w))
  | ["reset", w] => return .reset (← parseQRef q w)
  | ["break"] => return .break
  | ["continue"] => return .continue
  | ["cx", control, target] =>
      if !endsWithStr "," control then none
      else
        return .gate (.cx
          (← parseQRef q (dropEndStr 1 control))
          (← parseQRef q target))
  | [lhs, "=", "measure", rhs] =>
      return .measure (← parseQRef q rhs) (← parseCRef c lhs)
  | _ =>
      if startsWithStr "ry(" s then
        match splitTwo ')' ' ' false "" s.toList with
        | [angle, w] =>
            return .gate (.ry
              (← parseAngle (dropStr 3 angle))
              (← parseQRef q w))
        | _ => none
      else if startsWithStr "barrier " s then
        return .barrier (← parseRefs q (dropStr 8 s))
      else if startsWithStr "delay[" s then
        match splitTwo ']' ' ' false "" s.toList with
        | [duration, refs] =>
            if !endsWithStr "dt" duration then none
            else
              let n ← parseNatStr (dropEndStr 2 (dropStr 6 duration))
              return .delay n (← parseRefs q refs)
        | _ => none
      else
        match splitThree ' ' '=' ' ' 0 "" s.toList with
        | [lhs, rhs] =>
            return .store (← parseCRef c lhs) (← parseCExpr c rhs)
        | _ => none

inductive ParsedInstr (q c : ℕ) where
  | instr : Instr q c → ParsedInstr q c
  | whileEnd : ParsedInstr q c
  | whileStep : Nat → CExpr c → List (Instr q c) → ParsedInstr q c

def finishParsed {q c : ℕ} :
    List (ParsedInstr q c) → Option (List (Instr q c))
  | [] => some []
  | .instr i :: rest => return i :: (← finishParsed rest)
  | .whileStep fuel guard body :: rest =>
      return .whileLoop fuel guard body :: (← finishParsed rest)
  | .whileEnd :: _ => none

def finishWhile {q c : ℕ} (guard : CExpr c)
    (body : List (ParsedInstr q c)) : Option (ParsedInstr q c) :=
  match body.reverse with
  | .whileEnd :: prefixLines =>
      return .whileStep 1 guard (← finishParsed prefixLines.reverse)
  | .whileStep fuel _ _ :: prefixLines =>
      return .whileStep (fuel + 1) guard (← finishParsed prefixLines.reverse)
  | _ => none

/-- Fuel-indexed parser. `partial` mutual recursion has no kernel body. -/
def parseGo {q c : ℕ} (fuel : Nat) (casesMode : Bool) (ls : List String) :
    Option (Sum (List (ParsedInstr q c) × List String)
                (List (Bool × List (Instr q c)) × List String)) :=
  match fuel with
  | 0 => none
  | fuel + 1 =>
    if casesMode then
      match ls with
      | [] => none
      | "" :: rest => parseGo fuel true rest
      | "}" :: rest => some (.inr ([], rest))
      | line :: rest => do
          let label ← stripAffixes "case " " {" line
          let value ← if label = "true" then some true
            else if label = "false" then some false else none
          let some (.inl (body, rest)) := parseGo fuel false rest | none
          let body ← finishParsed body
          let rest ← match rest with
            | "}" :: rest => some rest
            | _ => none
          let some (.inr (cases, rest)) := parseGo fuel true rest | none
          some (.inr ((value, body) :: cases, rest))
    else
      match ls with
      | [] => some (.inl ([], []))
      | line :: rest =>
          if line = "" then
            parseGo fuel false rest
          else if line = "}" || line = "} else {" then
            some (.inl ([], line :: rest))
          else if line = "// bounded while exhausted" then
            match parseGo fuel false rest with
            | some (.inl (is, rest)) => some (.inl (.whileEnd :: is, rest))
            | _ => none
          else if line = "// zero-iteration for loop" then
            match parseGo fuel false rest with
            | some (.inl (is, rest)) => some (.inl (.instr (.forLoop 0 []) :: is, rest))
            | _ => none
          else if let some guardText := stripAffixes "if (" ") {" line then
            match parseCExpr c guardText with
            | none => none
            | some guard =>
              match parseGo fuel false rest with
              | some (.inl (yes, "} else {" :: rest)) =>
                match parseGo fuel false rest with
                | some (.inl (no, "}" :: rest)) => do
                    let yes ← finishParsed yes
                    let no ← finishParsed no
                    match parseGo fuel false rest with
                    | some (.inl (is, rest)) =>
                      some (.inl (.instr (.ite guard yes no) :: is, rest))
                    | _ => none
                | _ => none
              | some (.inl (yes, "}" :: rest)) => do
                  let i ← finishWhile guard yes
                  match parseGo fuel false rest with
                  | some (.inl (is, rest)) => some (.inl (i :: is, rest))
                  | _ => none
              | _ => none
          else if let some guardText := stripAffixes "switch (" ") {" line then
            match parseCExpr c guardText with
            | none => none
            | some guard =>
              match parseGo fuel true rest with
              | some (.inr (cases, rest)) =>
                match parseGo fuel false rest with
                | some (.inl (is, rest)) =>
                  some (.inl (.instr (.switch guard cases) :: is, rest))
                | _ => none
              | _ => none
          else if let some last := stripAffixes "for uint _i in [0:" "] {" line then
            match parseNatStr last with
            | none => none
            | some last =>
              match parseGo fuel false rest with
              | some (.inl (body, "}" :: rest)) => do
                  let body ← finishParsed body
                  match parseGo fuel false rest with
                  | some (.inl (is, rest)) =>
                    some (.inl (.instr (.forLoop (last + 1) body) :: is, rest))
                  | _ => none
              | _ => none
          else if let some label := stripAffixes "box { // " "" line then
            match parseGo fuel false rest with
            | some (.inl (body, "}" :: rest)) => do
                let body ← finishParsed body
                match parseGo fuel false rest with
                | some (.inl (is, rest)) =>
                  some (.inl (.instr (.box label body) :: is, rest))
                | _ => none
            | _ => none
          else
            match parseSimpleInstr q c line with
            | none => none
            | some i =>
              match parseGo fuel false rest with
              | some (.inl (is, rest)) => some (.inl (.instr i :: is, rest))
              | _ => none

def parseBlock (q c : ℕ) (ls : List String) :
    Option (List (ParsedInstr q c) × List String) :=
  match parseGo (ls.length * 4 + 4) false ls with
  | some (.inl parsed) => some parsed
  | _ => none

def parseCandidate (q c : ℕ) (text : String) :
    Option (Program .openQASM3_0_ibmComposer_2026_09 q c) :=
  match splitChar '\n' "" text.toList with
  | version :: includeLine :: qdecl :: cdecl :: body =>
      if version = "OPENQASM 3.0;" ∧
          includeLine = "include \"stdgates.inc\";" ∧
          qdecl = "qubit[" ++ natStr q ++ "] q;" ∧
          cdecl = "bit[" ++ natStr c ++ "] c;" then do
        let (instructions, rest) ← parseBlock q c body
        if rest ≠ [] then none
        let instructions ← finishParsed instructions
        pure ⟨instructions⟩
      else none
  | _ => none

noncomputable def acceptRendered {q c : ℕ} (text : String)
    (P : Program .openQASM3_0_ibmComposer_2026_09 q c) :
    Option (Program .openQASM3_0_ibmComposer_2026_09 q c) :=
  if P.renderOpenQASM = text then some P else none

private theorem acceptRendered_sound {q c : ℕ} {text : String}
    {P P' : Program .openQASM3_0_ibmComposer_2026_09 q c}
    (h : acceptRendered text P = some P') :
    P'.renderOpenQASM = text := by
  unfold acceptRendered at h
  split at h <;> simp_all

/-- Parse the complete, structured, canonical interchange grammar documented
at the top of this module. -/
noncomputable def parseStructuredProgram (q c : ℕ) (text : String) :
    Option (Program .openQASM3_0_ibmComposer_2026_09 q c) :=
  match parseCandidate q c text with
  | none => none
  | some P => acceptRendered text P

/-- Exact AST boundary for two-sided render/parse round trips.  In particular,
it excludes information erased by zero-count loops and any label containing a
newline. -/
def Program.ParserCanonical {q c : ℕ}
    (P : Program .openQASM3_0_ibmComposer_2026_09 q c) : Prop :=
  parseStructuredProgram q c P.renderOpenQASM = some P

/-- Exact accepted textual language.  This operational definition supplements
the grammar above by requiring canonical rendering byte-for-byte. -/
def SupportedOpenQASMText (q c : ℕ) (text : String) : Prop :=
  ∃ P, parseStructuredProgram q c text = some P

/-- Every accepted structured program renders back byte-for-byte. -/
theorem parseStructuredProgram_render_roundTrip {q c : ℕ} {text : String}
    {P : Program .openQASM3_0_ibmComposer_2026_09 q c}
    (h : parseStructuredProgram q c text = some P) :
    P.renderOpenQASM = text := by
  unfold parseStructuredProgram at h
  generalize hc : parseCandidate q c text = candidate at h
  cases candidate with
  | none => simp at h
  | some candidate =>
      exact acceptRendered_sound h

/-- On the exact canonical AST subset, parsing after rendering is identity. -/
theorem Program.parse_render_roundTrip {q c : ℕ}
    (P : Program .openQASM3_0_ibmComposer_2026_09 q c)
    (h : P.ParserCanonical) :
    parseStructuredProgram q c P.renderOpenQASM = some P :=
  h

/-- The public well-formed renderer also round-trips byte-for-byte after any
successful parse. -/
theorem parseStructuredProgram_toOpenQASM_roundTrip {q c : ℕ} {text : String}
    {P : Program .openQASM3_0_ibmComposer_2026_09 q c}
    (hP : P.WellFormed)
    (h : parseStructuredProgram q c text = some P) :
    P.toOpenQASM hP = text := by
  simpa [Program.toOpenQASM] using
    (parseStructuredProgram_render_roundTrip h)

/-- Backwards-compatible name for parsing one flat instruction. -/
abbrev parseFlatInstr := parseSimpleInstr

/-- Backwards-compatible entry point; it now accepts the structured grammar. -/
noncomputable def parseFlatProgram := parseStructuredProgram

end QLambda.Composer
