/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import QLambda.Composer.OpenQASM

/-!
# Parser for the rendered OpenQASM interchange fragment

This is deliberately a parser for the deterministic text emitted by
`Program.renderOpenQASM`, not a general OpenQASM parser.  Its exact grammar is:

* the four fixed header lines emitted by the renderer;
* `x`, `h`, `t`, `ry`, `cx`, measurement, reset, Boolean store, barrier,
  delay, `break`, and `continue`;
* brace-delimited `if`/`else`, Boolean `switch` cases, counted `for`, boxes,
  and the renderer's nested-`if` finite unrolling of bounded `while`;
* Boolean expressions generated by `CExpr.toOpenQASM`.

Whitespace, register names, declaration order, punctuation, and line layout
are exact.  A final render check rejects non-canonical spellings.

Two renderer erasures necessarily have canonical parses: a zero-count `for`
is parsed as `.forLoop 0 []`, and a zero-fuel `while` marker cannot recover a
guard or body and is accepted only as the terminator inside a positive-fuel
rendering.  Consequently `Program.ParserCanonical` below is the exact AST
boundary for two-sided round trips.
-/

namespace QLambda.Composer

private def parseFin (bound : ℕ) (pre : String) (s : String) :
    Option (Fin bound) := do
  if !(s.startsWith (pre ++ "[")) || !(s.endsWith "]") then
    none
  else
    let digits := ((s.drop (pre.length + 1)).toString.dropEnd 1).toString
    let n ← digits.toNat?
    if h : n < bound then some ⟨n, h⟩ else none

private def parseQRef (q : ℕ) : String → Option (Fin q) :=
  parseFin q "q"

private def parseCRef (c : ℕ) : String → Option (Fin c) :=
  parseFin c "c"

private def parseRat (s : String) : Option ℚ :=
  match s.splitOn "/" with
  | [n] => Rat.ofInt <$> n.toInt?
  | [n, d] => do
      let numerator ← n.toInt?
      let denominator ← d.toNat?
      if h : denominator = 0 then none
      else some (Rat.normalize numerator denominator h)
  | _ => none

private def parseAngle (s : String) : Option AngleExpr :=
  if s.startsWith "2*acos(sqrt(" && s.endsWith "))" then do
    let body := ((s.drop 12).toString.dropEnd 2).toString
    let p ← parseRat body
    if h0 : 0 ≤ p then
      if h1 : p ≤ 1 then some (.coin ⟨p, h0, h1⟩) else none
    else none
  else
    .rational <$> parseRat s

private def withoutSemi (s : String) : Option String :=
  if s.endsWith ";" then some (s.dropEnd 1).toString else none

private def stripAffixes (pre post s : String) : Option String :=
  if s.startsWith pre && s.endsWith post then
    some ((s.drop pre.length).toString.dropEnd post.length).toString
  else
    none

private def dropChars (pre xs : List Char) : Option (List Char) :=
  if pre.isPrefixOf xs then some (xs.drop pre.length) else none

private partial def parseCChars (c : ℕ) :
    Nat → List Char → Option (CExpr c × List Char)
  | 0, _ => none
  | fuel + 1, xs =>
      if let some rest := dropChars "true".toList xs then
        some (.lit true, rest)
      else if let some rest := dropChars "false".toList xs then
        some (.lit false, rest)
      else if let some rest := dropChars "c[".toList xs then
        let digits := rest.takeWhile (· != ']')
        match rest.drop digits.length with
        | ']' :: tail => do
            let i ← parseCRef c ("c[" ++ String.ofList digits ++ "]")
            pure (.bit i, tail)
        | _ => none
      else if let some rest := dropChars "!(".toList xs then do
        let (e, tail) ← parseCChars c fuel rest
        let tail ← dropChars [')'] tail
        pure (.not e, tail)
      else if let some rest := dropChars ['('] xs then do
        let (lhs, tail) ← parseCChars c fuel rest
        let (op, tail) ←
          if let some r := dropChars " && ".toList tail then
            some (0, r)
          else if let some r := dropChars " || ".toList tail then
            some (1, r)
          else if let some r := dropChars " != ".toList tail then
            some (2, r)
          else none
        let (rhs, tail) ← parseCChars c fuel tail
        let tail ← dropChars [')'] tail
        let e := match op with
          | 0 => .and lhs rhs
          | 1 => .or lhs rhs
          | _ => .xor lhs rhs
        pure (e, tail)
      else none

/-- Parse exactly the fully parenthesized Boolean expression language emitted
by `CExpr.toOpenQASM`. -/
def parseCExpr (c : ℕ) (s : String) : Option (CExpr c) := do
  let (e, rest) ← parseCChars c (s.length + 1) s.toList
  if rest = [] then some e else none

private def parseRefs (q : ℕ) (s : String) : Option (List (Fin q)) :=
  if s = "" then some []
  else (s.splitOn ", ").mapM (parseQRef q)

/-- Parse one non-structured instruction in the interchange fragment. -/
def parseSimpleInstr (q c : ℕ) (line : String) : Option (Instr q c) := do
  let s ← withoutSemi line.trimAscii.toString
  match s.splitOn " " with
  | ["x", w] => return .gate (.x (← parseQRef q w))
  | ["h", w] => return .gate (.h (← parseQRef q w))
  | ["t", w] => return .gate (.t (← parseQRef q w))
  | ["reset", w] => return .reset (← parseQRef q w)
  | ["break"] => return .break
  | ["continue"] => return .continue
  | ["cx", control, target] =>
      if !control.endsWith "," then none
      else
        return .gate (.cx
          (← parseQRef q (control.dropEnd 1).toString)
          (← parseQRef q target))
  | [lhs, "=", "measure", rhs] =>
      return .measure (← parseQRef q rhs) (← parseCRef c lhs)
  | _ =>
      if s.startsWith "ry(" then
        match s.splitOn ") " with
        | [angle, w] =>
            return .gate (.ry
              (← parseAngle (angle.dropPrefix "ry(").toString)
              (← parseQRef q w))
        | _ => none
      else if s.startsWith "barrier " then
        return .barrier (← parseRefs q (s.drop 8).toString)
      else if s.startsWith "delay[" then
        match s.splitOn "] " with
        | [duration, refs] =>
            if !duration.endsWith "dt" then none
            else
              let n ← ((duration.drop 6).toString.dropEnd 2).toString.toNat?
              return .delay n (← parseRefs q refs)
        | _ => none
      else
        match s.splitOn " = " with
        | [lhs, rhs] =>
            return .store (← parseCRef c lhs) (← parseCExpr c rhs)
        | _ => none

private inductive ParsedInstr (q c : ℕ) where
  | instr : Instr q c → ParsedInstr q c
  | whileEnd : ParsedInstr q c
  | whileStep : Nat → CExpr c → List (Instr q c) → ParsedInstr q c

private def finishParsed {q c : ℕ} :
    List (ParsedInstr q c) → Option (List (Instr q c))
  | [] => some []
  | .instr i :: rest => return i :: (← finishParsed rest)
  | .whileStep fuel guard body :: rest =>
      return .whileLoop fuel guard body :: (← finishParsed rest)
  | .whileEnd :: _ => none

private def finishWhile {q c : ℕ} (guard : CExpr c)
    (body : List (ParsedInstr q c)) : Option (ParsedInstr q c) :=
  match body.reverse with
  | .whileEnd :: prefixLines =>
      return .whileStep 1 guard (← finishParsed prefixLines.reverse)
  | .whileStep fuel _ _ :: prefixLines =>
      return .whileStep (fuel + 1) guard (← finishParsed prefixLines.reverse)
  | _ => none

mutual

private partial def parseBlock (q c : ℕ) :
    List String → Option (List (ParsedInstr q c) × List String)
  | [] => some ([], [])
  | line :: rest =>
      if line = "" then
        parseBlock q c rest
      else if line = "}" || line = "} else {" then
        some ([], line :: rest)
      else do
        let (i, rest) ← parseStructuredInstr q c line rest
        let (is, rest) ← parseBlock q c rest
        pure (i :: is, rest)

private partial def parseCases (q c : ℕ) :
    List String → Option (List (Bool × List (Instr q c)) × List String)
  | [] => none
  | "" :: rest => parseCases q c rest
  | "}" :: rest => some ([], rest)
  | line :: rest => do
      let label ← stripAffixes "case " " {" line
      let value ← if label = "true" then some true
        else if label = "false" then some false else none
      let (body, rest) ← parseBlock q c rest
      let body ← finishParsed body
      let rest ← match rest with
        | "}" :: rest => some rest
        | _ => none
      let (cases, rest) ← parseCases q c rest
      pure ((value, body) :: cases, rest)

private partial def parseStructuredInstr (q c : ℕ)
    (line : String) (rest : List String) :
    Option (ParsedInstr q c × List String) :=
  if line = "// bounded while exhausted" then
    some (.whileEnd, rest)
  else if line = "// zero-iteration for loop" then
    some (.instr (.forLoop 0 []), rest)
  else if let some guardText := stripAffixes "if (" ") {" line then do
    let guard ← parseCExpr c guardText
    let (yes, rest) ← parseBlock q c rest
    match rest with
    | "} else {" :: rest => do
        let (no, rest) ← parseBlock q c rest
        let rest ← match rest with
          | "}" :: rest => some rest
          | _ => none
        pure (.instr (.ite guard (← finishParsed yes) (← finishParsed no)), rest)
    | "}" :: rest =>
        pure (← finishWhile guard yes, rest)
    | _ => none
  else if let some guardText := stripAffixes "switch (" ") {" line then do
    let guard ← parseCExpr c guardText
    let (cases, rest) ← parseCases q c rest
    pure (.instr (.switch guard cases), rest)
  else if let some last := stripAffixes "for uint _i in [0:" "] {" line then do
    let last ← last.toNat?
    let (body, rest) ← parseBlock q c rest
    let rest ← match rest with
      | "}" :: rest => some rest
      | _ => none
    pure (.instr (.forLoop (last + 1) (← finishParsed body)), rest)
  else if let some label := stripAffixes "box { // " "" line then do
    let (body, rest) ← parseBlock q c rest
    let rest ← match rest with
      | "}" :: rest => some rest
      | _ => none
    pure (.instr (.box label (← finishParsed body)), rest)
  else
    return (.instr (← parseSimpleInstr q c line), rest)

end

private def parseCandidate (q c : ℕ) (text : String) :
    Option (Program .openQASM3_0_ibmComposer_2026_09 q c) :=
  match text.splitOn "\n" with
  | version :: includeLine :: qdecl :: cdecl :: body =>
      if version = "OPENQASM 3.0;" ∧
          includeLine = "include \"stdgates.inc\";" ∧
          qdecl = "qubit[" ++ toString q ++ "] q;" ∧
          cdecl = "bit[" ++ toString c ++ "] c;" then do
        let (instructions, rest) ← parseBlock q c body
        if rest ≠ [] then none
        let instructions ← finishParsed instructions
        pure ⟨instructions⟩
      else none
  | _ => none

private def acceptRendered {q c : ℕ} (text : String)
    (P : Program .openQASM3_0_ibmComposer_2026_09 q c) :
    Option (Program .openQASM3_0_ibmComposer_2026_09 q c) :=
  if P.renderOpenQASM = text then some P else none

private theorem acceptRendered_sound {q c : ℕ} {text : String}
    {P P' : Program .openQASM3_0_ibmComposer_2026_09 q c}
    (h : acceptRendered text P = some P') :
    P'.renderOpenQASM = text := by
  unfold acceptRendered at h
  split at h <;> simp_all

/-- Parse the complete, structured, canonical interchange grammar documented
at the top of this module. -/
def parseStructuredProgram (q c : ℕ) (text : String) :
    Option (Program .openQASM3_0_ibmComposer_2026_09 q c) :=
  match parseCandidate q c text with
  | none => none
  | some P => acceptRendered text P

/-- Exact AST boundary for two-sided render/parse round trips.  In particular,
it excludes information erased by zero-count loops and any label containing a
newline. -/
def Program.ParserCanonical {q c : ℕ}
    (P : Program .openQASM3_0_ibmComposer_2026_09 q c) : Prop :=
  parseStructuredProgram q c P.renderOpenQASM = some P

/-- Exact accepted textual language.  This operational definition supplements
the grammar above by requiring canonical rendering byte-for-byte. -/
def SupportedOpenQASMText (q c : ℕ) (text : String) : Prop :=
  ∃ P, parseStructuredProgram q c text = some P

/-- Every accepted structured program renders back byte-for-byte. -/
theorem parseStructuredProgram_render_roundTrip {q c : ℕ} {text : String}
    {P : Program .openQASM3_0_ibmComposer_2026_09 q c}
    (h : parseStructuredProgram q c text = some P) :
    P.renderOpenQASM = text := by
  unfold parseStructuredProgram at h
  generalize hc : parseCandidate q c text = candidate at h
  cases candidate with
  | none => simp at h
  | some candidate =>
      exact acceptRendered_sound h

/-- On the exact canonical AST subset, parsing after rendering is identity. -/
theorem Program.parse_render_roundTrip {q c : ℕ}
    (P : Program .openQASM3_0_ibmComposer_2026_09 q c)
    (h : P.ParserCanonical) :
    parseStructuredProgram q c P.renderOpenQASM = some P :=
  h

/-- The public well-formed renderer also round-trips byte-for-byte after any
successful parse. -/
theorem parseStructuredProgram_toOpenQASM_roundTrip {q c : ℕ} {text : String}
    {P : Program .openQASM3_0_ibmComposer_2026_09 q c}
    (hP : P.WellFormed)
    (h : parseStructuredProgram q c text = some P) :
    P.toOpenQASM hP = text := by
  simpa [Program.toOpenQASM] using
    (parseStructuredProgram_render_roundTrip h)

/-- Backwards-compatible name for parsing one flat instruction. -/
abbrev parseFlatInstr := parseSimpleInstr

/-- Backwards-compatible entry point; it now accepts the structured grammar. -/
abbrev parseFlatProgram := parseStructuredProgram

end QLambda.Composer
