"""Mathematical vocabulary for turning QLambda Lean identifiers into English.

Used by generate_blueprint_cards.py.  Three layers:

* IDENT  – whole identifiers (exact or lower-first) → noun phrase;
* WORD   – camelCase pieces → words (fallback when IDENT misses);
* TYPE_NS – namespaces that name a mathematical kind of object, with
  singular / plural nouns, used as the subject of lemma titles.

Everything here is prose; nothing may contain Lean syntax.
"""

from __future__ import annotations

# Namespaces that only organise files; they never become subjects.
MODULE_NS = {
    "QLambda", "Linear", "Domain", "Presheaf", "Composer", "CQ",
    "SuperoperatorModule", "SigmaMon", "GeneralQuotation", "Fixtures",
    "Palomar", "Compiler", "HardwareChannel", "Source", "Examples",
    "Metatheory", "Mathlib", "_root_",
}

# Namespace → (singular, plural) for the mathematical kind it names.
TYPE_NS: dict[str, tuple[str, str]] = {
    "OSplit": ("ordered context split", "ordered context splits"),
    "AllNone": ("empty usage mask", "empty usage masks"),
    "OnlySomeAt": ("single-cell usage mask", "single-cell usage masks"),
    "Lookup": ("context lookup", "context lookups"),
    "InsertAt": ("cell insertion", "cell insertions"),
    "DropLin": ("linear-cell deletion", "linear-cell deletions"),
    "LinSubCtx": ("linear substitution context", "linear substitution contexts"),
    "UnresSubCtx": ("unrestricted substitution context", "unrestricted substitution contexts"),
    "HasType": ("typing derivation", "typing derivations"),
    "Step": ("reduction step", "reduction steps"),
    "Term": ("term", "terms"),
    "Ty": ("type", "types"),
    "Prim": ("primitive", "primitives"),
    "Command": ("circuit command", "circuit commands"),
    "Quotation": ("quotation", "quotations"),
    "Quotable": ("quotable command", "quotable commands"),
    "FragCert": ("fragment certificate", "fragment certificates"),
    "FragmentBinders": ("fragment binder", "fragment binders"),
    "FragmentArrowDomains": ("fragment arrow domain", "fragment arrow domains"),
    "FragmentContext": ("context interpretation", "context interpretations"),
    "SemanticFragment": ("semantic fragment", "semantic fragments"),
    "ClosedSemanticFragment": ("closed semantic fragment", "closed semantic fragments"),
    "FirstOrder": ("first-order type", "first-order types"),
    "CtxLAllSomeFragment": ("fully occupied fragment linear context", "fully occupied fragment linear contexts"),
    "CtxUAllBit": ("all-bit unrestricted context", "all-bit unrestricted contexts"),
    "CtxUAllFragment": ("all-fragment unrestricted context", "all-fragment unrestricted contexts"),
    "ContextObject": ("context object", "context objects"),
    "UsesAtMostQubits": ("qubit-usage bound", "qubit-usage bounds"),
    "RuntimeUsesAtMost": ("runtime qubit-usage bound", "runtime qubit-usage bounds"),
    "StagedValue": ("staged value", "staged values"),
    "StageResult": ("staging result", "staging results"),
    "Runtime": ("runtime", "runtimes"),
    "RegisterState": ("register state", "register states"),
    "RegFile": ("register file", "register files"),
    "Config": ("runtime configuration", "runtime configurations"),
    "Value": ("runtime value", "runtime values"),
    "Control": ("control state", "control states"),
    "Superoperator": ("superoperator", "superoperators"),
    "CPMap": ("completely positive map", "completely positive maps"),
    "KrausFamily": ("Kraus family", "Kraus families"),
    "CompletedCP": ("completed CP class", "completed CP classes"),
    "Instrument": ("quantum instrument", "quantum instruments"),
    "QuantumInstrument": ("quantum instrument", "quantum instruments"),
    "QuantumOperation": ("quantum operation", "quantum operations"),
    "FiniteInstrumentComp": ("finite instrument computation", "finite instrument computations"),
    "CompEq": ("observational equality", "observational equalities"),
    "Eq": ("semantic equality of circuits", "semantic equalities of circuits"),
    "NormalizedDensity": ("normalized density matrix", "normalized density matrices"),
    "SubNormalizedDensity": ("subnormalized density matrix", "subnormalized density matrices"),
    "Qubit": ("qubit", "qubits"),
    "QuantumRel": ("quantum relation", "quantum relations"),
    "IsFunction": ("functional quantum relation", "functional quantum relations"),
    "QuantumSet": ("quantum set", "quantum sets"),
    "QuantumFunction": ("quantum function", "quantum functions"),
    "QuantumPoset": ("quantum poset", "quantum posets"),
    "QuantumCPO": ("quantum CPO", "quantum CPOs"),
    "ScottFunction": ("Scott-continuous function", "Scott-continuous functions"),
    "Limits": ("limit", "limits"),
    "QObj": ("quantum object", "quantum objects"),
    "SetHom": ("set map", "set maps"),
    "OmegaMap": ("ω-continuous map", "ω-continuous maps"),
    "OmegaComplete": ("ω-complete order", "ω-complete orders"),
    "OmegaCategory": ("ω-enriched category", "ω-enriched categories"),
    "OmegaObject": ("ω-complete object", "ω-complete objects"),
    "Pointed": ("pointed ω-complete order", "pointed ω-complete orders"),
    "ClosedStructure": ("closed structure", "closed structures"),
    "FunctionSpace": ("function space", "function spaces"),
    "ProjectionChain": ("projection chain", "projection chains"),
    "CircuitEmbedding": ("circuit embedding", "circuit embeddings"),
    "Module": ("superoperator module", "superoperator modules"),
    "Hom": ("module morphism", "module morphisms"),
    "Iso": ("module isomorphism", "module isomorphisms"),
    "Fiber": ("fiber", "fibers"),
    "HasSumAdd": ("additive summability", "additive summability"),
    "Bilinear": ("bilinear map", "bilinear maps"),
    "DayTensor": ("Day tensor product", "Day tensor products"),
    "DayCoend": ("Day coend", "Day coends"),
    "Raw": ("raw Day coend expression", "raw Day coend expressions"),
    "DayNegation": ("Day negation", "Day negations"),
    "DayInternalHom": ("Day internal hom", "Day internal homs"),
    "NegationData": ("negation datum", "negation data"),
    "ClassicalObject": ("classical object", "classical objects"),
    "CanonicalReflexivity": ("canonical reflexivity witness", "canonical reflexivity witnesses"),
    "PseudoBasis": ("pseudo-basis", "pseudo-bases"),
    "PseudoRepresentable": ("pseudo-representable module", "pseudo-representable modules"),
    "AdmissibleMatrix": ("admissible matrix", "admissible matrices"),
    "Basis": ("basis", "bases"),
    "ComonoidHom": ("comonoid morphism", "comonoid morphisms"),
    "SymmetricElement": ("symmetric tensor", "symmetric tensors"),
    "SymmetricEquivalenceComonoidHom": ("symmetric-equivalence comonoid morphism", "symmetric-equivalence comonoid morphisms"),
    "ClosedCoefficient": ("closed coefficient", "closed coefficients"),
    "HasActSumFromDim": ("dimension-indexed action sum", "dimension-indexed action sums"),
    "PosSemidef": ("positive semidefinite matrix", "positive semidefinite matrices"),
    "ChoiSum": ("countable Choi sum", "countable Choi sums"),
    "FiniteSupport": ("finitely supported sum", "finitely supported sums"),
    "CPMapSum": ("countable sum of CP maps", "countable sums of CP maps"),
    "Gate": ("gate", "gates"),
    "Probability": ("outcome probability", "outcome probabilities"),
    "CExpr": ("classical expression", "classical expressions"),
    "AngleExpr": ("angle expression", "angle expressions"),
    "Program": ("OpenQASM program", "OpenQASM programs"),
}

# Whole identifiers (matched exactly, then with the first letter lowered).
IDENT: dict[str, str] = {
    # linear contexts and typing
    "OSplit": "ordered context split",
    "oSplit": "ordered context split",
    "AllNone": "empty usage mask",
    "allNone": "empty usage mask",
    "OnlySomeAt": "single-cell usage mask",
    "onlySomeAt": "single-cell usage mask",
    "Lookup": "context lookup",
    "lookup": "context lookup",
    "lookupTarget": "lookup of the substituted variable",
    "noLookupSome": "absence of a lookup hit",
    "noLookupTarget": "absence of the substituted variable",
    "HasType": "typing judgement",
    "hasType": "typing judgement",
    "typed": "well-typedness",
    "typing": "typing",
    "infer": "type inference",
    "Step": "one-step reduction",
    "step": "one-step reduction",
    "MakesProgress": "progress property",
    "usage": "usage mask",
    "usageCtx": "usage context",
    "mask": "usage mask",
    "mark": "single-use mark",
    "unused": "unused context",
    "ctxL": "linear context",
    "ctxU": "unrestricted context",
    "withNoneRight": "split with an empty right part",
    "insertNone": "insertion of an absent cell",
    "InsertAt": "cell insertion",
    "insertAt": "cell insertion",
    "DropLin": "deletion of a linear cell",
    "weakenLinNone": "weakening by an absent linear cell",
    "weakenUnres": "unrestricted weakening",
    "weakening": "weakening",
    "shiftLin": "linear de Bruijn shift",
    "shiftUnres": "unrestricted de Bruijn shift",
    "shiftForward": "forward index shift",
    "shiftBackward": "backward index shift",
    "subst": "substitution",
    "substLin": "linear substitution",
    "substUnres": "unrestricted substitution",
    "LinSubCtx": "linear substitution context",
    "UnresSubCtx": "unrestricted substitution context",
    "noLin": "absence of free linear variables",
    "linearOSplit": "Day split induced by an ordered context split",
    "linearOSplitLists": "Day split on the underlying lists",
    "combinedOSplit": "combined Day split of both contexts",
    "combinedOSplitLists": "combined Day split on the underlying lists",
    "liftLin": "linear lifting",
    "liftUnres": "unrestricted lifting",
    "CtxLAllSomeFragment": "fully occupied fragment linear context",
    "CtxUAllBit": "all-bit unrestricted context",
    "CtxUAllFragment": "all-fragment unrestricted context",
    "envTys": "environment types",
    # terms
    "var": "variable",
    "varL": "linear variable",
    "varU": "unrestricted variable",
    "varLin": "linear variable",
    "varL0": "linear variable at index zero",
    "varU0": "unrestricted variable at index zero",
    "lam": "lambda abstraction",
    "lamL": "linear lambda abstraction",
    "lamU": "unrestricted lambda abstraction",
    "lamLin": "linear lambda abstraction",
    "lamUnres": "unrestricted lambda abstraction",
    "app": "application",
    "appL": "linear application",
    "appU": "unrestricted application",
    "pair": "pair",
    "unpair": "pair elimination",
    "ite": "conditional",
    "iteTrue": "true branch of a conditional",
    "iteFalse": "false branch of a conditional",
    "cond": "condition",
    "fn": "function part",
    "arg": "argument",
    "bitLit": "bit literal",
    "bit": "bit",
    "unit": "unit",
    "prim": "primitive",
    "Prim": "primitive",
    "beta": "β-reduction",
    "betaL": "linear β-reduction",
    "betaU": "unrestricted β-reduction",
    "eta": "η-expansion",
    "value": "value",
    "closed": "closed term",
    "Term": "term",
    "Ty": "type",
    "arrow": "function type",
    "tensor": "tensor product",
    "SemanticFragment": "semantic fragment",
    "semanticFragment": "semantic-fragment membership",
    "semanticFragmentB": "Boolean semantic-fragment check",
    "ClosedSemanticFragment": "closed semantic fragment",
    "FirstOrder": "first-order type",
    "firstOrder": "first-order type",
    "firstOrderB": "Boolean first-order check",
    "wellFormedB": "Boolean well-formedness check",
    "wellFormed": "well-formedness",
    "WellFormed": "well-formedness",
    "admissible": "admissibility",
    "Admissible": "admissibility",
    "admissibleAt": "admissibility at a position",
    "positiveRec": "positivity of recursion",
    "strictlyPositiveAt": "strict positivity",
    "StrictlyPositiveAt": "strict positivity",
    "wellScopedAt": "well-scopedness",
    "doesNotContainAt": "absence of the recursion variable",
    "duplicable": "duplicability",
    "duplicableAt": "duplicability at a position",
    "recursionFree": "recursion freedom",
    "negativeRecursiveTy": "negative recursive type",
    "recursiveIdTy": "recursive identity type",
    "recursiveFoldUnfold": "fold/unfold of a recursive type",
    "FragCert": "fragment certificate",
    "fragCert": "fragment certificate",
    "ofFragCert": "passage from a fragment certificate",
    "fragmentJudgment": "fragment typing judgement",
    "toFragmentJudgment": "passage to a fragment typing judgement",
    "ofFragmentJudgment": "passage from a fragment typing judgement",
    "toHasType": "passage to a typing judgement",
    "ofHasType": "passage from a typing judgement",
    "FragmentContext": "context interpretation",
    "fragmentModule": "fragment module",
    "fragmentBinders": "fragment binders",
    "fragmentWeightedSimulation": "weighted fragment simulation",
    "routeA": "route-A fragment model",
    "routeAFragmentModel": "route-A fragment model",
    "primMap": "primitive interpretation",
    "primTy": "primitive type",
    "operationalDenote": "operational meaning",
    "operationalSetoid": "operational equivalence",
    # quantum commands / circuits
    "Command": "circuit command",
    "command": "circuit command",
    "Quotable": "quotability",
    "quotable": "quotability",
    "quote": "quotation",
    "quoteBody": "quoted body",
    "quoteCExpr": "quotation of a classical expression",
    "quoteGateSpine": "quoted gate spine",
    "quoteSkipSpine": "quoted skip spine",
    "quotationTy": "quotation type",
    "generalQuotationTy": "general quotation type",
    "interpret": "interpretation",
    "interpretQuoteHom": "interpretation of a quoted morphism",
    "interpretQuoteSpine": "interpretation of a quoted spine",
    "interpretSkipSpine": "interpretation of the skip spine",
    "ContinuationTyped": "well-typed continuation",
    "gateSpine": "gate spine",
    "gateBlock": "gate block",
    "resetBlock": "reset block",
    "measureBlock": "measurement block",
    "denoteBlock": "denotation of a block",
    "denoteFlow": "denotation of a control-flow program",
    "denoteFlowBlock": "denotation of a control-flow block",
    "FlowSem": "control-flow semantics",
    "FlowStore": "control-flow store",
    "flowSeq": "sequential control flow",
    "flowSkip": "empty control flow",
    "flowSelect": "control-flow selection",
    "blockWellFormed": "block well-formedness",
    "joinCommands": "concatenation of commands",
    "commandAsProgram": "command viewed as a program",
    "commandToOpenQASM": "OpenQASM rendering of a command",
    "toOpenQASM": "OpenQASM rendering",
    "openQASM": "OpenQASM",
    "openqasm": "OpenQASM rendering",
    "nQubitOpenQASMVersion": "n-qubit OpenQASM header",
    "elaborateCommand": "command elaboration",
    "elaborates": "successful elaboration",
    "elaboration": "elaboration",
    "elab": "elaboration",
    "compile": "compilation",
    "canonicalModel": "canonical matrix model",
    "Model": "matrix model",
    "parse": "parsing",
    "render": "rendering",
    "roundTrip": "render/parse round trip",
    "roundtrip": "render/parse round trip",
    "acceptRendered": "acceptance of rendered output",
    "ParserCanonical": "parser-canonical program",
    "stripAffixes": "removal of affixes",
    "andThen": "sequential composition",
    "usesAtMost": "qubit-usage bound",
    "UsesAtMostQubits": "qubit-usage bound",
    "assembleAtoms": "assembly from atoms",
    "seq": "sequential composition",
    "zipOr": "pointwise merge of two usage masks",
    "mu": "recursive type",
    "nostep": "absence of a reduction step",
    "scoped": "well-scopedness",
    "after": "cutoff",
    "get?": "successful lookup",
    "unfold": "unfolding",
    "allFalse": "all-false mask",
    "copyIdx": "copy index",
    "psi": "Ψ map",
    "Psi": "Ψ map",
    "reflect": "reflection",
    "pre": "pre-composite",
    "comma": "comma-separated rendering",
    # gates and matrices
    "new0": "fresh zero-qubit allocation",
    "new1": "fresh one-qubit allocation",
    "x": "Pauli-X gate",
    "h": "Hadamard gate",
    "t": "T gate",
    "cx": "controlled-NOT gate",
    "ry": "Y-rotation gate",
    "reset": "reset",
    "measure": "measurement",
    "measureX": "X-basis measurement",
    "measureRegister": "register measurement",
    "measureBranch": "measurement branch",
    "measureProbability": "measurement probability",
    "measured": "measured",
    "measurement": "measurement",
    "meas": "measurement",
    "measStep": "measurement step",
    "hMatrix": "Hadamard matrix",
    "xMatrix": "Pauli-X matrix",
    "tMatrix": "T-gate matrix",
    "cxMatrix": "controlled-NOT matrix",
    "ryMatrix": "Y-rotation matrix",
    "tPhase": "T-gate phase",
    "pauliX": "Pauli-X matrix",
    "projector": "computational-basis projector",
    "proj0": "projector onto zero",
    "proj1": "projector onto one",
    "cosHalf": "cosine of the half angle",
    "sinHalf": "sine of the half angle",
    "sqrtTwoHalf": "value one over the square root of two",
    "ketZero": "zero ket",
    "registerKetZero": "all-zero register ket",
    "basisKet": "basis ket",
    "basisBra": "basis bra",
    "prepBra": "preparation bra",
    "allocZeroMatrix": "zero-qubit allocation matrix",
    "allocateZero": "allocation of a fresh zero qubit",
    "allocQ": "qubit allocation",
    "allocC": "classical-bit allocation",
    "resetKraus": "Kraus operators of reset",
    "QubitMatrix": "single-qubit matrix",
    "bell": "Bell-state program",
    "bellProgram": "Bell-state program",
    "cxRegister": "controlled-NOT on a register",
    "qubitRegisterTy": "qubit-register type",
    "dynamicX": "dynamically controlled X gate",
    "applyGate": "gate application",
    "onWire": "action on a single wire",
    "onWires": "action on a pair of wires",
    "wire": "wire",
    "idGate": "identity gate",
    "idQ": "identity on a qubit",
    # quantum operations
    "Superoperator": "superoperator",
    "superoperator": "superoperator",
    "CPMap": "completely positive map",
    "cpMap": "completely positive map",
    "cp": "underlying completely positive map",
    "completedCP": "completed CP class",
    "CompletedCP": "completed CP class",
    "KrausFamily": "Kraus family",
    "krausFamily": "Kraus family",
    "kraus": "Kraus operators",
    "ofKraus": "map determined by a Kraus family",
    "toKraus": "Kraus presentation",
    "ofUnitary": "map induced by a unitary",
    "ofIsometry": "map induced by an isometry",
    "ofEquivalence": "map induced by an index equivalence",
    "ofEquiv": "map induced by an index equivalence",
    "ofEffect": "map determined by an effect",
    "ofReal": "real embedding",
    "ofLE": "map dominated by a given bound",
    "ofQuantumOperation": "superoperator of a quantum operation",
    "ofQuantumInstrument": "instrument of a quantum instrument",
    "ofOperation": "map of an operation",
    "ofCompleted": "passage from a completed class",
    "toCompleted": "passage to the completed class",
    "applyMat": "action on a matrix",
    "apply": "application",
    "choi": "Choi matrix",
    "choiIdentity": "Choi matrix of the identity",
    "choiSemEq": "Choi-matrix semantic equality",
    "choiRefines": "Choi-order refinement",
    "choiTerm": "Choi term",
    "effect": "effect",
    "effectExpectation": "effect expectation",
    "effectPairingPolar": "polarised effect pairing",
    "effectPairingQuad": "quadratic effect pairing",
    "effectPrecompose": "precomposition with an effect",
    "trace": "trace",
    "traceNonincreasing": "trace non-increase",
    "tni": "trace non-increasing",
    "semEq": "semantic equality",
    "SemEq": "semantic equality",
    "ApplySemEq": "semantic equality of applications",
    "residualRefines": "residual refinement",
    "ResidualRefines": "residual refinement",
    "wpKraus": "Kraus weakest precondition",
    "identity": "identity",
    "comp": "composition",
    "postcomp": "postcomposition",
    "precomp": "precomposition",
    "dagger": "adjoint",
    "conjTranspose": "conjugate transpose",
    "isometry": "isometry property",
    "unitary": "unitarity",
    "posSemidef": "positive semidefiniteness",
    "PosSemidef": "positive semidefiniteness",
    "isHermitian": "self-adjointness",
    "normSq": "squared norm",
    "vecMulVec": "outer product",
    "dotProduct": "dot product",
    "kronecker": "Kronecker product",
    "reindex": "reindexing",
    "tensorPowerDimension": "dimension of a tensor power",
    "tensorPowerMap": "tensor-power map",
    "QDim": "Hilbert-space dimension",
    "CStore": "classical bit store",
    "density": "density matrix",
    "mat": "underlying matrix",
    "born": "Born rule",
    "bornScalar": "Born-rule scalar",
    "bornWeight": "Born-rule weight",
    "spectralScale": "spectral scaling",
    "spectralErode": "spectral erosion",
    "Instrument": "quantum instrument",
    "instrument": "quantum instrument",
    "branch": "branch",
    "outcome": "outcome",
    "Outcome": "outcome",
    "bind": "sequential composition",
    "FiniteInstrumentComp": "finite instrument computation",
    "CompEq": "observational equality",
    "Sem": "classical–quantum meaning",
    # quantum relations / sets / orders
    "QuantumRel": "quantum relation",
    "QuantumSet": "quantum set",
    "liftSet": "quantum set of a classical set",
    "atomic": "atomic quantum set",
    "restrictAtom": "restriction to an atom",
    "component": "component",
    "graph": "graph",
    "IsFunction": "functionality",
    "isFunction": "functionality",
    "opTensor": "tensor of opposite components",
    "internalHom": "internal hom",
    "curry": "currying",
    "uncurry": "uncurrying",
    "ScottFunction": "Scott-continuous function",
    "omegaSup": "supremum of an ω-chain",
    "ωSup": "supremum of an ω-chain",
    "iSup": "indexed supremum",
    "iInf": "indexed infimum",
    "sSup": "supremum",
    "sInf": "infimum",
    "isLUB": "least-upper-bound property",
    "isGLB": "greatest-lower-bound property",
    "OmegaComplete": "ω-completeness",
    "omegaComplete": "ω-completeness",
    "OmegaMap": "ω-continuous map",
    "iterateBot": "iteration from the bottom element",
    "fix": "least fixed point",
    "paramFix": "parametrised least fixed point",
    "top": "top element",
    "bot": "bottom element",
    "SetHom": "set map",
    "QObj": "quantum object",
    # Day convolution / presheaf modules
    "Module": "superoperator module",
    "Hom": "module morphism",
    "Bilinear": "bilinear map",
    "dayTensor": "Day tensor product",
    "DayTensor": "Day tensor product",
    "dayTensorUnit": "Day tensor unit",
    "DayCoend": "Day coend",
    "dayCurry": "Day currying",
    "dayUncurry": "Day uncurrying",
    "dayEval": "Day evaluation",
    "dayBraiding": "Day braiding",
    "dayClosed": "Day closed structure",
    "dayLeftUnitor": "Day left unitor",
    "dayRightUnitor": "Day right unitor",
    "dayAssociatorInv": "inverse Day associator",
    "DayNegation": "Day negation",
    "neg": "negation",
    "representable": "representable module",
    "yoneda": "Yoneda correspondence",
    "yonedaMap": "Yoneda image",
    "yonedaEquiv": "Yoneda equivalence",
    "bang": "exponential modality",
    "bangComult": "comultiplication of the exponential",
    "bangCounit": "counit of the exponential",
    "bangComonoid": "exponential comonoid",
    "bangDereliction": "dereliction",
    "bangPromote": "promotion",
    "bangMap": "action of the exponential on morphisms",
    "comult": "comultiplication",
    "counit": "counit",
    "comonoid": "comonoid",
    "Comonoid": "comonoid",
    "ComonoidHom": "comonoid morphism",
    "coassoc": "coassociativity",
    "coassociative": "coassociativity",
    "cocommutative": "cocommutativity",
    "counital": "counitality",
    "dereliction": "dereliction",
    "promotion": "promotion",
    "promote": "promotion",
    "leftUnitor": "left unitor",
    "rightUnitor": "right unitor",
    "leftUnitorInv": "inverse left unitor",
    "rightUnitorInv": "inverse right unitor",
    "associator": "associator",
    "associatorInv": "inverse associator",
    "braiding": "braiding",
    "tensorAssociator": "tensor associator",
    "tensorAssociatorInv": "inverse tensor associator",
    "tensorLeftUnitor": "tensor left unitor",
    "tensorLeftUnitorInv": "inverse tensor left unitor",
    "tensorRightUnitor": "tensor right unitor",
    "tensorRightUnitorInv": "inverse tensor right unitor",
    "tensorSwap": "tensor swap",
    "doubleDual": "double dual",
    "additiveProduct": "additive product",
    "additivePair": "additive pairing",
    "additiveFst": "first additive projection",
    "additiveSnd": "second additive projection",
    "symmetricFormalPowerSeries": "symmetric formal power series",
    "symmetricElement": "symmetric tensor",
    "SymmetricElement": "symmetric tensor",
    "classicalObject": "classical object",
    "ClassicalObject": "classical object",
    "fiber": "fiber",
    "Fiber": "fiber",
    "hasSum": "summability",
    "HasSum": "summability",
    "sum": "sum",
    "cpmModule": "CP-map module",
    "zeroModule": "zero module",
    "presheafQuantumLNL": "presheaf linear/non-linear model",
    "ChoiSum": "countable Choi sum",
    # generic operations (as nouns)
    "zero": "zero",
    "one": "one",
    "add": "addition",
    "sub": "subtraction",
    "mul": "multiplication",
    "smul": "scalar multiplication",
    "nsmul": "natural-number scalar multiplication",
    "nnsmul": "nonnegative scalar multiplication",
    "zsmul": "integer scalar multiplication",
    "qsmul": "rational scalar multiplication",
    "pow": "power",
    "inv": "inverse",
    "star": "adjoint",
    "conj": "complex conjugate",
    "re": "real part",
    "im": "imaginary part",
    "norm": "norm",
    "abs": "absolute value",
    "sq": "square",
    "sqrt": "square root",
    "nil": "empty list",
    "cons": "extended list",
    "append": "concatenation",
    "length": "length",
    "lengths": "lengths",
    "replicate": "constant list",
    "map": "functorial action",
    "flatMap": "flat map",
    "id": "identity",
    "swap": "swap",
    "fst": "first projection",
    "snd": "second projection",
    "inl": "left injection",
    "inr": "right injection",
    "cast": "transport along an equality",
    "ext": "extensionality",
    "mem": "membership",
    "mono": "monotonicity",
    "monotone": "monotonicity",
    "injective": "injectivity",
    "surjective": "surjectivity",
    "symm": "symmetry",
    "refl": "reflexivity",
    "trans": "transitivity",
    "assoc": "associativity",
    "comm": "commutativity",
    "congr": "congruence",
    "congruence": "congruence",
    "natural": "naturality",
    "naturality": "naturality",
    "unique": "uniqueness",
    "nonneg": "nonnegativity",
    "pos": "positivity",
    "sound": "soundness",
    "complete": "completeness",
    "completeness": "completeness",
    "adequacy": "adequacy",
    "deterministic": "determinism",
    "progress": "progress",
    "preservation": "type preservation",
    "denote": "denotation",
    "denotation": "denotation",
    "eval": "evaluation",
    "evaluate": "evaluation",
    "exists": "existence",
    "total": "totality",
    "bounds": "bounds",
    "dim": "dimension",
    "card": "cardinality",
    "diag": "diagonal",
    "single": "single-entry element",
    "singleton": "singleton",
    "finset": "finite-set sum",
    "tendsto": "limit",
    "tends": "convergence",
    "summable": "summability",
    "fixture": "test fixture",
    "test": "test",
    "spec": "specification",
}

# camelCase pieces → words.  Only used when IDENT misses a whole identifier.
WORD: dict[str, str] = {
    "cp": "CP", "cpm": "CP-map", "tni": "trace non-increasing",
    "osplit": "ordered context split", "ctx": "context", "ctxl": "linear context",
    "ctxu": "unrestricted context", "lin": "linear", "unres": "unrestricted",
    "l": "linear", "u": "unrestricted", "b": "Boolean", "q": "quantum",
    "c": "classical", "rep": "representable", "so": "superoperator",
    "mat": "matrix", "vec": "vector", "sem": "semantic", "eq": "equality",
    "le": "order", "lt": "strict order", "iff": "equivalence", "inv": "inverse",
    "id": "identity", "comp": "composite", "hom": "morphism", "iso": "isomorphism",
    "equiv": "equivalence", "day": "Day", "bang": "exponential",
    "comult": "comultiplication", "counit": "counit", "coassoc": "coassociativity",
    "cofree": "cofree", "choi": "Choi", "kraus": "Kraus", "born": "Born",
    "qasm": "QASM", "openqasm": "OpenQASM", "yoneda": "Yoneda",
    "omega": "ω", "sup": "supremum", "inf": "infimum", "lub": "least upper bound",
    "glb": "greatest lower bound", "psd": "positive semidefinite",
    "frag": "fragment", "cert": "certificate", "elab": "elaboration",
    "quote": "quotation", "subst": "substitution", "prim": "primitive",
    "ite": "conditional", "lam": "lambda", "app": "application", "var": "variable",
    "ty": "type", "tys": "types", "cx": "controlled-NOT", "ry": "Y-rotation",
    "alloc": "allocation", "meas": "measurement", "prep": "preparation",
    "reg": "register", "cq": "classical–quantum", "qrel": "quantum relation",
    "dual": "dual", "neg": "negation", "coeff": "coefficient", "ket": "ket",
    "bra": "bra", "smul": "scalar multiplication", "nnsmul": "nonnegative scalar multiplication",
    "fst": "first", "snd": "second", "proj": "projection", "fin": "finite index",
    "nat": "natural-number", "real": "real", "complex": "complex",
    "sq": "square", "sqrt": "square root", "norm": "norm", "abs": "absolute value",
    "min": "minimum", "max": "maximum", "succ": "successor", "pred": "predecessor",
    "fwd": "forward", "bwd": "backward", "aux": "auxiliary", "wp": "weakest precondition",
    "tpd": "trace-preserving", "lnl": "linear/non-linear", "nq": "n-qubit",
    "ok": "success", "b0": "bit zero", "w0": "wire zero", "e0": "basis vector zero",
    "e1": "basis vector one", "p0": "outcome zero", "p1": "outcome one",
    "mk": "construction", "zipor": "pointwise disjunction",
    "app": "component", "elim": "elimination", "representable": "representable",
    "intro": "introduction", "ctor": "constructor", "cont": "continuation",
}

# Suffix atoms of lemma names → how the title reads (P = subject noun phrase).
# "{S}" is the subject, "{s}" the lower-case subject.
PROPERTY_SUFFIX: dict[str, str] = {
    "mono": "Monotonicity of {s}",
    "monotone": "Monotonicity of {s}",
    "injective": "Injectivity of {s}",
    "surjective": "Surjectivity of {s}",
    "nonneg": "Nonnegativity of {s}",
    "pos": "Positivity of {s}",
    "posSemidef": "Positive semidefiniteness of {s}",
    "psd": "Positive semidefiniteness of {s}",
    "isHermitian": "Self-adjointness of {s}",
    "isometry": "{S} is an isometry",
    "unitary": "{S} is unitary",
    "sound": "Soundness of {s}",
    "soundness": "Soundness of {s}",
    "complete": "Completeness of {s}",
    "completeness": "Completeness of {s}",
    "adequacy": "Adequacy of {s}",
    "deterministic": "Determinism of {s}",
    "progress": "Progress for {s}",
    "preservation": "Preservation of typing under {s}",
    "unique": "Uniqueness of {s}",
    "ext": "Extensionality for {s}",
    "symm": "Symmetry of {s}",
    "refl": "Reflexivity of {s}",
    "trans": "Transitivity of {s}",
    "assoc": "Associativity of {s}",
    "comm": "Commutativity of {s}",
    "natural": "Naturality of {s}",
    "naturality": "Naturality of {s}",
    "congr": "Congruence property of {s}",
    "congruence": "Congruence property of {s}",
    "typed": "{S} is well typed",
    "hasType": "Typing of {s}",
    "infer": "Type inference for {s}",
    "admissible": "Admissibility of {s}",
    "wellFormed": "Well-formedness of {s}",
    "exists": "Existence of {s}",
    "total": "Totality of {s}",
    "bounds": "Bounds for {s}",
    "denote": "Denotation of {s}",
    "denotation": "Denotation of {s}",
    "canonical": "{S} agrees with the canonical matrix model",
    "coassociative": "Coassociativity of {s}",
    "coassoc": "Coassociativity of {s}",
    "cocommutative": "Cocommutativity of {s}",
    "counital": "Counitality of {s}",
    "idempotent": "Idempotence of {s}",
    "involutive": "{S} is an involution",
    "continuous": "Continuity of {s}",
    "summable": "Summability of {s}",
    "hasSum": "Summability of {s}",
    "finite": "Finiteness of {s}",
    "nonempty": "Nonemptiness of {s}",
    "subsingleton": "{S} has at most one element",
    "rejected": "{S} is rejected",
    "succeeds": "{S} succeeds",
    "fails": "{S} fails",
    "safety": "Safety of {s}",
    "test": "Worked check of {s}",
    "fixture": "Worked check of {s}",
    "spec": "Specification of {s}",
    "cases": "Case analysis for {s}",
    "lengths": "Lengths of the parts of {s}",
    "length": "Length of {s}",
    "shape": "Shape of {s}",
    "dim": "Dimension of {s}",
    "dimension": "Dimension of {s}",
    "trace": "Trace of {s}",
    "openqasm": "OpenQASM rendering of {s}",
    "elaboration": "Elaboration of {s}",
    "elaborates": "{S} elaborates successfully",
    "compile": "Compilation of {s}",
    "quote": "Quotation of {s}",
    "interpret": "Interpretation of {s}",
    "semanticFragment": "{S} stays in the semantic fragment",
    "representable": "Representability of {s}",
    "duplicable": "Duplicability of {s}",
    "irrel": "Proof irrelevance for {s}",
    "rfl": "Definitional form of {s}",
    "def": "Defining equation of {s}",
    "eq": "Formula for {s}",
    "eq'": "Alternative formula for {s}",
    "apply": "Pointwise formula for {s}",
    "exact": "Exactness of {s}",
    "intro": "{S} on an introduced element",
    "app": "Components of {s}",
    "val": "Underlying value of {s}",
    "mem": "Membership in {s}",
    "iff": "Characterization of {s}",
    "le": "Order bound for {s}",
    "le_one": "{S} is at most one",
    "ne": "{S} is nonzero",
    "not": "{S} fails",
    "bound": "Bound on {s}",
}

# Operation atoms that read as the *argument* of a lemma ("f of a sum").
ARG_FORM: dict[str, str] = {
    "zero": "zero",
    "one": "one",
    "add": "a sum",
    "sub": "a difference",
    "mul": "a product",
    "smul": "a scalar multiple",
    "nsmul": "a natural-number multiple",
    "nnsmul": "a nonnegative multiple",
    "zsmul": "an integer multiple",
    "neg": "a negation",
    "sum": "a finite sum",
    "tsum": "an infinite sum",
    "finset": "a finite sum",
    "comp": "a composite",
    "tensor": "a tensor product",
    "id": "the identity",
    "identity": "the identity",
    "nil": "the empty list",
    "cons": "an extended list",
    "append": "a concatenation",
    "pair": "a pair",
    "unit": "the unit",
    "bot": "the bottom element",
    "top": "the top element",
    "inv": "an inverse",
    "star": "an adjoint",
    "dagger": "an adjoint",
    "conjTranspose": "a conjugate transpose",
    "swap": "a swap",
    "cast": "a transport along an equality",
    "map": "a mapped family",
    "single": "a single-entry element",
    "singleton": "a singleton",
    "intro": "an introduced element",
    "mk": "a constructed element",
    "ofReal": "a real number",
    "natCast": "a natural number",
    "pow": "a power",
    "iSup": "an indexed supremum",
    "omegaSup": "an ω-chain supremum",
    "ωSup": "an ω-chain supremum",
    "true": "true",
    "false": "false",
    "self": "itself",
    "none": "an absent cell",
    "some": "an occupied cell",
    "empty": "the empty family",
}

# Class heads of instances → noun phrase.
CLASS_NOUN: dict[str, str] = {
    "Zero": "Zero element",
    "One": "Unit element",
    "Add": "Addition",
    "Neg": "Negation",
    "SMul": "Scalar action",
    "Module": "Module structure",
    "AddCommMonoid": "Commutative additive monoid structure",
    "AddCommGroup": "Commutative additive group structure",
    "LE": "Order relation",
    "LT": "Strict order relation",
    "Preorder": "Preorder",
    "PartialOrder": "Partial order",
    "OrderBot": "Least element",
    "OrderTop": "Greatest element",
    "BoundedOrder": "Bounded order",
    "Bot": "Bottom element",
    "Top": "Top element",
    "Lattice": "Lattice structure",
    "SemilatticeInf": "Meet-semilattice structure",
    "SemilatticeSup": "Join-semilattice structure",
    "CompleteLattice": "Complete lattice structure",
    "InfSet": "Arbitrary meets",
    "SupSet": "Arbitrary joins",
    "Finite": "Finiteness",
    "Fintype": "Finite enumeration",
    "Inhabited": "Distinguished inhabitant",
    "Nonempty": "Nonemptiness",
    "Unique": "Unique inhabitant",
    "DecidableEq": "Decidable equality",
    "Decidable": "Decidability",
    "CoeFun": "Coercion to functions",
    "CoeSort": "Coercion to types",
    "Coe": "Coercion",
    "OmegaComplete": "ω-completeness",
    "IsPreorder": "Preorder property",
    "Setoid": "Equivalence relation",
    "Repr": "Printing",
    "ToString": "Printing",
    "BEq": "Boolean equality",
    "Hashable": "Hashing",
}
