#!/usr/bin/env python3
"""Generate mathematical English + Lean cards for every extracted declaration.

Reads build/declarations.jsonl and writes build/blueprint_cards/{section}.md
plus build/blueprint_thin.jsonl for cards lacking a real docstring.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECLS = ROOT / "build" / "declarations.jsonl"
OUT_DIR = ROOT / "build" / "blueprint_cards"
THIN = ROOT / "build" / "blueprint_thin.jsonl"

SECTION_TITLES = {
    "intro": "Library root",
    "sec2": "Typed linear language",
    "sec3": "Finite quantum runtime",
    "sec4": "Quantum sets, relations, and qCPOs",
    "sec5": "Type-indexed denotation and the $N$-qubit fragment",
    "sec6": "Deterministic staging to circuits",
    "sec7": "Circuit reflection, quotation, and completeness",
    "sec8": "Composer and OpenQASM interchange",
    "sec9": "Supporting quantum primitives",
    "palomar": "Palomar challenge and solution",
}

KIND_VERB = {
    "theorem": "Theorem",
    "lemma": "Lemma",
    "def": "Definition",
    "abbrev": "Abbreviation",
    "structure": "Structure",
    "class": "Type class",
    "inductive": "Inductive type",
    "instance": "Instance",
    "example": "Example",
}


def camel_to_words(name: str) -> str:
    name = name.split(".")[-1]
    name = re.sub(r"_+", " ", name)
    name = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", name)
    name = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", name)
    return name.strip().lower()


def type_gist(signature: str) -> str:
    """Pull a readable type fragment from a Lean signature."""
    one = " ".join(signature.split())
    # Drop attributes
    one = re.sub(r"@\[[^\]]*\]\s*", "", one)
    # Prefer everything after the last top-level ':' before ':=' / 'where'
    if ":=" in one:
        one = one.split(":=", 1)[0]
    if " where" in one:
        one = one.split(" where", 1)[0]
    if ":" in one:
        parts = one.split(":", 1)
        if len(parts) == 2:
            one = parts[1].strip().rstrip(":")
    # Keep Statement lines PDF-friendly under pdfLaTeX.
    if len(one) > 96:
        one = one[:93] + "..."
    return one


def statement_english(d: dict) -> str:
    doc = (d.get("docstring") or "").strip()
    if doc:
        # First paragraph only for Statement.
        para = doc.split("\n\n", 1)[0]
        para = re.sub(r"\s+", " ", para).strip()
        if para:
            return para
    kind = d["kind"]
    words = camel_to_words(d["name"])
    typ = type_gist(d.get("signature") or "")
    label = KIND_VERB.get(kind, kind.title())
    if kind in ("theorem", "lemma"):
        if typ:
            return f"{label}. {words}: `{typ}`."
        return f"{label}. {words}."
    if kind in ("def", "abbrev"):
        if typ:
            return f"{label} of `{words}` with type `{typ}`."
        return f"{label} of `{words}`."
    if kind == "structure":
        return f"Structure `{d['name']}` packaging the fields of {words}."
    if kind == "class":
        return f"Type class `{d['name']}` recording the {words} interface."
    if kind == "inductive":
        return f"Inductive type `{d['name']}` generating the {words} constructors."
    if kind == "instance":
        return f"Instance supplying {words}."
    if kind == "example":
        return f"Example checking {words}."
    return f"{label} `{d['name']}`."


def proof_english(d: dict) -> str:
    kind = d["kind"]
    doc = (d.get("docstring") or "").strip()
    if doc and "\n\n" in doc:
        rest = doc.split("\n\n", 1)[1]
        rest = re.sub(r"\s+", " ", rest).strip()
        if rest:
            return rest
    if kind in ("theorem", "lemma"):
        return (
            "Proved in Lean by the tactics and lemmas in the excerpt; "
            "the kernel checks the resulting proof term."
        )
    if kind in ("def", "abbrev"):
        return "Definitional construction; unfolding is as in the Lean excerpt."
    if kind == "structure":
        return "Record type; fields and default instances appear in the Lean excerpt."
    if kind == "class":
        return "Type-class interface; instances elsewhere discharge the fields."
    if kind == "inductive":
        return "Generated by the listed constructors; eliminators are the usual ones."
    if kind == "instance":
        return "Instance fields are filled as in the Lean excerpt."
    if kind == "example":
        return "Concrete check; Lean accepts the example when the build succeeds."
    return "See the Lean excerpt."


def card_markdown(d: dict) -> str:
    fqn = d["fqn"]
    kind = d["kind"]
    rel = d["file"]
    a, b = d["start_line"], d["end_line"]
    tag = "example" if d.get("is_example") else kind
    lines = [
        f"#### `{fqn}` (`{tag}`)",
        "",
        f"**Statement.** {statement_english(d)}",
        "",
        f"**Proof / construction.** {proof_english(d)}",
        "",
        f"<!-- lean: {rel}#L{a}-L{b} -->",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    if not DECLS.is_file():
        raise SystemExit(f"missing {DECLS}; run scripts/extract_declarations.py first")
    decls = [json.loads(line) for line in DECLS.read_text(encoding="utf-8").splitlines() if line.strip()]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    by_sec: dict[str, list[dict]] = {}
    thin: list[dict] = []
    for d in decls:
        by_sec.setdefault(d["section"], []).append(d)
        if not (d.get("docstring") or "").strip():
            thin.append({"fqn": d["fqn"], "file": d["file"], "kind": d["kind"]})

    for sec, items in by_sec.items():
        # Stable order: file then line
        items.sort(key=lambda x: (x["file"], x["start_line"], x["fqn"]))
        parts: list[str] = []
        title = SECTION_TITLES.get(sec, sec)
        parts.append(f"### Blueprint declarations — {title}\n\n")
        parts.append(
            f"*Auto-generated from the Lean sources ({len(items)} declarations). "
            "Each card states the claim in mathematical English and inlines the Lean gist.*\n\n"
        )
        # Group examples after non-examples within the same file blocks
        current_file = None
        for d in items:
            if d["file"] != current_file:
                current_file = d["file"]
                parts.append(f"#### Module `{current_file}`\n\n")
            parts.append(card_markdown(d))
        (OUT_DIR / f"{sec}.md").write_text("".join(parts), encoding="utf-8")

    with THIN.open("w", encoding="utf-8") as f:
        for t in thin:
            f.write(json.dumps(t) + "\n")
    print(
        f"wrote {OUT_DIR} ({len(decls)} cards across {len(by_sec)} sections); "
        f"{len(thin)} thin (no docstring) listed in {THIN}"
    )


if __name__ == "__main__":
    main()
