/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import QLambda.Domain.Presheaf.SymmetricPower

/-!
# Closed coefficient codes
-/

namespace QLambda.Domain.Presheaf

namespace SuperoperatorModule

/-- Coefficient modules generated by representables, symmetric powers, and
repeated internal hom with a representable domain. -/
inductive ClosedCoefficient where
  | representable (dimension : ℕ)
  | symmetricPower (dimension degree : ℕ)
  | internalHomRepresentable (domain : ℕ) (codomain : ClosedCoefficient)

namespace ClosedCoefficient

/-- Concrete interpretation of a generated coefficient code. -/
noncomputable def toModule : ClosedCoefficient → Module
  | .representable n => SuperoperatorModule.representable n
  | .symmetricPower A k => SuperoperatorModule.symmetricPower A k
  | .internalHomRepresentable A B =>
      SuperoperatorModule.internalHomRepresentable A B.toModule

/-- Day tensor of two representable coefficients. -/
def tensorRepresentable (A B : ℕ) : ClosedCoefficient :=
  .representable (A * B)

@[simp]
theorem toModule_tensorRepresentable (A B : ℕ) :
    (tensorRepresentable A B).toModule =
      dayTensorRepresentable A B :=
  rfl

/-- Internal hom by a representable remains in the generated coefficient
fragment. -/
def hom (A : ℕ) (B : ClosedCoefficient) : ClosedCoefficient :=
  .internalHomRepresentable A B

@[simp]
theorem toModule_hom (A : ℕ) (B : ClosedCoefficient) :
    (hom A B).toModule =
      SuperoperatorModule.internalHomRepresentable A B.toModule :=
  rfl

end ClosedCoefficient

end SuperoperatorModule

end QLambda.Domain.Presheaf
