/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import QLambda.Domain.Presheaf.SymmetricPower

/-!
# The concretely closed generated coefficient fragment

Representables are closed under Day tensor, finite tensor-factor-invariant
symmetric powers are concrete submodules, and internal hom with a
representable domain is concrete.  The inductive codes below record exactly
that coefficient closure.  They do not claim that every basis-generated
module is a coefficient object.
-/

namespace QLambda.Domain.Presheaf

namespace SuperoperatorModule

/-- Coefficient modules generated by representables, symmetric powers, and
repeated internal hom with a representable domain. -/
inductive ClosedCoefficient where
  | representable (dimension : ℕ)
  | symmetricPower (dimension degree : ℕ)
  | internalHomRepresentable (domain : ℕ) (codomain : ClosedCoefficient)

namespace ClosedCoefficient

/-- Concrete interpretation of a generated coefficient code. -/
noncomputable def toModule : ClosedCoefficient → Module
  | .representable n => SuperoperatorModule.representable n
  | .symmetricPower A k => SuperoperatorModule.symmetricPower A k
  | .internalHomRepresentable A B =>
      SuperoperatorModule.internalHomRepresentable A B.toModule

/-- Day tensor of two representable coefficients. -/
def tensorRepresentable (A B : ℕ) : ClosedCoefficient :=
  .representable (A * B)

@[simp]
theorem toModule_tensorRepresentable (A B : ℕ) :
    (tensorRepresentable A B).toModule =
      dayTensorRepresentable A B :=
  rfl

/-- Internal hom by a representable remains in the generated coefficient
fragment. -/
def hom (A : ℕ) (B : ClosedCoefficient) : ClosedCoefficient :=
  .internalHomRepresentable A B

@[simp]
theorem toModule_hom (A : ℕ) (B : ClosedCoefficient) :
    (hom A B).toModule =
      SuperoperatorModule.internalHomRepresentable A B.toModule :=
  rfl

end ClosedCoefficient

/-- A countably based module whose coefficient objects all belong to the
concretely closed coefficient fragment. -/
structure ClosedBasis (M : Module) where
  Index : Type
  countableIndex : Countable Index
  coeff : Index → ClosedCoefficient
  ket : ∀ i, Hom (coeff i).toModule M
  bra : ∀ i, Hom M (coeff i).toModule
  resolves :
    Hom.HasSum
      (fun i : Index => Hom.comp (ket i) (bra i))
      (Hom.id M)

attribute [instance] ClosedBasis.countableIndex

/-- A module with an exhibited basis from the concrete closed coefficient
fragment. -/
structure ClosedGenerated where
  module : Module
  basis : ClosedBasis module

/-- A symmetric tensor power is a concrete one-coefficient generated
object. -/
noncomputable def closedSymmetricPower (A k : ℕ) : ClosedGenerated where
  module := symmetricPower A k
  basis :=
    { Index := PUnit
      countableIndex := inferInstance
      coeff := fun _ => .symmetricPower A k
      ket := fun _ => Hom.id _
      bra := fun _ => Hom.id _
      resolves := by
        intro n x
        change ((symmetricPower A k).obj n).HasSum
          (fun _ : PUnit => x) x
        exact ((symmetricPower A k).obj n).summation.singleton x }

/-- Every representable belongs to the concretely closed generated
subcategory. -/
noncomputable def closedRepresentable (A : ℕ) : ClosedGenerated where
  module := representable A
  basis :=
    { Index := PUnit
      countableIndex := inferInstance
      coeff := fun _ => .representable A
      ket := fun _ => Hom.id _
      bra := fun _ => Hom.id _
      resolves := by
        intro n x
        change ((representable A).obj n).HasSum
          (fun _ : PUnit => x) x
        exact ((representable A).obj n).summation.singleton x }

/-- The Day tensor of two representables is again a closed-generated object. -/
noncomputable def closedTensorRepresentable (A B : ℕ) : ClosedGenerated :=
  closedRepresentable (A * B)

@[simp]
theorem closedTensorRepresentable_module (A B : ℕ) :
    (closedTensorRepresentable A B).module =
      dayTensorRepresentable A B :=
  rfl

/-- Internal hom from a representable to a generated coefficient is itself a
closed-generated one-coefficient object. -/
noncomputable def closedInternalHomRepresentable
    (A : ℕ) (B : ClosedCoefficient) : ClosedGenerated where
  module := internalHomRepresentable A B.toModule
  basis :=
    { Index := PUnit
      countableIndex := inferInstance
      coeff := fun _ => B.hom A
      ket := fun _ => Hom.id _
      bra := fun _ => Hom.id _
      resolves := by
        intro n x
        change ((internalHomRepresentable A B.toModule).obj n).HasSum
          (fun _ : PUnit => x) x
        exact
          ((internalHomRepresentable A B.toModule).obj n).summation.singleton x }

@[simp]
theorem closedInternalHomRepresentable_module
    (A : ℕ) (B : ClosedCoefficient) :
    (closedInternalHomRepresentable A B).module =
      internalHomRepresentable A B.toModule :=
  rfl

end SuperoperatorModule

end QLambda.Domain.Presheaf
