/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import QLambda.Composer.WellFormed
import QLambda.Syntax

/-!
# Emit-kernel qλ source syntax

The surface language is the untyped call-by-value λ-calculus with the three
choices and one quantum boundary, `emit I`.  A separate first-order `Command`
is the terminating residual accepted by the Composer compiler.  This keeps
the source grammar context-free while making the compilation boundary
explicit rather than pretending that every untyped term terminates.
-/

namespace QLambda.Source

abbrev ChoiceId := Nat

/-- A probability together with the bounds needed by the physical coin. -/
structure Probability where
  val : QLambda.Prob
  nonneg : 0 ≤ val
  le_one : val ≤ 1

/-- Untyped call-by-value source terms. -/
inductive Term (q c : ℕ) where
  | var : Name → Term q c
  | lam : Name → Term q c → Term q c
  | app : Term q c → Term q c → Term q c
  | unit
  | emit : Composer.Instr q c → Term q c
  | seq : Term q c → Term q c → Term q c
  | prob : Probability → Term q c → Term q c → Term q c
  | intern : ChoiceId → Term q c → Term q c → Term q c
  | extern : Composer.CExpr c → Term q c → Term q c → Term q c

/-- First-order, finite residual generated by CBV staging. -/
inductive Command (q c : ℕ) where
  | skip
  | emit : Composer.Instr q c → Command q c
  | seq : Command q c → Command q c → Command q c
  | prob : Probability → Command q c → Command q c → Command q c
  | intern : ChoiceId → Command q c → Command q c → Command q c
  | extern : Composer.CExpr c → Command q c → Command q c → Command q c

namespace Term

def free {q c : ℕ} : Term q c → List Name
  | .var x => [x]
  | .lam x M => (free M).filter (· ≠ x)
  | .app M N => free M ++ free N
  | .unit | .emit _ => []
  | .seq M N | .prob _ M N | .intern _ M N | .extern _ M N => free M ++ free N

def Closed {q c : ℕ} (M : Term q c) : Prop :=
  free M = []

/-- Capture-avoiding substitution is only needed by the staging relation.
The binder is renamed when its name occurs free in the replacement. -/
def rename {q c : ℕ} (M : Term q c) (old fresh : Name) : Term q c :=
  match M with
  | .var x => if x = old then .var fresh else .var x
  | .lam x body =>
      if x = old then .lam fresh (rename body old fresh)
      else .lam x (rename body old fresh)
  | .app F A => .app (rename F old fresh) (rename A old fresh)
  | .unit => .unit
  | .emit i => .emit i
  | .seq A B => .seq (rename A old fresh) (rename B old fresh)
  | .prob p A B => .prob p (rename A old fresh) (rename B old fresh)
  | .intern id A B => .intern id (rename A old fresh) (rename B old fresh)
  | .extern e A B => .extern e (rename A old fresh) (rename B old fresh)

/-- A deterministic fresh name for substitution. -/
def fresh {q c : ℕ} (M N : Term q c) (x : Name) : Name :=
  x ++ "#" ++ toString (M.free.length + N.free.length)

partial def subst {q c : ℕ} (M : Term q c) (x : Name) (V : Term q c) : Term q c :=
  match M with
  | .var y => if y = x then V else .var y
  | .lam y body =>
      if y = x then .lam y body
      else if y ∈ V.free then
        let z := fresh body V y
        .lam z (subst (rename body y z) x V)
      else .lam y (subst body x V)
  | .app F A => .app (subst F x V) (subst A x V)
  | .unit => .unit
  | .emit i => .emit i
  | .seq A B => .seq (subst A x V) (subst B x V)
  | .prob p A B => .prob p (subst A x V) (subst B x V)
  | .intern id A B => .intern id (subst A x V) (subst B x V)
  | .extern e A B => .extern e (subst A x V) (subst B x V)
inductive Value {q c : ℕ} : Term q c → Prop
  | unit : Value .unit
  | lam {x body} : Value (.lam x body)

end Term

namespace Command

/-- Circuit well-formedness is separate from the context-free grammar. -/
inductive WellFormed {q c : ℕ} : Command q c → Prop
  | skip : WellFormed .skip
  | emit {i} :
      Composer.Instr.WellFormedAt 0 i →
      WellFormed (.emit i)
  | seq {A B} : WellFormed A → WellFormed B → WellFormed (.seq A B)
  | prob {p A B} : WellFormed A → WellFormed B → WellFormed (.prob p A B)
  | intern {id A B} : WellFormed A → WellFormed B → WellFormed (.intern id A B)
  | extern {e A B} : WellFormed A → WellFormed B → WellFormed (.extern e A B)

/-- Embed a residual command back into source syntax. -/
def quote {q c : ℕ} : Command q c → Term q c
  | .skip => .unit
  | .emit i => .emit i
  | .seq A B => .seq (quote A) (quote B)
  | .prob p A B => .prob p (quote A) (quote B)
  | .intern id A B => .intern id (quote A) (quote B)
  | .extern e A B => .extern e (quote A) (quote B)

end Command

/-- CBV staging relation from closed higher-order syntax to finite commands.

This relation, rather than a total function on untyped terms, records the
termination premise of the compiler. -/
inductive Elaborates {q c : ℕ} : Term q c → Command q c → Prop
  | skip : Elaborates .unit .skip
  | emit {i} : Elaborates (.emit i) (.emit i)
  | seq {M N A B} :
      Elaborates M A → Elaborates N B →
      Elaborates (.seq M N) (.seq A B)
  | prob {p M N A B} :
      Elaborates M A → Elaborates N B →
      Elaborates (.prob p M N) (.prob p A B)
  | intern {id M N A B} :
      Elaborates M A → Elaborates N B →
      Elaborates (.intern id M N) (.intern id A B)
  | extern {e M N A B} :
      Elaborates M A → Elaborates N B →
      Elaborates (.extern e M N) (.extern e A B)
  | beta {x body V C} :
      Term.Value V →
      Elaborates (Term.subst body x V) C →
      Elaborates (.app (.lam x body) V) C

end QLambda.Source
